In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/mukengane/Desktop/DS_Python_Class/Titanic data/train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df_dict = df.set_index('PassengerId').T.to_dict('list')

In [5]:
df_dict

{1: [0,
  3,
  'Braund, Mr. Owen Harris',
  'male',
  22.0,
  1,
  0,
  'A/5 21171',
  7.25,
  nan,
  'S'],
 2: [1,
  1,
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  38.0,
  1,
  0,
  'PC 17599',
  71.2833,
  'C85',
  'C'],
 3: [1,
  3,
  'Heikkinen, Miss. Laina',
  'female',
  26.0,
  0,
  0,
  'STON/O2. 3101282',
  7.925,
  nan,
  'S'],
 4: [1,
  1,
  'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'female',
  35.0,
  1,
  0,
  '113803',
  53.1,
  'C123',
  'S'],
 5: [0,
  3,
  'Allen, Mr. William Henry',
  'male',
  35.0,
  0,
  0,
  '373450',
  8.05,
  nan,
  'S'],
 6: [0, 3, 'Moran, Mr. James', 'male', nan, 0, 0, '330877', 8.4583, nan, 'Q'],
 7: [0,
  1,
  'McCarthy, Mr. Timothy J',
  'male',
  54.0,
  0,
  0,
  '17463',
  51.8625,
  'E46',
  'S'],
 8: [0,
  3,
  'Palsson, Master. Gosta Leonard',
  'male',
  2.0,
  3,
  1,
  '349909',
  21.075,
  nan,
  'S'],
 9: [1,
  3,
  'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'female',
  27.0,
  0,
  2,
  '347742',
  11.1333,
  nan,
  'S'],
 10: [1,
  2,
  'Nasser, Mrs. Nicholas (Adele Achem)',
  'female',
  14.0,
  1,
  0,
  '237736',
  30.0708,
  nan,
  'C'],
 11: [1,
  3,
  'Sandstrom, Miss. Marguerite Rut',
  'female',
  4.0,
  1,
  1,
  'PP 9549',
  16.7,
  'G6',
  'S'],
 12: [1,
  1,
  'Bonnell, Miss. Elizabeth',
  'female',
  58.0,
  0,
  0,
  '113783',
  26.55,
  'C103',
  'S'],
 13: [0,
  3,
  'Saundercock, Mr. William Henry',
  'male',
  20.0,
  0,
  0,
  'A/5. 2151',
  8.05,
  nan,
  'S'],
 14: [0,
  3,
  'Andersson, Mr. Anders Johan',
  'male',
  39.0,
  1,
  5,
  '347082',
  31.275,
  nan,
  'S'],
 15: [0,
  3,
  'Vestrom, Miss. Hulda Amanda Adolfina',
  'female',
  14.0,
  0,
  0,
  '350406',
  7.8542,
  nan,
  'S'],
 16: [1,
  2,
  'Hewlett, Mrs. (Mary D Kingcome) ',
  'female',
  55.0,
  0,
  0,
  '248706',
  16.0,
  nan,
  'S'],
 17: [0,
  3,
  'Rice, Master. Eugene',
  'male',
  2.0,
  4,
  1,
  '382652',
  29.125,
  nan,
  'Q'],
 18: [1,
  2,
  'Williams, Mr. Charles Eugene',
  'male',
  nan,
  0,
  0,
  '244373',
  13.0,
  nan,
  'S'],
 19: [0,
  3,
  'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'female',
  31.0,
  1,
  0,
  '345763',
  18.0,
  nan,
  'S'],
 20: [1,
  3,
  'Masselmani, Mrs. Fatima',
  'female',
  nan,
  0,
  0,
  '2649',
  7.225,
  nan,
  'C'],
 21: [0,
  2,
  'Fynney, Mr. Joseph J',
  'male',
  35.0,
  0,
  0,
  '239865',
  26.0,
  nan,
  'S'],
 22: [1,
  2,
  'Beesley, Mr. Lawrence',
  'male',
  34.0,
  0,
  0,
  '248698',
  13.0,
  'D56',
  'S'],
 23: [1,
  3,
  'McGowan, Miss. Anna "Annie"',
  'female',
  15.0,
  0,
  0,
  '330923',
  8.0292,
  nan,
  'Q'],
 24: [1,
  1,
  'Sloper, Mr. William Thompson',
  'male',
  28.0,
  0,
  0,
  '113788',
  35.5,
  'A6',
  'S'],
 25: [0,
  3,
  'Palsson, Miss. Torborg Danira',
  'female',
  8.0,
  3,
  1,
  '349909',
  21.075,
  nan,
  'S'],
 26: [1,
  3,
  'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'female',
  38.0,
  1,
  5,
  '347077',
  31.3875,
  nan,
  'S'],
 27: [0,
  3,
  'Emir, Mr. Farred Chehab',
  'male',
  nan,
  0,
  0,
  '2631',
  7.225,
  nan,
  'C'],
 28: [0,
  1,
  'Fortune, Mr. Charles Alexander',
  'male',
  19.0,
  3,
  2,
  '19950',
  263.0,
  'C23 C25 C27',
  'S'],
 29: [1,
  3,
  'O\'Dwyer, Miss. Ellen "Nellie"',
  'female',
  nan,
  0,
  0,
  '330959',
  7.8792,
  nan,
  'Q'],
 30: [0,
  3,
  'Todoroff, Mr. Lalio',
  'male',
  nan,
  0,
  0,
  '349216',
  7.8958,
  nan,
  'S'],
 31: [0,
  1,
  'Uruchurtu, Don. Manuel E',
  'male',
  40.0,
  0,
  0,
  'PC 17601',
  27.7208,
  nan,
  'C'],
 32: [1,
  1,
  'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'female',
  nan,
  1,
  0,
  'PC 17569',
  146.5208,
  'B78',
  'C'],
 33: [1,
  3,
  'Glynn, Miss. Mary Agatha',
  'female',
  nan,
  0,
  0,
  '335677',
  7.75,
  nan,
  'Q'],
 34: [0,
  2,
  'Wheadon, Mr. Edward H',
  'male',
  66.0,
  0,
  0,
  'C.A. 24579',
  10.5,
  nan,
  'S'],
 35: [0,
  1,
  'Meyer, Mr. Edgar Joseph',
  'male',
  28.0,
  1,
  0,
  'PC 17604',
  82.1708,
  nan,
  'C'],
 36: [0,
  1,
  'Holverson, Mr. Alexander Oskar',
  'male',
  42.0,
  1,
  0,
  '113789',
  52.0,
  nan,
  'S'],
 37: [1, 3, 'Mamee, Mr. Hanna', 'male', nan, 0, 0, '2677', 7.2292, nan, 'C'],
 38: [0,
  3,
  'Cann, Mr. Ernest Charles',
  'male',
  21.0,
  0,
  0,
  'A./5. 2152',
  8.05,
  nan,
  'S'],
 39: [0,
  3,
  'Vander Planke, Miss. Augusta Maria',
  'female',
  18.0,
  2,
  0,
  '345764',
  18.0,
  nan,
  'S'],
 40: [1,
  3,
  'Nicola-Yarred, Miss. Jamila',
  'female',
  14.0,
  1,
  0,
  '2651',
  11.2417,
  nan,
  'C'],
 41: [0,
  3,
  'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'female',
  40.0,
  1,
  0,
  '7546',
  9.475,
  nan,
  'S'],
 42: [0,
  2,
  'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'female',
  27.0,
  1,
  0,
  '11668',
  21.0,
  nan,
  'S'],
 43: [0,
  3,
  'Kraeff, Mr. Theodor',
  'male',
  nan,
  0,
  0,
  '349253',
  7.8958,
  nan,
  'C'],
 44: [1,
  2,
  'Laroche, Miss. Simonne Marie Anne Andree',
  'female',
  3.0,
  1,
  2,
  'SC/Paris 2123',
  41.5792,
  nan,
  'C'],
 45: [1,
  3,
  'Devaney, Miss. Margaret Delia',
  'female',
  19.0,
  0,
  0,
  '330958',
  7.8792,
  nan,
  'Q'],
 46: [0,
  3,
  'Rogers, Mr. William John',
  'male',
  nan,
  0,
  0,
  'S.C./A.4. 23567',
  8.05,
  nan,
  'S'],
 47: [0, 3, 'Lennon, Mr. Denis', 'male', nan, 1, 0, '370371', 15.5, nan, 'Q'],
 48: [1,
  3,
  "O'Driscoll, Miss. Bridget",
  'female',
  nan,
  0,
  0,
  '14311',
  7.75,
  nan,
  'Q'],
 49: [0,
  3,
  'Samaan, Mr. Youssef',
  'male',
  nan,
  2,
  0,
  '2662',
  21.6792,
  nan,
  'C'],
 50: [0,
  3,
  'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'female',
  18.0,
  1,
  0,
  '349237',
  17.8,
  nan,
  'S'],
 51: [0,
  3,
  'Panula, Master. Juha Niilo',
  'male',
  7.0,
  4,
  1,
  '3101295',
  39.6875,
  nan,
  'S'],
 52: [0,
  3,
  'Nosworthy, Mr. Richard Cater',
  'male',
  21.0,
  0,
  0,
  'A/4. 39886',
  7.8,
  nan,
  'S'],
 53: [1,
  1,
  'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'female',
  49.0,
  1,
  0,
  'PC 17572',
  76.7292,
  'D33',
  'C'],
 54: [1,
  2,
  'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'female',
  29.0,
  1,
  0,
  '2926',
  26.0,
  nan,
  'S'],
 55: [0,
  1,
  'Ostby, Mr. Engelhart Cornelius',
  'male',
  65.0,
  0,
  1,
  '113509',
  61.9792,
  'B30',
  'C'],
 56: [1, 1, 'Woolner, Mr. Hugh', 'male', nan, 0, 0, '19947', 35.5, 'C52', 'S'],
 57: [1,
  2,
  'Rugg, Miss. Emily',
  'female',
  21.0,
  0,
  0,
  'C.A. 31026',
  10.5,
  nan,
  'S'],
 58: [0,
  3,
  'Novel, Mr. Mansouer',
  'male',
  28.5,
  0,
  0,
  '2697',
  7.2292,
  nan,
  'C'],
 59: [1,
  2,
  'West, Miss. Constance Mirium',
  'female',
  5.0,
  1,
  2,
  'C.A. 34651',
  27.75,
  nan,
  'S'],
 60: [0,
  3,
  'Goodwin, Master. William Frederick',
  'male',
  11.0,
  5,
  2,
  'CA 2144',
  46.9,
  nan,
  'S'],
 61: [0,
  3,
  'Sirayanian, Mr. Orsen',
  'male',
  22.0,
  0,
  0,
  '2669',
  7.2292,
  nan,
  'C'],
 62: [1,
  1,
  'Icard, Miss. Amelie',
  'female',
  38.0,
  0,
  0,
  '113572',
  80.0,
  'B28',
  nan],
 63: [0,
  1,
  'Harris, Mr. Henry Birkhardt',
  'male',
  45.0,
  1,
  0,
  '36973',
  83.475,
  'C83',
  'S'],
 64: [0,
  3,
  'Skoog, Master. Harald',
  'male',
  4.0,
  3,
  2,
  '347088',
  27.9,
  nan,
  'S'],
 65: [0,
  1,
  'Stewart, Mr. Albert A',
  'male',
  nan,
  0,
  0,
  'PC 17605',
  27.7208,
  nan,
  'C'],
 66: [1,
  3,
  'Moubarek, Master. Gerios',
  'male',
  nan,
  1,
  1,
  '2661',
  15.2458,
  nan,
  'C'],
 67: [1,
  2,
  'Nye, Mrs. (Elizabeth Ramell)',
  'female',
  29.0,
  0,
  0,
  'C.A. 29395',
  10.5,
  'F33',
  'S'],
 68: [0,
  3,
  'Crease, Mr. Ernest James',
  'male',
  19.0,
  0,
  0,
  'S.P. 3464',
  8.1583,
  nan,
  'S'],
 69: [1,
  3,
  'Andersson, Miss. Erna Alexandra',
  'female',
  17.0,
  4,
  2,
  '3101281',
  7.925,
  nan,
  'S'],
 70: [0,
  3,
  'Kink, Mr. Vincenz',
  'male',
  26.0,
  2,
  0,
  '315151',
  8.6625,
  nan,
  'S'],
 71: [0,
  2,
  'Jenkin, Mr. Stephen Curnow',
  'male',
  32.0,
  0,
  0,
  'C.A. 33111',
  10.5,
  nan,
  'S'],
 72: [0,
  3,
  'Goodwin, Miss. Lillian Amy',
  'female',
  16.0,
  5,
  2,
  'CA 2144',
  46.9,
  nan,
  'S'],
 73: [0,
  2,
  'Hood, Mr. Ambrose Jr',
  'male',
  21.0,
  0,
  0,
  'S.O.C. 14879',
  73.5,
  nan,
  'S'],
 74: [0,
  3,
  'Chronopoulos, Mr. Apostolos',
  'male',
  26.0,
  1,
  0,
  '2680',
  14.4542,
  nan,
  'C'],
 75: [1, 3, 'Bing, Mr. Lee', 'male', 32.0, 0, 0, '1601', 56.4958, nan, 'S'],
 76: [0,
  3,
  'Moen, Mr. Sigurd Hansen',
  'male',
  25.0,
  0,
  0,
  '348123',
  7.65,
  'F G73',
  'S'],
 77: [0,
  3,
  'Staneff, Mr. Ivan',
  'male',
  nan,
  0,
  0,
  '349208',
  7.8958,
  nan,
  'S'],
 78: [0,
  3,
  'Moutal, Mr. Rahamin Haim',
  'male',
  nan,
  0,
  0,
  '374746',
  8.05,
  nan,
  'S'],
 79: [1,
  2,
  'Caldwell, Master. Alden Gates',
  'male',
  0.83,
  0,
  2,
  '248738',
  29.0,
  nan,
  'S'],
 80: [1,
  3,
  'Dowdell, Miss. Elizabeth',
  'female',
  30.0,
  0,
  0,
  '364516',
  12.475,
  nan,
  'S'],
 81: [0,
  3,
  'Waelens, Mr. Achille',
  'male',
  22.0,
  0,
  0,
  '345767',
  9.0,
  nan,
  'S'],
 82: [1,
  3,
  'Sheerlinck, Mr. Jan Baptist',
  'male',
  29.0,
  0,
  0,
  '345779',
  9.5,
  nan,
  'S'],
 83: [1,
  3,
  'McDermott, Miss. Brigdet Delia',
  'female',
  nan,
  0,
  0,
  '330932',
  7.7875,
  nan,
  'Q'],
 84: [0,
  1,
  'Carrau, Mr. Francisco M',
  'male',
  28.0,
  0,
  0,
  '113059',
  47.1,
  nan,
  'S'],
 85: [1,
  2,
  'Ilett, Miss. Bertha',
  'female',
  17.0,
  0,
  0,
  'SO/C 14885',
  10.5,
  nan,
  'S'],
 86: [1,
  3,
  'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
  'female',
  33.0,
  3,
  0,
  '3101278',
  15.85,
  nan,
  'S'],
 87: [0,
  3,
  'Ford, Mr. William Neal',
  'male',
  16.0,
  1,
  3,
  'W./C. 6608',
  34.375,
  nan,
  'S'],
 88: [0,
  3,
  'Slocovski, Mr. Selman Francis',
  'male',
  nan,
  0,
  0,
  'SOTON/OQ 392086',
  8.05,
  nan,
  'S'],
 89: [1,
  1,
  'Fortune, Miss. Mabel Helen',
  'female',
  23.0,
  3,
  2,
  '19950',
  263.0,
  'C23 C25 C27',
  'S'],
 90: [0,
  3,
  'Celotti, Mr. Francesco',
  'male',
  24.0,
  0,
  0,
  '343275',
  8.05,
  nan,
  'S'],
 91: [0,
  3,
  'Christmann, Mr. Emil',
  'male',
  29.0,
  0,
  0,
  '343276',
  8.05,
  nan,
  'S'],
 92: [0,
  3,
  'Andreasson, Mr. Paul Edvin',
  'male',
  20.0,
  0,
  0,
  '347466',
  7.8542,
  nan,
  'S'],
 93: [0,
  1,
  'Chaffee, Mr. Herbert Fuller',
  'male',
  46.0,
  1,
  0,
  'W.E.P. 5734',
  61.175,
  'E31',
  'S'],
 94: [0,
  3,
  'Dean, Mr. Bertram Frank',
  'male',
  26.0,
  1,
  2,
  'C.A. 2315',
  20.575,
  nan,
  'S'],
 95: [0, 3, 'Coxon, Mr. Daniel', 'male', 59.0, 0, 0, '364500', 7.25, nan, 'S'],
 96: [0,
  3,
  'Shorney, Mr. Charles Joseph',
  'male',
  nan,
  0,
  0,
  '374910',
  8.05,
  nan,
  'S'],
 97: [0,
  1,
  'Goldschmidt, Mr. George B',
  'male',
  71.0,
  0,
  0,
  'PC 17754',
  34.6542,
  'A5',
  'C'],
 98: [1,
  1,
  'Greenfield, Mr. William Bertram',
  'male',
  23.0,
  0,
  1,
  'PC 17759',
  63.3583,
  'D10 D12',
  'C'],
 99: [1,
  2,
  'Doling, Mrs. John T (Ada Julia Bone)',
  'female',
  34.0,
  0,
  1,
  '231919',
  23.0,
  nan,
  'S'],
 100: [0,
  2,
  'Kantor, Mr. Sinai',
  'male',
  34.0,
  1,
  0,
  '244367',
  26.0,
  nan,
  'S'],
 101: [0,
  3,
  'Petranec, Miss. Matilda',
  'female',
  28.0,
  0,
  0,
  '349245',
  7.8958,
  nan,
  'S'],
 102: [0,
  3,
  'Petroff, Mr. Pastcho ("Pentcho")',
  'male',
  nan,
  0,
  0,
  '349215',
  7.8958,
  nan,
  'S'],
 103: [0,
  1,
  'White, Mr. Richard Frasar',
  'male',
  21.0,
  0,
  1,
  '35281',
  77.2875,
  'D26',
  'S'],
 104: [0,
  3,
  'Johansson, Mr. Gustaf Joel',
  'male',
  33.0,
  0,
  0,
  '7540',
  8.6542,
  nan,
  'S'],
 105: [0,
  3,
  'Gustafsson, Mr. Anders Vilhelm',
  'male',
  37.0,
  2,
  0,
  '3101276',
  7.925,
  nan,
  'S'],
 106: [0,
  3,
  'Mionoff, Mr. Stoytcho',
  'male',
  28.0,
  0,
  0,
  '349207',
  7.8958,
  nan,
  'S'],
 107: [1,
  3,
  'Salkjelsvik, Miss. Anna Kristine',
  'female',
  21.0,
  0,
  0,
  '343120',
  7.65,
  nan,
  'S'],
 108: [1,
  3,
  'Moss, Mr. Albert Johan',
  'male',
  nan,
  0,
  0,
  '312991',
  7.775,
  nan,
  'S'],
 109: [0,
  3,
  'Rekic, Mr. Tido',
  'male',
  38.0,
  0,
  0,
  '349249',
  7.8958,
  nan,
  'S'],
 110: [1,
  3,
  'Moran, Miss. Bertha',
  'female',
  nan,
  1,
  0,
  '371110',
  24.15,
  nan,
  'Q'],
 111: [0,
  1,
  'Porter, Mr. Walter Chamberlain',
  'male',
  47.0,
  0,
  0,
  '110465',
  52.0,
  'C110',
  'S'],
 112: [0,
  3,
  'Zabour, Miss. Hileni',
  'female',
  14.5,
  1,
  0,
  '2665',
  14.4542,
  nan,
  'C'],
 113: [0,
  3,
  'Barton, Mr. David John',
  'male',
  22.0,
  0,
  0,
  '324669',
  8.05,
  nan,
  'S'],
 114: [0,
  3,
  'Jussila, Miss. Katriina',
  'female',
  20.0,
  1,
  0,
  '4136',
  9.825,
  nan,
  'S'],
 115: [0,
  3,
  'Attalah, Miss. Malake',
  'female',
  17.0,
  0,
  0,
  '2627',
  14.4583,
  nan,
  'C'],
 116: [0,
  3,
  'Pekoniemi, Mr. Edvard',
  'male',
  21.0,
  0,
  0,
  'STON/O 2. 3101294',
  7.925,
  nan,
  'S'],
 117: [0,
  3,
  'Connors, Mr. Patrick',
  'male',
  70.5,
  0,
  0,
  '370369',
  7.75,
  nan,
  'Q'],
 118: [0,
  2,
  'Turpin, Mr. William John Robert',
  'male',
  29.0,
  1,
  0,
  '11668',
  21.0,
  nan,
  'S'],
 119: [0,
  1,
  'Baxter, Mr. Quigg Edmond',
  'male',
  24.0,
  0,
  1,
  'PC 17558',
  247.5208,
  'B58 B60',
  'C'],
 120: [0,
  3,
  'Andersson, Miss. Ellis Anna Maria',
  'female',
  2.0,
  4,
  2,
  '347082',
  31.275,
  nan,
  'S'],
 121: [0,
  2,
  'Hickman, Mr. Stanley George',
  'male',
  21.0,
  2,
  0,
  'S.O.C. 14879',
  73.5,
  nan,
  'S'],
 122: [0,
  3,
  'Moore, Mr. Leonard Charles',
  'male',
  nan,
  0,
  0,
  'A4. 54510',
  8.05,
  nan,
  'S'],
 123: [0,
  2,
  'Nasser, Mr. Nicholas',
  'male',
  32.5,
  1,
  0,
  '237736',
  30.0708,
  nan,
  'C'],
 124: [1,
  2,
  'Webber, Miss. Susan',
  'female',
  32.5,
  0,
  0,
  '27267',
  13.0,
  'E101',
  'S'],
 125: [0,
  1,
  'White, Mr. Percival Wayland',
  'male',
  54.0,
  0,
  1,
  '35281',
  77.2875,
  'D26',
  'S'],
 126: [1,
  3,
  'Nicola-Yarred, Master. Elias',
  'male',
  12.0,
  1,
  0,
  '2651',
  11.2417,
  nan,
  'C'],
 127: [0,
  3,
  'McMahon, Mr. Martin',
  'male',
  nan,
  0,
  0,
  '370372',
  7.75,
  nan,
  'Q'],
 128: [1,
  3,
  'Madsen, Mr. Fridtjof Arne',
  'male',
  24.0,
  0,
  0,
  'C 17369',
  7.1417,
  nan,
  'S'],
 129: [1,
  3,
  'Peter, Miss. Anna',
  'female',
  nan,
  1,
  1,
  '2668',
  22.3583,
  'F E69',
  'C'],
 130: [0,
  3,
  'Ekstrom, Mr. Johan',
  'male',
  45.0,
  0,
  0,
  '347061',
  6.975,
  nan,
  'S'],
 131: [0,
  3,
  'Drazenoic, Mr. Jozef',
  'male',
  33.0,
  0,
  0,
  '349241',
  7.8958,
  nan,
  'C'],
 132: [0,
  3,
  'Coelho, Mr. Domingos Fernandeo',
  'male',
  20.0,
  0,
  0,
  'SOTON/O.Q. 3101307',
  7.05,
  nan,
  'S'],
 133: [0,
  3,
  'Robins, Mrs. Alexander A (Grace Charity Laury)',
  'female',
  47.0,
  1,
  0,
  'A/5. 3337',
  14.5,
  nan,
  'S'],
 134: [1,
  2,
  'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
  'female',
  29.0,
  1,
  0,
  '228414',
  26.0,
  nan,
  'S'],
 135: [0,
  2,
  'Sobey, Mr. Samuel James Hayden',
  'male',
  25.0,
  0,
  0,
  'C.A. 29178',
  13.0,
  nan,
  'S'],
 136: [0,
  2,
  'Richard, Mr. Emile',
  'male',
  23.0,
  0,
  0,
  'SC/PARIS 2133',
  15.0458,
  nan,
  'C'],
 137: [1,
  1,
  'Newsom, Miss. Helen Monypeny',
  'female',
  19.0,
  0,
  2,
  '11752',
  26.2833,
  'D47',
  'S'],
 138: [0,
  1,
  'Futrelle, Mr. Jacques Heath',
  'male',
  37.0,
  1,
  0,
  '113803',
  53.1,
  'C123',
  'S'],
 139: [0,
  3,
  'Osen, Mr. Olaf Elon',
  'male',
  16.0,
  0,
  0,
  '7534',
  9.2167,
  nan,
  'S'],
 140: [0,
  1,
  'Giglio, Mr. Victor',
  'male',
  24.0,
  0,
  0,
  'PC 17593',
  79.2,
  'B86',
  'C'],
 141: [0,
  3,
  'Boulos, Mrs. Joseph (Sultana)',
  'female',
  nan,
  0,
  2,
  '2678',
  15.2458,
  nan,
  'C'],
 142: [1,
  3,
  'Nysten, Miss. Anna Sofia',
  'female',
  22.0,
  0,
  0,
  '347081',
  7.75,
  nan,
  'S'],
 143: [1,
  3,
  'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
  'female',
  24.0,
  1,
  0,
  'STON/O2. 3101279',
  15.85,
  nan,
  'S'],
 144: [0,
  3,
  'Burke, Mr. Jeremiah',
  'male',
  19.0,
  0,
  0,
  '365222',
  6.75,
  nan,
  'Q'],
 145: [0,
  2,
  'Andrew, Mr. Edgardo Samuel',
  'male',
  18.0,
  0,
  0,
  '231945',
  11.5,
  nan,
  'S'],
 146: [0,
  2,
  'Nicholls, Mr. Joseph Charles',
  'male',
  19.0,
  1,
  1,
  'C.A. 33112',
  36.75,
  nan,
  'S'],
 147: [1,
  3,
  'Andersson, Mr. August Edvard ("Wennerstrom")',
  'male',
  27.0,
  0,
  0,
  '350043',
  7.7958,
  nan,
  'S'],
 148: [0,
  3,
  'Ford, Miss. Robina Maggie "Ruby"',
  'female',
  9.0,
  2,
  2,
  'W./C. 6608',
  34.375,
  nan,
  'S'],
 149: [0,
  2,
  'Navratil, Mr. Michel ("Louis M Hoffman")',
  'male',
  36.5,
  0,
  2,
  '230080',
  26.0,
  'F2',
  'S'],
 150: [0,
  2,
  'Byles, Rev. Thomas Roussel Davids',
  'male',
  42.0,
  0,
  0,
  '244310',
  13.0,
  nan,
  'S'],
 151: [0,
  2,
  'Bateman, Rev. Robert James',
  'male',
  51.0,
  0,
  0,
  'S.O.P. 1166',
  12.525,
  nan,
  'S'],
 152: [1,
  1,
  'Pears, Mrs. Thomas (Edith Wearne)',
  'female',
  22.0,
  1,
  0,
  '113776',
  66.6,
  'C2',
  'S'],
 153: [0,
  3,
  'Meo, Mr. Alfonzo',
  'male',
  55.5,
  0,
  0,
  'A.5. 11206',
  8.05,
  nan,
  'S'],
 154: [0,
  3,
  'van Billiard, Mr. Austin Blyler',
  'male',
  40.5,
  0,
  2,
  'A/5. 851',
  14.5,
  nan,
  'S'],
 155: [0,
  3,
  'Olsen, Mr. Ole Martin',
  'male',
  nan,
  0,
  0,
  'Fa 265302',
  7.3125,
  nan,
  'S'],
 156: [0,
  1,
  'Williams, Mr. Charles Duane',
  'male',
  51.0,
  0,
  1,
  'PC 17597',
  61.3792,
  nan,
  'C'],
 157: [1,
  3,
  'Gilnagh, Miss. Katherine "Katie"',
  'female',
  16.0,
  0,
  0,
  '35851',
  7.7333,
  nan,
  'Q'],
 158: [0,
  3,
  'Corn, Mr. Harry',
  'male',
  30.0,
  0,
  0,
  'SOTON/OQ 392090',
  8.05,
  nan,
  'S'],
 159: [0,
  3,
  'Smiljanic, Mr. Mile',
  'male',
  nan,
  0,
  0,
  '315037',
  8.6625,
  nan,
  'S'],
 160: [0,
  3,
  'Sage, Master. Thomas Henry',
  'male',
  nan,
  8,
  2,
  'CA. 2343',
  69.55,
  nan,
  'S'],
 161: [0,
  3,
  'Cribb, Mr. John Hatfield',
  'male',
  44.0,
  0,
  1,
  '371362',
  16.1,
  nan,
  'S'],
 162: [1,
  2,
  'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
  'female',
  40.0,
  0,
  0,
  'C.A. 33595',
  15.75,
  nan,
  'S'],
 163: [0,
  3,
  'Bengtsson, Mr. John Viktor',
  'male',
  26.0,
  0,
  0,
  '347068',
  7.775,
  nan,
  'S'],
 164: [0,
  3,
  'Calic, Mr. Jovo',
  'male',
  17.0,
  0,
  0,
  '315093',
  8.6625,
  nan,
  'S'],
 165: [0,
  3,
  'Panula, Master. Eino Viljami',
  'male',
  1.0,
  4,
  1,
  '3101295',
  39.6875,
  nan,
  'S'],
 166: [1,
  3,
  'Goldsmith, Master. Frank John William "Frankie"',
  'male',
  9.0,
  0,
  2,
  '363291',
  20.525,
  nan,
  'S'],
 167: [1,
  1,
  'Chibnall, Mrs. (Edith Martha Bowerman)',
  'female',
  nan,
  0,
  1,
  '113505',
  55.0,
  'E33',
  'S'],
 168: [0,
  3,
  'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
  'female',
  45.0,
  1,
  4,
  '347088',
  27.9,
  nan,
  'S'],
 169: [0,
  1,
  'Baumann, Mr. John D',
  'male',
  nan,
  0,
  0,
  'PC 17318',
  25.925,
  nan,
  'S'],
 170: [0, 3, 'Ling, Mr. Lee', 'male', 28.0, 0, 0, '1601', 56.4958, nan, 'S'],
 171: [0,
  1,
  'Van der hoef, Mr. Wyckoff',
  'male',
  61.0,
  0,
  0,
  '111240',
  33.5,
  'B19',
  'S'],
 172: [0,
  3,
  'Rice, Master. Arthur',
  'male',
  4.0,
  4,
  1,
  '382652',
  29.125,
  nan,
  'Q'],
 173: [1,
  3,
  'Johnson, Miss. Eleanor Ileen',
  'female',
  1.0,
  1,
  1,
  '347742',
  11.1333,
  nan,
  'S'],
 174: [0,
  3,
  'Sivola, Mr. Antti Wilhelm',
  'male',
  21.0,
  0,
  0,
  'STON/O 2. 3101280',
  7.925,
  nan,
  'S'],
 175: [0,
  1,
  'Smith, Mr. James Clinch',
  'male',
  56.0,
  0,
  0,
  '17764',
  30.6958,
  'A7',
  'C'],
 176: [0,
  3,
  'Klasen, Mr. Klas Albin',
  'male',
  18.0,
  1,
  1,
  '350404',
  7.8542,
  nan,
  'S'],
 177: [0,
  3,
  'Lefebre, Master. Henry Forbes',
  'male',
  nan,
  3,
  1,
  '4133',
  25.4667,
  nan,
  'S'],

### dict - the default: column names are keys, values are dictionaries of index:data pairs

In [6]:
df.to_dict('dict')

{'PassengerId': {0: 1,
  1: 2,
  2: 3,
  3: 4,
  4: 5,
  5: 6,
  6: 7,
  7: 8,
  8: 9,
  9: 10,
  10: 11,
  11: 12,
  12: 13,
  13: 14,
  14: 15,
  15: 16,
  16: 17,
  17: 18,
  18: 19,
  19: 20,
  20: 21,
  21: 22,
  22: 23,
  23: 24,
  24: 25,
  25: 26,
  26: 27,
  27: 28,
  28: 29,
  29: 30,
  30: 31,
  31: 32,
  32: 33,
  33: 34,
  34: 35,
  35: 36,
  36: 37,
  37: 38,
  38: 39,
  39: 40,
  40: 41,
  41: 42,
  42: 43,
  43: 44,
  44: 45,
  45: 46,
  46: 47,
  47: 48,
  48: 49,
  49: 50,
  50: 51,
  51: 52,
  52: 53,
  53: 54,
  54: 55,
  55: 56,
  56: 57,
  57: 58,
  58: 59,
  59: 60,
  60: 61,
  61: 62,
  62: 63,
  63: 64,
  64: 65,
  65: 66,
  66: 67,
  67: 68,
  68: 69,
  69: 70,
  70: 71,
  71: 72,
  72: 73,
  73: 74,
  74: 75,
  75: 76,
  76: 77,
  77: 78,
  78: 79,
  79: 80,
  80: 81,
  81: 82,
  82: 83,
  83: 84,
  84: 85,
  85: 86,
  86: 87,
  87: 88,
  88: 89,
  89: 90,
  90: 91,
  91: 92,
  92: 93,
  93: 94,
  94: 95,
  95: 96,
  96: 97,
  97: 98,
  98: 99,
  99: 100,
  100: 101,
  101: 102,
  102: 103,
  103: 104,
  104: 105,
  105: 106,
  106: 107,
  107: 108,
  108: 109,
  109: 110,
  110: 111,
  111: 112,
  112: 113,
  113: 114,
  114: 115,
  115: 116,
  116: 117,
  117: 118,
  118: 119,
  119: 120,
  120: 121,
  121: 122,
  122: 123,
  123: 124,
  124: 125,
  125: 126,
  126: 127,
  127: 128,
  128: 129,
  129: 130,
  130: 131,
  131: 132,
  132: 133,
  133: 134,
  134: 135,
  135: 136,
  136: 137,
  137: 138,
  138: 139,
  139: 140,
  140: 141,
  141: 142,
  142: 143,
  143: 144,
  144: 145,
  145: 146,
  146: 147,
  147: 148,
  148: 149,
  149: 150,
  150: 151,
  151: 152,
  152: 153,
  153: 154,
  154: 155,
  155: 156,
  156: 157,
  157: 158,
  158: 159,
  159: 160,
  160: 161,
  161: 162,
  162: 163,
  163: 164,
  164: 165,
  165: 166,
  166: 167,
  167: 168,
  168: 169,
  169: 170,
  170: 171,
  171: 172,
  172: 173,
  173: 174,
  174: 175,
  175: 176,
  176: 177,
  177: 178,
  178: 179,
  179: 180,
  180: 181,
  181: 182,
  182: 183,
  183: 184,
  184: 185,
  185: 186,
  186: 187,
  187: 188,
  188: 189,
  189: 190,
  190: 191,
  191: 192,
  192: 193,
  193: 194,
  194: 195,
  195: 196,
  196: 197,
  197: 198,
  198: 199,
  199: 200,
  200: 201,
  201: 202,
  202: 203,
  203: 204,
  204: 205,
  205: 206,
  206: 207,
  207: 208,
  208: 209,
  209: 210,
  210: 211,
  211: 212,
  212: 213,
  213: 214,
  214: 215,
  215: 216,
  216: 217,
  217: 218,
  218: 219,
  219: 220,
  220: 221,
  221: 222,
  222: 223,
  223: 224,
  224: 225,
  225: 226,
  226: 227,
  227: 228,
  228: 229,
  229: 230,
  230: 231,
  231: 232,
  232: 233,
  233: 234,
  234: 235,
  235: 236,
  236: 237,
  237: 238,
  238: 239,
  239: 240,
  240: 241,
  241: 242,
  242: 243,
  243: 244,
  244: 245,
  245: 246,
  246: 247,
  247: 248,
  248: 249,
  249: 250,
  250: 251,
  251: 252,
  252: 253,
  253: 254,
  254: 255,
  255: 256,
  256: 257,
  257: 258,
  258: 259,
  259: 260,
  260: 261,
  261: 262,
  262: 263,
  263: 264,
  264: 265,
  265: 266,
  266: 267,
  267: 268,
  268: 269,
  269: 270,
  270: 271,
  271: 272,
  272: 273,
  273: 274,
  274: 275,
  275: 276,
  276: 277,
  277: 278,
  278: 279,
  279: 280,
  280: 281,
  281: 282,
  282: 283,
  283: 284,
  284: 285,
  285: 286,
  286: 287,
  287: 288,
  288: 289,
  289: 290,
  290: 291,
  291: 292,
  292: 293,
  293: 294,
  294: 295,
  295: 296,
  296: 297,
  297: 298,
  298: 299,
  299: 300,
  300: 301,
  301: 302,
  302: 303,
  303: 304,
  304: 305,
  305: 306,
  306: 307,
  307: 308,
  308: 309,
  309: 310,
  310: 311,
  311: 312,
  312: 313,
  313: 314,
  314: 315,
  315: 316,
  316: 317,
  317: 318,
  318: 319,
  319: 320,
  320: 321,
  321: 322,
  322: 323,
  323: 324,
  324: 325,
  325: 326,
  326: 327,
  327: 328,
  328: 329,
  329: 330,
  330: 331,
  331: 332,
  332: 333,
  333: 334,
  334: 335,
  335: 336,
  336: 337,
  337: 338,
  338: 339,
  339: 340,
  340: 341,
  341: 342,
  342: 343,
  343: 344,
  344: 345,
  345: 346,
  346: 347,
  347: 348,
  348: 349,
  349: 350,
  350: 351,
  351: 352,
  352: 353,
  353: 354,
  354: 355,
  355: 356,
  356: 357,
  357: 358,
  358: 359,
  359: 360,
  360: 361,
  361: 362,
  362: 363,
  363: 364,
  364: 365,
  365: 366,
  366: 367,
  367: 368,
  368: 369,
  369: 370,
  370: 371,
  371: 372,
  372: 373,
  373: 374,
  374: 375,
  375: 376,
  376: 377,
  377: 378,
  378: 379,
  379: 380,
  380: 381,
  381: 382,
  382: 383,
  383: 384,
  384: 385,
  385: 386,
  386: 387,
  387: 388,
  388: 389,
  389: 390,
  390: 391,
  391: 392,
  392: 393,
  393: 394,
  394: 395,
  395: 396,
  396: 397,
  397: 398,
  398: 399,
  399: 400,
  400: 401,
  401: 402,
  402: 403,
  403: 404,
  404: 405,
  405: 406,
  406: 407,
  407: 408,
  408: 409,
  409: 410,
  410: 411,
  411: 412,
  412: 413,
  413: 414,
  414: 415,
  415: 416,
  416: 417,
  417: 418,
  418: 419,
  419: 420,
  420: 421,
  421: 422,
  422: 423,
  423: 424,
  424: 425,
  425: 426,
  426: 427,
  427: 428,
  428: 429,
  429: 430,
  430: 431,
  431: 432,
  432: 433,
  433: 434,
  434: 435,
  435: 436,
  436: 437,
  437: 438,
  438: 439,
  439: 440,
  440: 441,
  441: 442,
  442: 443,
  443: 444,
  444: 445,
  445: 446,
  446: 447,
  447: 448,
  448: 449,
  449: 450,
  450: 451,
  451: 452,
  452: 453,
  453: 454,
  454: 455,
  455: 456,
  456: 457,
  457: 458,
  458: 459,
  459: 460,
  460: 461,
  461: 462,
  462: 463,
  463: 464,
  464: 465,
  465: 466,
  466: 467,
  467: 468,
  468: 469,
  469: 470,
  470: 471,
  471: 472,
  472: 473,
  473: 474,
  474: 475,
  475: 476,
  476: 477,
  477: 478,
  478: 479,
  479: 480,
  480: 481,
  481: 482,
  482: 483,
  483: 484,
  484: 485,
  485: 486,
  486: 487,
  487: 488,
  488: 489,
  489: 490,
  490: 491,
  491: 492,
  492: 493,
  493: 494,
  494: 495,
  495: 496,
  496: 497,
  497: 498,
  498: 499,
  499: 500,
  500: 501,
  501: 502,
  502: 503,
  503: 504,
  504: 505,
  505: 506,
  506: 507,
  507: 508,
  508: 509,
  509: 510,
  510: 511,
  511: 512,
  512: 513,
  513: 514,
  514: 515,
  515: 516,
  516: 517,
  517: 518,
  518: 519,
  519: 520,
  520: 521,
  521: 522,
  522: 523,
  523: 524,
  524: 525,
  525: 526,
  526: 527,
  527: 528,
  528: 529,
  529: 530,
  530: 531,
  531: 532,
  532: 533,
  533: 534,
  534: 535,
  535: 536,
  536: 537,
  537: 538,
  538: 539,
  539: 540,
  540: 541,
  541: 542,
  542: 543,
  543: 544,
  544: 545,
  545: 546,
  546: 547,
  547: 548,
  548: 549,
  549: 550,
  550: 551,
  551: 552,
  552: 553,
  553: 554,
  554: 555,
  555: 556,
  556: 557,
  557: 558,
  558: 559,
  559: 560,
  560: 561,
  561: 562,
  562: 563,
  563: 564,
  564: 565,
  565: 566,
  566: 567,
  567: 568,
  568: 569,
  569: 570,
  570: 571,
  571: 572,
  572: 573,
  573: 574,
  574: 575,
  575: 576,
  576: 577,
  577: 578,
  578: 579,
  579: 580,
  580: 581,
  581: 582,
  582: 583,
  583: 584,
  584: 585,
  585: 586,
  586: 587,
  587: 588,
  588: 589,
  589: 590,
  590: 591,
  591: 592,
  592: 593,
  593: 594,
  594: 595,
  595: 596,
  596: 597,
  597: 598,
  598: 599,
  599: 600,
  600: 601,
  601: 602,
  602: 603,
  603: 604,
  604: 605,
  605: 606,
  606: 607,
  607: 608,
  608: 609,
  609: 610,
  610: 611,
  611: 612,
  612: 613,
  613: 614,
  614: 615,
  615: 616,
  616: 617,
  617: 618,
  618: 619,
  619: 620,
  620: 621,
  621: 622,
  622: 623,
  623: 624,
  624: 625,
  625: 626,
  626: 627,
  627: 628,
  628: 629,
  629: 630,
  630: 631,
  631: 632,
  632: 633,
  633: 634,
  634: 635,
  635: 636,
  636: 637,
  637: 638,
  638: 639,
  639: 640,
  640: 641,
  641: 642,
  642: 643,
  643: 644,
  644: 645,
  645: 646,
  646: 647,
  647: 648,
  648: 649,
  649: 650,
  650: 651,
  651: 652,
  652: 653,
  653: 654,
  654: 655,
  655: 656,
  656: 657,
  657: 658,
  658: 659,
  659: 660,
  660: 661,
  661: 662,
  662: 663,
  663: 664,
  664: 665,
  665: 666,
  666: 667,
  667: 668,
  668: 669,
  669: 670,
  670: 671,
  671: 672,
  672: 673,
  673: 674,
  674: 675,
  675: 676,
  676: 677,
  677: 678,
  678: 679,
  679: 680,
  680: 681,
  681: 682,
  682: 683,
  683: 684,
  684: 685,
  685: 686,
  686: 687,
  687: 688,
  688: 689,
  689: 690,
  690: 691,
  691: 692,
  692: 693,
  693: 694,
  694: 695,
  695: 696,
  696: 697,
  697: 698,
  698: 699,
  699: 700,
  700: 701,
  701: 702,
  702: 703,
  703: 704,
  704: 705,
  705: 706,
  706: 707,
  707: 708,
  708: 709,
  709: 710,
  710: 711,
  711: 712,
  712: 713,
  713: 714,
  714: 715,
  715: 716,
  716: 717,
  717: 718,
  718: 719,
  719: 720,
  720: 721,
  721: 722,
  722: 723,
  723: 724,
  724: 725,
  725: 726,
  726: 727,
  727: 728,
  728: 729,
  729: 730,
  730: 731,
  731: 732,
  732: 733,
  733: 734,
  734: 735,
  735: 736,
  736: 737,
  737: 738,
  738: 739,
  739: 740,
  740: 741,
  741: 742,
  742: 743,
  743: 744,
  744: 745,
  745: 746,
  746: 747,
  747: 748,
  748: 749,
  749: 750,
  750: 751,
  751: 752,
  752: 753,
  753: 754,
  754: 755,
  755: 756,
  756: 757,
  757: 758,
  758: 759,
  759: 760,
  760: 761,
  761: 762,
  762: 763,
  763: 764,
  764: 765,
  765: 766,
  766: 767,
  767: 768,
  768: 769,
  769: 770,
  770: 771,
  771: 772,
  772: 773,
  773: 774,
  774: 775,
  775: 776,
  776: 777,
  777: 778,
  778: 779,
  779: 780,
  780: 781,
  781: 782,
  782: 783,
  783: 784,
  784: 785,
  785: 786,
  786: 787,
  787: 788,
  788: 789,
  789: 790,
  790: 791,
  791: 792,
  792: 793,
  793: 794,
  794: 795,
  795: 796,
  796: 797,
  797: 798,
  798: 799,
  799: 800,
  800: 801,
  801: 802,
  802: 803,
  803: 804,
  804: 805,
  805: 806,
  806: 807,
  807: 808,
  808: 809,
  809: 810,
  810: 811,
  811: 812,
  812: 813,
  813: 814,
  814: 815,
  815: 816,
  816: 817,
  817: 818,
  818: 819,
  819: 820,
  820: 821,
  821: 822,
  822: 823,
  823: 824,
  824: 825,
  825: 826,
  826: 827,
  827: 828,
  828: 829,
  829: 830,
  830: 831,
  831: 832,
  832: 833,
  833: 834,
  834: 835,
  835: 836,
  836: 837,
  837: 838,
  838: 839,
  839: 840,
  840: 841,
  841: 842,
  842: 843,
  843: 844,
  844: 845,
  845: 846,
  846: 847,
  847: 848,
  848: 849,
  849: 850,
  850: 851,
  851: 852,
  852: 853,
  853: 854,
  854: 855,
  855: 856,
  856: 857,
  857: 858,
  858: 859,
  859: 860,
  860: 861,
  861: 862,
  862: 863,
  863: 864,
  864: 865,
  865: 866,
  866: 867,
  867: 868,
  868: 869,
  869: 870,
  870: 871,
  871: 872,
  872: 873,
  873: 874,
  874: 875,
  875: 876,
  876: 877,
  877: 878,
  878: 879,
  879: 880,
  880: 881,
  881: 882,
  882: 883,
  883: 884,
  884: 885,
  885: 886,
  886: 887,
  887: 888,
  888: 889,
  889: 890,
  890: 891},
 'Survived': {0: 0,
  1: 1,
  2: 1,
  3: 1,
  4: 0,
  5: 0,
  6: 0,
  7: 0,
  8: 1,
  9: 1,
  10: 1,
  11: 1,
  12: 0,
  13: 0,
  14: 0,
  15: 1,
  16: 0,
  17: 1,
  18: 0,
  19: 1,
  20: 0,
  21: 1,
  22: 1,
  23: 1,
  24: 0,
  25: 1,
  26: 0,
  27: 0,
  28: 1,
  29: 0,
  30: 0,
  31: 1,
  32: 1,
  33: 0,
  34: 0,
  35: 0,
  36: 1,
  37: 0,
  38: 0,
  39: 1,
  40: 0,
  41: 0,
  42: 0,
  43: 1,
  44: 1,
  45: 0,
  46: 0,
  47: 1,
  48: 0,
  49: 0,
  50: 0,
  51: 0,
  52: 1,
  53: 1,
  54: 0,
  55: 1,
  56: 1,
  57: 0,
  58: 1,
  59: 0,
  60: 0,
  61: 1,
  62: 0,
  63: 0,
  64: 0,
  65: 1,
  66: 1,
  67: 0,
  68: 1,
  69: 0,
  70: 0,
  71: 0,
  72: 0,
  73: 0,
  74: 1,
  75: 0,
  76: 0,
  77: 0,
  78: 1,
  79: 1,
  80: 0,
  81: 1,
  82: 1,
  83: 0,
  84: 1,
  85: 1,
  86: 0,
  87: 0,
  88: 1,
  89: 0,
  90: 0,
  91: 0,
  92: 0,
  93: 0,
  94: 0,
  95: 0,
  96: 0,
  97: 1,
  98: 1,
  99: 0,
  100: 0,
  101: 0,
  102: 0,
  103: 0,
  104: 0,
  105: 0,
  106: 1,
  107: 1,
  108: 0,
  109: 1,
  110: 0,
  111: 0,
  112: 0,
  113: 0,
  114: 0,
  115: 0,
  116: 0,
  117: 0,
  118: 0,
  119: 0,
  120: 0,
  121: 0,
  122: 0,
  123: 1,
  124: 0,
  125: 1,
  126: 0,
  127: 1,
  128: 1,
  129: 0,
  130: 0,
  131: 0,
  132: 0,
  133: 1,
  134: 0,
  135: 0,
  136: 1,
  137: 0,
  138: 0,
  139: 0,
  140: 0,
  141: 1,
  142: 1,
  143: 0,
  144: 0,
  145: 0,
  146: 1,
  147: 0,
  148: 0,
  149: 0,
  150: 0,
  151: 1,
  152: 0,
  153: 0,
  154: 0,
  155: 0,
  156: 1,
  157: 0,
  158: 0,
  159: 0,
  160: 0,
  161: 1,
  162: 0,
  163: 0,
  164: 0,
  165: 1,
  166: 1,
  167: 0,
  168: 0,
  169: 0,
  170: 0,
  171: 0,
  172: 1,
  173: 0,
  174: 0,
  175: 0,
  176: 0,
  177: 0,
  178: 0,
  179: 0,
  180: 0,
  181: 0,
  182: 0,
  183: 1,
  184: 1,
  185: 0,
  186: 1,
  187: 1,
  188: 0,
  189: 0,
  190: 1,
  191: 0,
  192: 1,
  193: 1,
  194: 1,
  195: 1,
  196: 0,
  197: 0,
  198: 1,
  199: 0,
  200: 0,
  201: 0,
  202: 0,
  203: 0,
  204: 1,
  205: 0,
  206: 0,
  207: 1,
  208: 1,
  209: 1,
  210: 0,
  211: 1,
  212: 0,
  213: 0,
  214: 0,
  215: 1,
  216: 1,
  217: 0,
  218: 1,
  219: 0,
  220: 1,
  221: 0,
  222: 0,
  223: 0,
  224: 1,
  225: 0,
  226: 1,
  227: 0,
  228: 0,
  229: 0,
  230: 1,
  231: 0,
  232: 0,
  233: 1,
  234: 0,
  235: 0,
  236: 0,
  237: 1,
  238: 0,
  239: 0,
  240: 0,
  241: 1,
  242: 0,
  243: 0,
  244: 0,
  245: 0,
  246: 0,
  247: 1,
  248: 1,
  249: 0,
  250: 0,
  251: 0,
  252: 0,
  253: 0,
  254: 0,
  255: 1,
  256: 1,
  257: 1,
  258: 1,
  259: 1,
  260: 0,
  261: 1,
  262: 0,
  263: 0,
  264: 0,
  265: 0,
  266: 0,
  267: 1,
  268: 1,
  269: 1,
  270: 0,
  271: 1,
  272: 1,
  273: 0,
  274: 1,
  275: 1,
  276: 0,
  277: 0,
  278: 0,
  279: 1,
  280: 0,
  281: 0,
  282: 0,
  283: 1,
  284: 0,
  285: 0,
  286: 1,
  287: 0,
  288: 1,
  289: 1,
  290: 1,
  291: 1,
  292: 0,
  293: 0,
  294: 0,
  295: 0,
  296: 0,
  297: 0,
  298: 1,
  299: 1,
  300: 1,
  301: 1,
  302: 0,
  303: 1,
  304: 0,
  305: 1,
  306: 1,
  307: 1,
  308: 0,
  309: 1,
  310: 1,
  311: 1,
  312: 0,
  313: 0,
  314: 0,
  315: 1,
  316: 1,
  317: 0,
  318: 1,
  319: 1,
  320: 0,
  321: 0,
  322: 1,
  323: 1,
  324: 0,
  325: 1,
  326: 0,
  327: 1,
  328: 1,
  329: 1,
  330: 1,
  331: 0,
  332: 0,
  333: 0,
  334: 1,
  335: 0,
  336: 0,
  337: 1,
  338: 1,
  339: 0,
  340: 1,
  341: 1,
  342: 0,
  343: 0,
  344: 0,
  345: 1,
  346: 1,
  347: 1,
  348: 1,
  349: 0,
  350: 0,
  351: 0,
  352: 0,
  353: 0,
  354: 0,
  355: 0,
  356: 1,
  357: 0,
  358: 1,
  359: 1,
  360: 0,
  361: 0,
  362: 0,
  363: 0,
  364: 0,
  365: 0,
  366: 1,
  367: 1,
  368: 1,
  369: 1,
  370: 1,
  371: 0,
  372: 0,
  373: 0,
  374: 0,
  375: 1,
  376: 1,
  377: 0,
  378: 0,
  379: 0,
  380: 1,
  381: 1,
  382: 0,
  383: 1,
  384: 0,
  385: 0,
  386: 0,
  387: 1,
  388: 0,
  389: 1,
  390: 1,
  391: 1,
  392: 0,
  393: 1,
  394: 1,
  395: 0,
  396: 0,
  397: 0,
  398: 0,
  399: 1,
  400: 1,
  401: 0,
  402: 0,
  403: 0,
  404: 0,
  405: 0,
  406: 0,
  407: 1,
  408: 0,
  409: 0,
  410: 0,
  411: 0,
  412: 1,
  413: 0,
  414: 1,
  415: 0,
  416: 1,
  417: 1,
  418: 0,
  419: 0,
  420: 0,
  421: 0,
  422: 0,
  423: 0,
  424: 0,
  425: 0,
  426: 1,
  427: 1,
  428: 0,
  429: 1,
  430: 1,
  431: 1,
  432: 1,
  433: 0,
  434: 0,
  435: 1,
  436: 0,
  437: 1,
  438: 0,
  439: 0,
  440: 1,
  441: 0,
  442: 0,
  443: 1,
  444: 1,
  445: 1,
  446: 1,
  447: 1,
  448: 1,
  449: 1,
  450: 0,
  451: 0,
  452: 0,
  453: 1,
  454: 0,
  455: 1,
  456: 0,
  457: 1,
  458: 1,
  459: 0,
  460: 1,
  461: 0,
  462: 0,
  463: 0,
  464: 0,
  465: 0,
  466: 0,
  467: 0,
  468: 0,
  469: 1,
  470: 0,
  471: 0,
  472: 1,
  473: 1,
  474: 0,
  475: 0,
  476: 0,
  477: 0,
  478: 0,
  479: 1,
  480: 0,
  481: 0,
  482: 0,
  483: 1,
  484: 1,
  485: 0,
  486: 1,
  487: 0,
  488: 0,
  489: 1,
  490: 0,
  491: 0,
  492: 0,
  493: 0,
  494: 0,
  495: 0,
  496: 1,
  497: 0,
  498: 0,
  499: 0,
  500: 0,
  501: 0,
  502: 0,
  503: 0,
  504: 1,
  505: 0,
  506: 1,
  507: 1,
  508: 0,
  509: 1,
  510: 1,
  511: 0,
  512: 1,
  513: 1,
  514: 0,
  515: 0,
  516: 1,
  517: 0,
  518: 1,
  519: 0,
  520: 1,
  521: 0,
  522: 0,
  523: 1,
  524: 0,
  525: 0,
  526: 1,
  527: 0,
  528: 0,
  529: 0,
  530: 1,
  531: 0,
  532: 0,
  533: 1,
  534: 0,
  535: 1,
  536: 0,
  537: 1,
  538: 0,
  539: 1,
  540: 1,
  541: 0,
  542: 0,
  543: 1,
  544: 0,
  545: 0,
  546: 1,
  547: 1,
  548: 0,
  549: 1,
  550: 1,
  551: 0,
  552: 0,
  553: 1,
  554: 1,
  555: 0,
  556: 1,
  557: 0,
  558: 1,
  559: 1,
  560: 0,
  561: 0,
  562: 0,
  563: 0,
  564: 0,
  565: 0,
  566: 0,
  567: 0,
  568: 0,
  569: 1,
  570: 1,
  571: 1,
  572: 1,
  573: 1,
  574: 0,
  575: 0,
  576: 1,
  577: 1,
  578: 0,
  579: 1,
  580: 1,
  581: 1,
  582: 0,
  583: 0,
  584: 0,
  585: 1,
  586: 0,
  587: 1,
  588: 0,
  589: 0,
  590: 0,
  591: 1,
  592: 0,
  593: 0,
  594: 0,
  595: 0,
  596: 1,
  597: 0,
  598: 0,
  599: 1,
  600: 1,
  601: 0,
  602: 0,
  603: 0,
  604: 1,
  605: 0,
  606: 0,
  607: 1,
  608: 1,
  609: 1,
  610: 0,
  611: 0,
  612: 1,
  613: 0,
  614: 0,
  615: 1,
  616: 0,
  617: 0,
  618: 1,
  619: 0,
  620: 0,
  621: 1,
  622: 1,
  623: 0,
  624: 0,
  625: 0,
  626: 0,
  627: 1,
  628: 0,
  629: 0,
  630: 1,
  631: 0,
  632: 1,
  633: 0,
  634: 0,
  635: 1,
  636: 0,
  637: 0,
  638: 0,
  639: 0,
  640: 0,
  641: 1,
  642: 0,
  643: 1,
  644: 1,
  645: 1,
  646: 0,
  647: 1,
  648: 0,
  649: 1,
  650: 0,
  651: 1,
  652: 0,
  653: 1,
  654: 0,
  655: 0,
  656: 0,
  657: 0,
  658: 0,
  659: 0,
  660: 1,
  661: 0,
  662: 0,
  663: 0,
  664: 1,
  665: 0,
  666: 0,
  667: 0,
  668: 0,
  669: 1,
  670: 1,
  671: 0,
  672: 0,
  673: 1,
  674: 0,
  675: 0,
  676: 0,
  677: 1,
  678: 0,
  679: 1,
  680: 0,
  681: 1,
  682: 0,
  683: 0,
  684: 0,
  685: 0,
  686: 0,
  687: 0,
  688: 0,
  689: 1,
  690: 1,
  691: 1,
  692: 1,
  693: 0,
  694: 0,
  695: 0,
  696: 0,
  697: 1,
  698: 0,
  699: 0,
  700: 1,
  701: 1,
  702: 0,
  703: 0,
  704: 0,
  705: 0,
  706: 1,
  707: 1,
  708: 1,
  709: 1,
  710: 1,
  711: 0,
  712: 1,
  713: 0,
  714: 0,
  715: 0,
  716: 1,
  717: 1,
  718: 0,
  719: 0,
  720: 1,
  721: 0,
  722: 0,
  723: 0,
  724: 1,
  725: 0,
  726: 1,
  727: 1,
  728: 0,
  729: 0,
  730: 1,
  731: 0,
  732: 0,
  733: 0,
  734: 0,
  735: 0,
  736: 0,
  737: 1,
  738: 0,
  739: 0,
  740: 1,
  741: 0,
  742: 1,
  743: 0,
  744: 1,
  745: 0,
  746: 0,
  747: 1,
  748: 0,
  749: 0,
  750: 1,
  751: 1,
  752: 0,
  753: 0,
  754: 1,
  755: 1,
  756: 0,
  757: 0,
  758: 0,
  759: 1,
  760: 0,
  761: 0,
  762: 1,
  763: 1,
  764: 0,
  765: 1,
  766: 0,
  767: 0,
  768: 0,
  769: 0,
  770: 0,
  771: 0,
  772: 0,
  773: 0,
  774: 1,
  775: 0,
  776: 0,
  777: 1,
  778: 0,
  779: 1,
  780: 1,
  781: 1,
  782: 0,
  783: 0,
  784: 0,
  785: 0,
  786: 1,
  787: 0,
  788: 1,
  789: 0,
  790: 0,
  791: 0,
  792: 0,
  793: 0,
  794: 0,
  795: 0,
  796: 1,
  797: 1,
  798: 0,
  799: 0,
  800: 0,
  801: 1,
  802: 1,
  803: 1,
  804: 1,
  805: 0,
  806: 0,
  807: 0,
  808: 0,
  809: 1,
  810: 0,
  811: 0,
  812: 0,
  813: 0,
  814: 0,
  815: 0,
  816: 0,
  817: 0,
  818: 0,
  819: 0,
  820: 1,
  821: 1,
  822: 0,
  823: 1,
  824: 0,
  825: 0,
  826: 0,
  827: 1,
  828: 1,
  829: 1,
  830: 1,
  831: 1,
  832: 0,
  833: 0,
  834: 0,
  835: 1,
  836: 0,
  837: 0,
  838: 1,
  839: 1,
  840: 0,
  841: 0,
  842: 1,
  843: 0,
  844: 0,
  845: 0,
  846: 0,
  847: 0,
  848: 0,
  849: 1,
  850: 0,
  851: 0,
  852: 0,
  853: 1,
  854: 0,
  855: 1,
  856: 1,
  857: 1,
  858: 1,
  859: 0,
  860: 0,
  861: 0,
  862: 1,
  863: 0,
  864: 0,
  865: 1,
  866: 1,
  867: 0,
  868: 0,
  869: 1,
  870: 0,
  871: 1,
  872: 0,
  873: 0,
  874: 1,
  875: 1,
  876: 0,
  877: 0,
  878: 0,
  879: 1,
  880: 1,
  881: 0,
  882: 0,
  883: 0,
  884: 0,
  885: 0,
  886: 0,
  887: 1,
  888: 0,
  889: 1,
  890: 0},
 'Pclass': {0: 3,
  1: 1,
  2: 3,
  3: 1,
  4: 3,
  5: 3,
  6: 1,
  7: 3,
  8: 3,
  9: 2,
  10: 3,
  11: 1,
  12: 3,
  13: 3,
  14: 3,
  15: 2,
  16: 3,
  17: 2,
  18: 3,
  19: 3,
  20: 2,
  21: 2,
  22: 3,
  23: 1,
  24: 3,
  25: 3,
  26: 3,
  27: 1,
  28: 3,
  29: 3,
  30: 1,
  31: 1,
  32: 3,
  33: 2,
  34: 1,
  35: 1,
  36: 3,
  37: 3,
  38: 3,
  39: 3,
  40: 3,
  41: 2,
  42: 3,
  43: 2,
  44: 3,
  45: 3,
  46: 3,
  47: 3,
  48: 3,
  49: 3,
  50: 3,
  51: 3,
  52: 1,
  53: 2,
  54: 1,
  55: 1,
  56: 2,
  57: 3,
  58: 2,
  59: 3,
  60: 3,
  61: 1,
  62: 1,
  63: 3,
  64: 1,
  65: 3,
  66: 2,
  67: 3,
  68: 3,
  69: 3,
  70: 2,
  71: 3,
  72: 2,
  73: 3,
  74: 3,
  75: 3,
  76: 3,

### list - keys are column names, values are lists of column data

In [7]:
df.to_dict('list')

{'PassengerId': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  204,
  205,
  206,
  207,
  208,
  209,
  210,
  211,
  212,
  213,
  214,
  215,
  216,
  217,
  218,
  219,
  220,
  221,
  222,
  223,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  233,
  234,
  235,
  236,
  237,
  238,
  239,
  240,
  241,
  242,
  243,
  244,
  245,
  246,
  247,
  248,
  249,
  250,
  251,
  252,
  253,
  254,
  255,
  256,
  257,
  258,
  259,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  292,
  293,
  294,
  295,
  296,
  297,
  298,
  299,
  300,
  301,
  302,
  303,
  304,
  305,
  306,
  307,
  308,
  309,
  310,
  311,
  312,
  313,
  314,
  315,
  316,
  317,
  318,
  319,
  320,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  332,
  333,
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  350,
  351,
  352,
  353,
  354,
  355,
  356,
  357,
  358,
  359,
  360,
  361,
  362,
  363,
  364,
  365,
  366,
  367,
  368,
  369,
  370,
  371,
  372,
  373,
  374,
  375,
  376,
  377,
  378,
  379,
  380,
  381,
  382,
  383,
  384,
  385,
  386,
  387,
  388,
  389,
  390,
  391,
  392,
  393,
  394,
  395,
  396,
  397,
  398,
  399,
  400,
  401,
  402,
  403,
  404,
  405,
  406,
  407,
  408,
  409,
  410,
  411,
  412,
  413,
  414,
  415,
  416,
  417,
  418,
  419,
  420,
  421,
  422,
  423,
  424,
  425,
  426,
  427,
  428,
  429,
  430,
  431,
  432,
  433,
  434,
  435,
  436,
  437,
  438,
  439,
  440,
  441,
  442,
  443,
  444,
  445,
  446,
  447,
  448,
  449,
  450,
  451,
  452,
  453,
  454,
  455,
  456,
  457,
  458,
  459,
  460,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  468,
  469,
  470,
  471,
  472,
  473,
  474,
  475,
  476,
  477,
  478,
  479,
  480,
  481,
  482,
  483,
  484,
  485,
  486,
  487,
  488,
  489,
  490,
  491,
  492,
  493,
  494,
  495,
  496,
  497,
  498,
  499,
  500,
  501,
  502,
  503,
  504,
  505,
  506,
  507,
  508,
  509,
  510,
  511,
  512,
  513,
  514,
  515,
  516,
  517,
  518,
  519,
  520,
  521,
  522,
  523,
  524,
  525,
  526,
  527,
  528,
  529,
  530,
  531,
  532,
  533,
  534,
  535,
  536,
  537,
  538,
  539,
  540,
  541,
  542,
  543,
  544,
  545,
  546,
  547,
  548,
  549,
  550,
  551,
  552,
  553,
  554,
  555,
  556,
  557,
  558,
  559,
  560,
  561,
  562,
  563,
  564,
  565,
  566,
  567,
  568,
  569,
  570,
  571,
  572,
  573,
  574,
  575,
  576,
  577,
  578,
  579,
  580,
  581,
  582,
  583,
  584,
  585,
  586,
  587,
  588,
  589,
  590,
  591,
  592,
  593,
  594,
  595,
  596,
  597,
  598,
  599,
  600,
  601,
  602,
  603,
  604,
  605,
  606,
  607,
  608,
  609,
  610,
  611,
  612,
  613,
  614,
  615,
  616,
  617,
  618,
  619,
  620,
  621,
  622,
  623,
  624,
  625,
  626,
  627,
  628,
  629,
  630,
  631,
  632,
  633,
  634,
  635,
  636,
  637,
  638,
  639,
  640,
  641,
  642,
  643,
  644,
  645,
  646,
  647,
  648,
  649,
  650,
  651,
  652,
  653,
  654,
  655,
  656,
  657,
  658,
  659,
  660,
  661,
  662,
  663,
  664,
  665,
  666,
  667,
  668,
  669,
  670,
  671,
  672,
  673,
  674,
  675,
  676,
  677,
  678,
  679,
  680,
  681,
  682,
  683,
  684,
  685,
  686,
  687,
  688,
  689,
  690,
  691,
  692,
  693,
  694,
  695,
  696,
  697,
  698,
  699,
  700,
  701,
  702,
  703,
  704,
  705,
  706,
  707,
  708,
  709,
  710,
  711,
  712,
  713,
  714,
  715,
  716,
  717,
  718,
  719,
  720,
  721,
  722,
  723,
  724,
  725,
  726,
  727,
  728,
  729,
  730,
  731,
  732,
  733,
  734,
  735,
  736,
  737,
  738,
  739,
  740,
  741,
  742,
  743,
  744,
  745,
  746,
  747,
  748,
  749,
  750,
  751,
  752,
  753,
  754,
  755,
  756,
  757,
  758,
  759,
  760,
  761,
  762,
  763,
  764,
  765,
  766,
  767,
  768,
  769,
  770,
  771,
  772,
  773,
  774,
  775,
  776,
  777,
  778,
  779,
  780,
  781,
  782,
  783,
  784,
  785,
  786,
  787,
  788,
  789,
  790,
  791,
  792,
  793,
  794,
  795,
  796,
  797,
  798,
  799,
  800,
  801,
  802,
  803,
  804,
  805,
  806,
  807,
  808,
  809,
  810,
  811,
  812,
  813,
  814,
  815,
  816,
  817,
  818,
  819,
  820,
  821,
  822,
  823,
  824,
  825,
  826,
  827,
  828,
  829,
  830,
  831,
  832,
  833,
  834,
  835,
  836,
  837,
  838,
  839,
  840,
  841,
  842,
  843,
  844,
  845,
  846,
  847,
  848,
  849,
  850,
  851,
  852,
  853,
  854,
  855,
  856,
  857,
  858,
  859,
  860,
  861,
  862,
  863,
  864,
  865,
  866,
  867,
  868,
  869,
  870,
  871,
  872,
  873,
  874,
  875,
  876,
  877,
  878,
  879,
  880,
  881,
  882,
  883,
  884,
  885,
  886,
  887,
  888,
  889,
  890,
  891],
 'Survived': [0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0],
 'Pclass': [3,
  1,
  3,
  1,
  3,
  3,
  1,
  3,
  3,
  2,
  3,
  1,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  2,
  2,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  1,
  1,
  3,
  2,
  1,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  2,
  1,
  1,
  2,
  3,
  2,
  3,
  3,
  1,
  1,
  3,
  1,
  3,
  2,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  1,
  2,
  2,
  3,
  3,
  1,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  3,
  3,
  3,
  2,
  1,
  3,
  2,
  3,
  2,
  2,
  1,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  2,
  2,
  2,
  1,
  1,
  3,
  1,
  3,
  3,
  3,
  3,
  2,
  2,
  3,
  3,
  2,
  2,
  2,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  1,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  1,
  2,
  3,
  3,
  2,
  3,
  2,
  3,
  1,
  3,
  1,
  3,
  3,
  2,
  2,
  3,
  2,
  1,
  1,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  3,
  2,
  3,
  2,
  3,
  1,
  3,
  2,
  1,
  2,
  3,
  2,
  3,
  3,
  1,
  3,
  2,
  3,
  2,
  3,
  1,
  3,
  2,
  3,
  2,
  3,
  2,
  2,
  2,
  2,
  3,
  3,
  2,
  3,
  3,
  1,
  3,
  2,
  1,
  2,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  1,
  1,
  2,
  3,
  3,
  1,
  1,
  3,
  2,
  3,
  3,
  1,
  1,
  1,
  3,
  2,
  1,
  3,
  1,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  2,
  3,
  1,
  1,
  2,
  3,
  3,
  1,
  3,
  1,
  1,
  1,
  3,
  3,
  3,
  2,
  3,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  2,
  3,
  2,
  3,
  2,
  2,
  1,
  1,
  3,
  3,
  2,
  2,
  3,
  1,
  3,
  2,
  3,
  1,
  3,
  1,
  1,
  3,
  1,
  3,
  1,
  1,
  3,
  1,
  2,
  1,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  3,
  1,
  1,
  3,
  3,
  1,
  3,
  1,
  3,
  1,
  3,
  3,
  1,
  3,
  3,
  1,
  3,
  2,
  3,
  2,
  3,
  2,
  1,
  3,
  3,
  1,
  3,
  3,
  3,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  2,
  2,
  3,
  3,
  1,
  3,
  2,
  3,
  1,
  1,
  3,
  2,
  1,
  2,
  2,
  3,
  3,
  2,
  3,
  1,
  2,
  1,
  3,
  1,
  2,
  3,
  1,
  1,
  3,
  3,
  1,
  1,
  2,
  3,
  1,
  3,
  1,
  2,
  3,
  3,
  2,
  1,
  3,
  3,
  3,
  3,
  2,
  2,
  3,
  1,
  2,
  3,
  3,
  3,
  3,
  2,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  3,
  3,
  3,
  1,
  1,
  3,
  3,
  1,
  3,
  1,
  3,
  3,
  3,
  3,
  3,
  1,
  1,
  2,
  1,
  3,
  3,
  3,
  3,
  1,
  1,
  3,
  1,
  2,
  3,
  2,
  3,
  1,
  3,
  3,
  1,
  3,
  3,
  2,
  1,
  3,
  2,
  2,
  3,
  3,
  3,
  3,
  2,
  1,
  1,
  3,
  1,
  1,
  3,
  3,
  2,
  1,
  1,
  2,
  2,
  3,
  2,
  1,
  2,
  3,
  3,
  3,
  1,
  1,
  1,
  1,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  2,
  1,
  1,
  3,
  3,
  3,
  2,
  1,
  3,
  3,
  2,
  1,
  2,
  1,
  3,
  1,
  2,
  1,
  3,
  3,
  3,
  1,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  1,
  2,
  3,
  1,
  3,
  1,
  3,
  3,
  1,
  2,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  3,
  2,
  2,
  3,
  1,
  3,
  3,
  3,
  1,
  2,
  1,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  1,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  2,
  3,
  3,
  2,
  1,
  1,
  3,
  1,
  3,
  3,
  2,
  2,
  3,
  3,
  1,
  2,
  1,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  1,
  3,
  3,
  2,
  2,
  3,
  3,
  3,
  1,
  1,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  3,
  3,
  2,
  2,
  1,
  1,
  3,
  1,
  1,
  1,
  3,
  2,
  3,
  1,
  2,
  3,
  3,
  2,
  3,
  2,
  2,
  1,
  3,
  2,
  3,
  2,
  3,
  1,
  3,
  2,
  2,
  2,
  3,
  3,
  1,
  3,
  3,
  1,
  1,
  1,
  3,
  3,
  1,
  3,
  2,
  1,
  3,
  2,
  3,
  3,
  3,
  2,
  2,
  3,
  2,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  3,
  1,
  1,
  3,
  3,
  3,
  3,
  3,
  3,
  1,
  3,
  2,
  3,
  1,
  3,
  2,
  1,
  3,
  3,
  3,
  2,
  2,
  1,
  3,
  3,
  3,
  1,
  3,
  2,
  1,
  3,
  3,
  2,
  3,
  3,
  1,
  3,
  2,
  3,
  3,
  1,
  3,
  1,
  3,
  3,
  3,
  3,
  2,
  3,
  1,
  3,
  2,
  3,
  3,
  3,
  1,
  3,
  3,
  3,
  1,
  3,
  2,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  1,
  3,
  3,
  3,
  1,
  2,
  3,
  1,
  1,
  3,
  3,
  3,
  2,
  1,
  3,
  2,
  2,
  2,
  1,
  3,
  3,
  3,
  1,
  1,
  3,
  2,
  3,
  3,
  3,
  3,
  1,
  2,
  3,
  3,
  2,
  3,
  3,
  2,
  1,
  3,
  1,
  3],
 'Name': ['Braund, Mr. Owen Harris',
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'Heikkinen, Miss. Laina',
  'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'Allen, Mr. William Henry',
  'Moran, Mr. James',
  'McCarthy, Mr. Timothy J',
  'Palsson, Master. Gosta Leonard',
  'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'Nasser, Mrs. Nicholas (Adele Achem)',
  'Sandstrom, Miss. Marguerite Rut',
  'Bonnell, Miss. Elizabeth',
  'Saundercock, Mr. William Henry',
  'Andersson, Mr. Anders Johan',
  'Vestrom, Miss. Hulda Amanda Adolfina',
  'Hewlett, Mrs. (Mary D Kingcome) ',
  'Rice, Master. Eugene',
  'Williams, Mr. Charles Eugene',
  'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'Masselmani, Mrs. Fatima',
  'Fynney, Mr. Joseph J',
  'Beesley, Mr. Lawrence',
  'McGowan, Miss. Anna "Annie"',
  'Sloper, Mr. William Thompson',
  'Palsson, Miss. Torborg Danira',
  'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'Emir, Mr. Farred Chehab',
  'Fortune, Mr. Charles Alexander',
  'O\'Dwyer, Miss. Ellen "Nellie"',
  'Todoroff, Mr. Lalio',
  'Uruchurtu, Don. Manuel E',
  'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'Glynn, Miss. Mary Agatha',
  'Wheadon, Mr. Edward H',
  'Meyer, Mr. Edgar Joseph',
  'Holverson, Mr. Alexander Oskar',
  'Mamee, Mr. Hanna',
  'Cann, Mr. Ernest Charles',
  'Vander Planke, Miss. Augusta Maria',
  'Nicola-Yarred, Miss. Jamila',
  'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'Kraeff, Mr. Theodor',
  'Laroche, Miss. Simonne Marie Anne Andree',
  'Devaney, Miss. Margaret Delia',
  'Rogers, Mr. William John',
  'Lennon, Mr. Denis',
  "O'Driscoll, Miss. Bridget",
  'Samaan, Mr. Youssef',
  'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'Panula, Master. Juha Niilo',
  'Nosworthy, Mr. Richard Cater',
  'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'Ostby, Mr. Engelhart Cornelius',
  'Woolner, Mr. Hugh',
  'Rugg, Miss. Emily',
  'Novel, Mr. Mansouer',
  'West, Miss. Constance Mirium',
  'Goodwin, Master. William Frederick',
  'Sirayanian, Mr. Orsen',
  'Icard, Miss. Amelie',
  'Harris, Mr. Henry Birkhardt',
  'Skoog, Master. Harald',
  'Stewart, Mr. Albert A',
  'Moubarek, Master. Gerios',
  'Nye, Mrs. (Elizabeth Ramell)',
  'Crease, Mr. Ernest James',
  'Andersson, Miss. Erna Alexandra',
  'Kink, Mr. Vincenz',
  'Jenkin, Mr. Stephen Curnow',
  'Goodwin, Miss. Lillian Amy',
  'Hood, Mr. Ambrose Jr',
  'Chronopoulos, Mr. Apostolos',
  'Bing, Mr. Lee',
  'Moen, Mr. Sigurd Hansen',
  'Staneff, Mr. Ivan',
  'Moutal, Mr. Rahamin Haim',
  'Caldwell, Master. Alden Gates',
  'Dowdell, Miss. Elizabeth',
  'Waelens, Mr. Achille',
  'Sheerlinck, Mr. Jan Baptist',
  'McDermott, Miss. Brigdet Delia',
  'Carrau, Mr. Francisco M',
  'Ilett, Miss. Bertha',
  'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
  'Ford, Mr. William Neal',
  'Slocovski, Mr. Selman Francis',
  'Fortune, Miss. Mabel Helen',
  'Celotti, Mr. Francesco',
  'Christmann, Mr. Emil',
  'Andreasson, Mr. Paul Edvin',
  'Chaffee, Mr. Herbert Fuller',
  'Dean, Mr. Bertram Frank',
  'Coxon, Mr. Daniel',
  'Shorney, Mr. Charles Joseph',
  'Goldschmidt, Mr. George B',
  'Greenfield, Mr. William Bertram',
  'Doling, Mrs. John T (Ada Julia Bone)',
  'Kantor, Mr. Sinai',
  'Petranec, Miss. Matilda',
  'Petroff, Mr. Pastcho ("Pentcho")',
  'White, Mr. Richard Frasar',
  'Johansson, Mr. Gustaf Joel',
  'Gustafsson, Mr. Anders Vilhelm',
  'Mionoff, Mr. Stoytcho',
  'Salkjelsvik, Miss. Anna Kristine',
  'Moss, Mr. Albert Johan',
  'Rekic, Mr. Tido',
  'Moran, Miss. Bertha',
  'Porter, Mr. Walter Chamberlain',
  'Zabour, Miss. Hileni',
  'Barton, Mr. David John',
  'Jussila, Miss. Katriina',
  'Attalah, Miss. Malake',
  'Pekoniemi, Mr. Edvard',
  'Connors, Mr. Patrick',
  'Turpin, Mr. William John Robert',
  'Baxter, Mr. Quigg Edmond',
  'Andersson, Miss. Ellis Anna Maria',
  'Hickman, Mr. Stanley George',
  'Moore, Mr. Leonard Charles',
  'Nasser, Mr. Nicholas',
  'Webber, Miss. Susan',
  'White, Mr. Percival Wayland',
  'Nicola-Yarred, Master. Elias',
  'McMahon, Mr. Martin',
  'Madsen, Mr. Fridtjof Arne',
  'Peter, Miss. Anna',
  'Ekstrom, Mr. Johan',
  'Drazenoic, Mr. Jozef',
  'Coelho, Mr. Domingos Fernandeo',
  'Robins, Mrs. Alexander A (Grace Charity Laury)',
  'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
  'Sobey, Mr. Samuel James Hayden',
  'Richard, Mr. Emile',
  'Newsom, Miss. Helen Monypeny',
  'Futrelle, Mr. Jacques Heath',
  'Osen, Mr. Olaf Elon',
  'Giglio, Mr. Victor',
  'Boulos, Mrs. Joseph (Sultana)',
  'Nysten, Miss. Anna Sofia',
  'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
  'Burke, Mr. Jeremiah',
  'Andrew, Mr. Edgardo Samuel',
  'Nicholls, Mr. Joseph Charles',
  'Andersson, Mr. August Edvard ("Wennerstrom")',
  'Ford, Miss. Robina Maggie "Ruby"',

### series - like 'list', but values are Series

In [8]:
df.to_dict('series')

{'PassengerId': 0        1
 1        2
 2        3
 3        4
 4        5
       ...
 886    887
 887    888
 888    889
 889    890
 890    891
 Name: PassengerId, Length: 891, dtype: int64,
 'Survived': 0      0
 1      1
 2      1
 3      1
 4      0
       ..
 886    0
 887    1
 888    0
 889    1
 890    0
 Name: Survived, Length: 891, dtype: int64,
 'Pclass': 0      3
 1      1
 2      3
 3      1
 4      3
       ..
 886    2
 887    1
 888    3
 889    1
 890    3
 Name: Pclass, Length: 891, dtype: int64,
 'Name': 0                                Braund, Mr. Owen Harris
 1      Cumings, Mrs. John Bradley (Florence Briggs Th...
 2                                 Heikkinen, Miss. Laina
 3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
 4                               Allen, Mr. William Henry
                              ...
 886                                Montvila, Rev. Juozas
 887                         Graham, Miss. Margaret Edith
 888             Johnston, Miss. Catherine Helen "Carrie"
 889                                Behr, Mr. Karl Howell
 890                                  Dooley, Mr. Patrick
 Name: Name, Length: 891, dtype: object,
 'Sex': 0        male
 1      female
 2      female
 3      female
 4        male
         ...
 886      male
 887    female
 888    female
 889      male
 890      male
 Name: Sex, Length: 891, dtype: object,
 'Age': 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64,
 'SibSp': 0      1
 1      1
 2      0
 3      1
 4      0
       ..
 886    0
 887    0
 888    1
 889    0
 890    0
 Name: SibSp, Length: 891, dtype: int64,
 'Parch': 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 886    0
 887    0
 888    2
 889    0
 890    0
 Name: Parch, Length: 891, dtype: int64,
 'Ticket': 0             A/5 21171
 1              PC 17599
 2      STON/O2. 3101282
 3                113803
 4                373450
              ...
 886              211536
 887              112053
 888          W./C. 6607
 889              111369
 890              370376
 Name: Ticket, Length: 891, dtype: object,
 'Fare': 0       7.2500
 1      71.2833
 2       7.9250
 3      53.1000
 4       8.0500
         ...
 886    13.0000
 887    30.0000
 888    23.4500
 889    30.0000
 890     7.7500
 Name: Fare, Length: 891, dtype: float64,
 'Cabin': 0       NaN
 1       C85
 2       NaN
 3      C123
 4       NaN
        ...
 886     NaN
 887     B42
 888     NaN
 889    C148
 890     NaN
 Name: Cabin, Length: 891, dtype: object,
 'Embarked': 0      S
 1      C
 2      S
 3      S
 4      S
       ..
 886    S
 887    S
 888    S
 889    C
 890    Q
 Name: Embarked, Length: 891, dtype: object}

### split - splits columns/data/index as keys with values being column names, data values by row and index labels respectively

In [9]:
df.to_dict('split')

{'index': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  162,
  163,
  164,
  165,
  166,
  167,
  168,
  169,
  170,
  171,
  172,
  173,
  174,
  175,
  176,
  177,
  178,
  179,
  180,
  181,
  182,
  183,
  184,
  185,
  186,
  187,
  188,
  189,
  190,
  191,
  192,
  193,
  194,
  195,
  196,
  197,
  198,
  199,
  200,
  201,
  202,
  203,
  204,
  205,
  206,
  207,
  208,
  209,
  210,
  211,
  212,
  213,
  214,
  215,
  216,
  217,
  218,
  219,
  220,
  221,
  222,
  223,
  224,
  225,
  226,
  227,
  228,
  229,
  230,
  231,
  232,
  233,
  234,
  235,
  236,
  237,
  238,
  239,
  240,
  241,
  242,
  243,
  244,
  245,
  246,
  247,
  248,
  249,
  250,
  251,
  252,
  253,
  254,
  255,
  256,
  257,
  258,
  259,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  292,
  293,
  294,
  295,
  296,
  297,
  298,
  299,
  300,
  301,
  302,
  303,
  304,
  305,
  306,
  307,
  308,
  309,
  310,
  311,
  312,
  313,
  314,
  315,
  316,
  317,
  318,
  319,
  320,
  321,
  322,
  323,
  324,
  325,
  326,
  327,
  328,
  329,
  330,
  331,
  332,
  333,
  334,
  335,
  336,
  337,
  338,
  339,
  340,
  341,
  342,
  343,
  344,
  345,
  346,
  347,
  348,
  349,
  350,
  351,
  352,
  353,
  354,
  355,
  356,
  357,
  358,
  359,
  360,
  361,
  362,
  363,
  364,
  365,
  366,
  367,
  368,
  369,
  370,
  371,
  372,
  373,
  374,
  375,
  376,
  377,
  378,
  379,
  380,
  381,
  382,
  383,
  384,
  385,
  386,
  387,
  388,
  389,
  390,
  391,
  392,
  393,
  394,
  395,
  396,
  397,
  398,
  399,
  400,
  401,
  402,
  403,
  404,
  405,
  406,
  407,
  408,
  409,
  410,
  411,
  412,
  413,
  414,
  415,
  416,
  417,
  418,
  419,
  420,
  421,
  422,
  423,
  424,
  425,
  426,
  427,
  428,
  429,
  430,
  431,
  432,
  433,
  434,
  435,
  436,
  437,
  438,
  439,
  440,
  441,
  442,
  443,
  444,
  445,
  446,
  447,
  448,
  449,
  450,
  451,
  452,
  453,
  454,
  455,
  456,
  457,
  458,
  459,
  460,
  461,
  462,
  463,
  464,
  465,
  466,
  467,
  468,
  469,
  470,
  471,
  472,
  473,
  474,
  475,
  476,
  477,
  478,
  479,
  480,
  481,
  482,
  483,
  484,
  485,
  486,
  487,
  488,
  489,
  490,
  491,
  492,
  493,
  494,
  495,
  496,
  497,
  498,
  499,
  500,
  501,
  502,
  503,
  504,
  505,
  506,
  507,
  508,
  509,
  510,
  511,
  512,
  513,
  514,
  515,
  516,
  517,
  518,
  519,
  520,
  521,
  522,
  523,
  524,
  525,
  526,
  527,
  528,
  529,
  530,
  531,
  532,
  533,
  534,
  535,
  536,
  537,
  538,
  539,
  540,
  541,
  542,
  543,
  544,
  545,
  546,
  547,
  548,
  549,
  550,
  551,
  552,
  553,
  554,
  555,
  556,
  557,
  558,
  559,
  560,
  561,
  562,
  563,
  564,
  565,
  566,
  567,
  568,
  569,
  570,
  571,
  572,
  573,
  574,
  575,
  576,
  577,
  578,
  579,
  580,
  581,
  582,
  583,
  584,
  585,
  586,
  587,
  588,
  589,
  590,
  591,
  592,
  593,
  594,
  595,
  596,
  597,
  598,
  599,
  600,
  601,
  602,
  603,
  604,
  605,
  606,
  607,
  608,
  609,
  610,
  611,
  612,
  613,
  614,
  615,
  616,
  617,
  618,
  619,
  620,
  621,
  622,
  623,
  624,
  625,
  626,
  627,
  628,
  629,
  630,
  631,
  632,
  633,
  634,
  635,
  636,
  637,
  638,
  639,
  640,
  641,
  642,
  643,
  644,
  645,
  646,
  647,
  648,
  649,
  650,
  651,
  652,
  653,
  654,
  655,
  656,
  657,
  658,
  659,
  660,
  661,
  662,
  663,
  664,
  665,
  666,
  667,
  668,
  669,
  670,
  671,
  672,
  673,
  674,
  675,
  676,
  677,
  678,
  679,
  680,
  681,
  682,
  683,
  684,
  685,
  686,
  687,
  688,
  689,
  690,
  691,
  692,
  693,
  694,
  695,
  696,
  697,
  698,
  699,
  700,
  701,
  702,
  703,
  704,
  705,
  706,
  707,
  708,
  709,
  710,
  711,
  712,
  713,
  714,
  715,
  716,
  717,
  718,
  719,
  720,
  721,
  722,
  723,
  724,
  725,
  726,
  727,
  728,
  729,
  730,
  731,
  732,
  733,
  734,
  735,
  736,
  737,
  738,
  739,
  740,
  741,
  742,
  743,
  744,
  745,
  746,
  747,
  748,
  749,
  750,
  751,
  752,
  753,
  754,
  755,
  756,
  757,
  758,
  759,
  760,
  761,
  762,
  763,
  764,
  765,
  766,
  767,
  768,
  769,
  770,
  771,
  772,
  773,
  774,
  775,
  776,
  777,
  778,
  779,
  780,
  781,
  782,
  783,
  784,
  785,
  786,
  787,
  788,
  789,
  790,
  791,
  792,
  793,
  794,
  795,
  796,
  797,
  798,
  799,
  800,
  801,
  802,
  803,
  804,
  805,
  806,
  807,
  808,
  809,
  810,
  811,
  812,
  813,
  814,
  815,
  816,
  817,
  818,
  819,
  820,
  821,
  822,
  823,
  824,
  825,
  826,
  827,
  828,
  829,
  830,
  831,
  832,
  833,
  834,
  835,
  836,
  837,
  838,
  839,
  840,
  841,
  842,
  843,
  844,
  845,
  846,
  847,
  848,
  849,
  850,
  851,
  852,
  853,
  854,
  855,
  856,
  857,
  858,
  859,
  860,
  861,
  862,
  863,
  864,
  865,
  866,
  867,
  868,
  869,
  870,
  871,
  872,
  873,
  874,
  875,
  876,
  877,
  878,
  879,
  880,
  881,
  882,
  883,
  884,
  885,
  886,
  887,
  888,
  889,
  890],
 'columns': ['PassengerId',
  'Survived',
  'Pclass',
  'Name',
  'Sex',
  'Age',
  'SibSp',
  'Parch',
  'Ticket',
  'Fare',
  'Cabin',
  'Embarked'],
 'data': [[1,
   0,
   3,
   'Braund, Mr. Owen Harris',
   'male',
   22.0,
   1,
   0,
   'A/5 21171',
   7.25,
   nan,
   'S'],
  [2,
   1,
   1,
   'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
   'female',
   38.0,
   1,
   0,
   'PC 17599',
   71.2833,
   'C85',
   'C'],
  [3,
   1,
   3,
   'Heikkinen, Miss. Laina',
   'female',
   26.0,
   0,
   0,
   'STON/O2. 3101282',
   7.925,
   nan,
   'S'],
  [4,
   1,
   1,
   'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
   'female',
   35.0,
   1,
   0,
   '113803',
   53.1,
   'C123',
   'S'],
  [5,
   0,
   3,
   'Allen, Mr. William Henry',
   'male',
   35.0,
   0,
   0,
   '373450',
   8.05,
   nan,
   'S'],
  [6, 0, 3, 'Moran, Mr. James', 'male', nan, 0, 0, '330877', 8.4583, nan, 'Q'],
  [7,
   0,
   1,
   'McCarthy, Mr. Timothy J',
   'male',
   54.0,
   0,
   0,
   '17463',
   51.8625,
   'E46',
   'S'],
  [8,
   0,
   3,
   'Palsson, Master. Gosta Leonard',
   'male',
   2.0,
   3,
   1,
   '349909',
   21.075,
   nan,
   'S'],
  [9,
   1,
   3,
   'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
   'female',
   27.0,
   0,
   2,
   '347742',
   11.1333,
   nan,
   'S'],
  [10,
   1,
   2,
   'Nasser, Mrs. Nicholas (Adele Achem)',
   'female',
   14.0,
   1,
   0,
   '237736',
   30.0708,
   nan,
   'C'],
  [11,
   1,
   3,
   'Sandstrom, Miss. Marguerite Rut',
   'female',
   4.0,
   1,
   1,
   'PP 9549',
   16.7,
   'G6',
   'S'],
  [12,
   1,
   1,
   'Bonnell, Miss. Elizabeth',
   'female',
   58.0,
   0,
   0,
   '113783',
   26.55,
   'C103',
   'S'],
  [13,
   0,
   3,
   'Saundercock, Mr. William Henry',
   'male',
   20.0,
   0,
   0,
   'A/5. 2151',
   8.05,
   nan,
   'S'],
  [14,
   0,
   3,
   'Andersson, Mr. Anders Johan',
   'male',
   39.0,
   1,
   5,
   '347082',
   31.275,
   nan,
   'S'],
  [15,
   0,
   3,
   'Vestrom, Miss. Hulda Amanda Adolfina',
   'female',
   14.0,
   0,
   0,
   '350406',
   7.8542,
   nan,
   'S'],
  [16,
   1,
   2,
   'Hewlett, Mrs. (Mary D Kingcome) ',
   'female',
   55.0,
   0,
   0,
   '248706',
   16.0,
   nan,
   'S'],
  [17,
   0,
   3,
   'Rice, Master. Eugene',
   'male',
   2.0,
   4,
   1,
   '382652',
   29.125,
   nan,
   'Q'],
  [18,
   1,
   2,
   'Williams, Mr. Charles Eugene',
   'male',
   nan,
   0,
   0,
   '244373',
   13.0,
   nan,
   'S'],
  [19,
   0,
   3,
   'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
   'female',
   31.0,
   1,
   0,
   '345763',
   18.0,
   nan,
   'S'],
  [20,
   1,
   3,
   'Masselmani, Mrs. Fatima',
   'female',
   nan,
   0,
   0,
   '2649',
   7.225,
   nan,
   'C'],
  [21,
   0,
   2,
   'Fynney, Mr. Joseph J',
   'male',
   35.0,
   0,
   0,
   '239865',
   26.0,
   nan,
   'S'],
  [22,
   1,
   2,
   'Beesley, Mr. Lawrence',
   'male',
   34.0,
   0,
   0,
   '248698',
   13.0,
   'D56',
   'S'],
  [23,
   1,
   3,
   'McGowan, Miss. Anna "Annie"',
   'female',
   15.0,
   0,
   0,
   '330923',
   8.0292,
   nan,
   'Q'],
  [24,
   1,
   1,
   'Sloper, Mr. William Thompson',
   'male',
   28.0,
   0,
   0,
   '113788',
   35.5,
   'A6',
   'S'],
  [25,
   0,
   3,
   'Palsson, Miss. Torborg Danira',
   'female',
   8.0,
   3,
   1,
   '349909',
   21.075,
   nan,
   'S'],
  [26,
   1,
   3,
   'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
   'female',
   38.0,
   1,
   5,
   '347077',
   31.3875,
   nan,
   'S'],
  [27,
   0,
   3,
   'Emir, Mr. Farred Chehab',
   'male',
   nan,
   0,
   0,
   '2631',
   7.225,
   nan,
   'C'],
  [28,
   0,
   1,
   'Fortune, Mr. Charles Alexander',
   'male',
   19.0,
   3,
   2,
   '19950',
   263.0,
   'C23 C25 C27',
   'S'],
  [29,
   1,
   3,
   'O\'Dwyer, Miss. Ellen "Nellie"',
   'female',
   nan,
   0,
   0,
   '330959',
   7.8792,
   nan,
   'Q'],
  [30,
   0,
   3,
   'Todoroff, Mr. Lalio',
   'male',
   nan,
   0,
   0,
   '349216',
   7.8958,
   nan,
   'S'],
  [31,
   0,
   1,
   'Uruchurtu, Don. Manuel E',
   'male',
   40.0,
   0,
   0,
   'PC 17601',
   27.7208,
   nan,
   'C'],
  [32,
   1,
   1,
   'Spencer, Mrs. William Augustus (Marie Eugenie)',
   'female',
   nan,
   1,
   0,
   'PC 17569',
   146.5208,
   'B78',
   'C'],
  [33,
   1,
   3,
   'Glynn, Miss. Mary Agatha',
   'female',
   nan,
   0,
   0,
   '335677',
   7.75,
   nan,
   'Q'],
  [34,
   0,
   2,
   'Wheadon, Mr. Edward H',
   'male',
   66.0,
   0,
   0,
   'C.A. 24579',
   10.5,
   nan,
   'S'],
  [35,
   0,
   1,
   'Meyer, Mr. Edgar Joseph',
   'male',
   28.0,
   1,
   0,
   'PC 17604',
   82.1708,
   nan,
   'C'],
  [36,
   0,
   1,
   'Holverson, Mr. Alexander Oskar',
   'male',
   42.0,
   1,
   0,
   '113789',
   52.0,
   nan,
   'S'],
  [37, 1, 3, 'Mamee, Mr. Hanna', 'male', nan, 0, 0, '2677', 7.2292, nan, 'C'],
  [38,
   0,
   3,
   'Cann, Mr. Ernest Charles',
   'male',
   21.0,
   0,
   0,
   'A./5. 2152',
   8.05,
   nan,
   'S'],
  [39,
   0,
   3,
   'Vander Planke, Miss. Augusta Maria',
   'female',
   18.0,
   2,
   0,
   '345764',
   18.0,
   nan,
   'S'],
  [40,
   1,
   3,
   'Nicola-Yarred, Miss. Jamila',
   'female',
   14.0,
   1,
   0,
   '2651',
   11.2417,
   nan,
   'C'],
  [41,
   0,
   3,
   'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
   'female',
   40.0,
   1,
   0,
   '7546',
   9.475,
   nan,
   'S'],
  [42,
   0,
   2,
   'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
   'female',
   27.0,
   1,
   0,
   '11668',
   21.0,
   nan,
   'S'],
  [43,
   0,
   3,
   'Kraeff, Mr. Theodor',
   'male',
   nan,
   0,
   0,
   '349253',
   7.8958,
   nan,
   'C'],
  [44,
   1,
   2,
   'Laroche, Miss. Simonne Marie Anne Andree',
   'female',
   3.0,
   1,
   2,
   'SC/Paris 2123',
   41.5792,
   nan,
   'C'],
  [45,
   1,
   3,
   'Devaney, Miss. Margaret Delia',
   'female',
   19.0,
   0,
   0,
   '330958',
   7.8792,
   nan,
   'Q'],
  [46,
   0,
   3,
   'Rogers, Mr. William John',
   'male',
   nan,
   0,
   0,
   'S.C./A.4. 23567',
   8.05,
   nan,
   'S'],
  [47, 0, 3, 'Lennon, Mr. Denis', 'male', nan, 1, 0, '370371', 15.5, nan, 'Q'],
  [48,
   1,
   3,
   "O'Driscoll, Miss. Bridget",
   'female',
   nan,
   0,
   0,
   '14311',
   7.75,
   nan,
   'Q'],
  [49,
   0,
   3,
   'Samaan, Mr. Youssef',
   'male',
   nan,
   2,
   0,
   '2662',
   21.6792,
   nan,
   'C'],
  [50,
   0,
   3,
   'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
   'female',
   18.0,
   1,
   0,
   '349237',
   17.8,
   nan,
   'S'],
  [51,
   0,
   3,
   'Panula, Master. Juha Niilo',
   'male',
   7.0,
   4,
   1,
   '3101295',
   39.6875,
   nan,
   'S'],
  [52,
   0,
   3,
   'Nosworthy, Mr. Richard Cater',
   'male',
   21.0,
   0,
   0,
   'A/4. 39886',
   7.8,
   nan,
   'S'],
  [53,
   1,
   1,
   'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
   'female',
   49.0,
   1,
   0,
   'PC 17572',
   76.7292,
   'D33',
   'C'],
  [54,
   1,
   2,
   'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
   'female',
   29.0,
   1,
   0,
   '2926',
   26.0,
   nan,
   'S'],
  [55,
   0,
   1,
   'Ostby, Mr. Engelhart Cornelius',
   'male',
   65.0,
   0,
   1,
   '113509',
   61.9792,
   'B30',
   'C'],
  [56,
   1,
   1,
   'Woolner, Mr. Hugh',
   'male',
   nan,
   0,
   0,
   '19947',
   35.5,
   'C52',
   'S'],
  [57,
   1,
   2,
   'Rugg, Miss. Emily',
   'female',
   21.0,
   0,
   0,
   'C.A. 31026',
   10.5,
   nan,
   'S'],
  [58,
   0,
   3,
   'Novel, Mr. Mansouer',
   'male',
   28.5,
   0,
   0,
   '2697',
   7.2292,
   nan,
   'C'],
  [59,
   1,
   2,
   'West, Miss. Constance Mirium',
   'female',
   5.0,
   1,
   2,
   'C.A. 34651',
   27.75,
   nan,
   'S'],
  [60,
   0,
   3,
   'Goodwin, Master. William Frederick',
   'male',
   11.0,
   5,
   2,
   'CA 2144',
   46.9,
   nan,
   'S'],
  [61,
   0,
   3,
   'Sirayanian, Mr. Orsen',
   'male',
   22.0,
   0,
   0,
   '2669',
   7.2292,
   nan,
   'C'],
  [62,
   1,
   1,
   'Icard, Miss. Amelie',
   'female',
   38.0,
   0,
   0,
   '113572',
   80.0,
   'B28',
   nan],
  [63,
   0,
   1,
   'Harris, Mr. Henry Birkhardt',
   'male',
   45.0,
   1,
   0,
   '36973',
   83.475,
   'C83',
   'S'],
  [64,
   0,
   3,
   'Skoog, Master. Harald',
   'male',
   4.0,
   3,
   2,
   '347088',
   27.9,
   nan,
   'S'],
  [65,
   0,
   1,
   'Stewart, Mr. Albert A',
   'male',
   nan,
   0,
   0,
   'PC 17605',
   27.7208,
   nan,
   'C'],
  [66,
   1,
   3,
   'Moubarek, Master. Gerios',
   'male',
   nan,
   1,
   1,
   '2661',
   15.2458,
   nan,
   'C'],
  [67,
   1,
   2,
   'Nye, Mrs. (Elizabeth Ramell)',
   'female',
   29.0,
   0,
   0,
   'C.A. 29395',
   10.5,
   'F33',
   'S'],
  [68,
   0,
   3,
   'Crease, Mr. Ernest James',
   'male',
   19.0,
   0,
   0,
   'S.P. 3464',
   8.1583,
   nan,
   'S'],
  [69,
   1,
   3,
   'Andersson, Miss. Erna Alexandra',
   'female',
   17.0,
   4,
   2,
   '3101281',
   7.925,
   nan,
   'S'],
  [70,
   0,
   3,
   'Kink, Mr. Vincenz',
   'male',
   26.0,
   2,
   0,
   '315151',
   8.6625,
   nan,
   'S'],
  [71,
   0,
   2,
   'Jenkin, Mr. Stephen Curnow',
   'male',
   32.0,
   0,
   0,
   'C.A. 33111',
   10.5,
   nan,
   'S'],
  [72,
   0,
   3,
   'Goodwin, Miss. Lillian Amy',
   'female',
   16.0,
   5,
   2,
   'CA 2144',
   46.9,
   nan,
   'S'],
  [73,
   0,
   2,
   'Hood, Mr. Ambrose Jr',
   'male',
   21.0,
   0,
   0,
   'S.O.C. 14879',
   73.5,
   nan,
   'S'],
  [74,
   0,
   3,
   'Chronopoulos, Mr. Apostolos',
   'male',
   26.0,
   1,
   0,
   '2680',
   14.4542,
   nan,
   'C'],
  [75, 1, 3, 'Bing, Mr. Lee', 'male', 32.0, 0, 0, '1601', 56.4958, nan, 'S'],
  [76,
   0,
   3,
   'Moen, Mr. Sigurd Hansen',
   'male',
   25.0,
   0,
   0,
   '348123',
   7.65,
   'F G73',
   'S'],
  [77,
   0,
   3,
   'Staneff, Mr. Ivan',
   'male',
   nan,
   0,
   0,
   '349208',
   7.8958,
   nan,
   'S'],
  [78,
   0,
   3,
   'Moutal, Mr. Rahamin Haim',
   'male',
   nan,
   0,
   0,
   '374746',
   8.05,
   nan,
   'S'],
  [79,
   1,
   2,
   'Caldwell, Master. Alden Gates',
   'male',
   0.83,
   0,
   2,
   '248738',
   29.0,
   nan,
   'S'],
  [80,
   1,
   3,
   'Dowdell, Miss. Elizabeth',
   'female',
   30.0,
   0,
   0,
   '364516',
   12.475,
   nan,
   'S'],
  [81,
   0,
   3,
   'Waelens, Mr. Achille',
   'male',
   22.0,
   0,
   0,
   '345767',
   9.0,
   nan,
   'S'],
  [82,
   1,
   3,
   'Sheerlinck, Mr. Jan Baptist',
   'male',
   29.0,
   0,
   0,
   '345779',
   9.5,
   nan,
   'S'],
  [83,
   1,
   3,
   'McDermott, Miss. Brigdet Delia',
   'female',
   nan,
   0,
   0,
   '330932',
   7.7875,
   nan,
   'Q'],
  [84,
   0,
   1,
   'Carrau, Mr. Francisco M',
   'male',
   28.0,
   0,
   0,
   '113059',
   47.1,
   nan,
   'S'],
  [85,
   1,
   2,
   'Ilett, Miss. Bertha',
   'female',
   17.0,
   0,
   0,
   'SO/C 14885',
   10.5,
   nan,
   'S'],
  [86,
   1,
   3,
   'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
   'female',
   33.0,
   3,
   0,
   '3101278',
   15.85,
   nan,
   'S'],
  [87,
   0,
   3,
   'Ford, Mr. William Neal',
   'male',
   16.0,
   1,
   3,
   'W./C. 6608',
   34.375,
   nan,
   'S'],
  [88,
   0,
   3,
   'Slocovski, Mr. Selman Francis',
   'male',
   nan,
   0,
   0,
   'SOTON/OQ 392086',
   8.05,
   nan,
   'S'],
  [89,
   1,
   1,
   'Fortune, Miss. Mabel Helen',
   'female',
   23.0,
   3,
   2,
   '19950',
   263.0,
   'C23 C25 C27',
   'S'],
  [90,
   0,
   3,
   'Celotti, Mr. Francesco',
   'male',
   24.0,
   0,
   0,
   '343275',
   8.05,
   nan,
   'S'],
  [91,
   0,
   3,
   'Christmann, Mr. Emil',
   'male',
   29.0,
   0,
   0,
   '343276',
   8.05,
   nan,
   'S'],
  [92,
   0,
   3,
   'Andreasson, Mr. Paul Edvin',
   'male',
   20.0,
   0,
   0,
   '347466',
   7.8542,
   nan,
   'S'],
  [93,
   0,
   1,
   'Chaffee, Mr. Herbert Fuller',
   'male',
   46.0,
   1,
   0,
   'W.E.P. 5734',
   61.175,
   'E31',
   'S'],
  [94,
   0,
   3,
   'Dean, Mr. Bertram Frank',
   'male',
   26.0,
   1,
   2,
   'C.A. 2315',
   20.575,
   nan,
   'S'],
  [95,
   0,
   3,
   'Coxon, Mr. Daniel',
   'male',
   59.0,
   0,
   0,
   '364500',
   7.25,
   nan,
   'S'],
  [96,
   0,
   3,
   'Shorney, Mr. Charles Joseph',
   'male',
   nan,
   0,
   0,
   '374910',
   8.05,
   nan,
   'S'],
  [97,
   0,
   1,
   'Goldschmidt, Mr. George B',
   'male',
   71.0,
   0,
   0,
   'PC 17754',
   34.6542,
   'A5',
   'C'],
  [98,
   1,
   1,
   'Greenfield, Mr. William Bertram',
   'male',
   23.0,
   0,
   1,
   'PC 17759',
   63.3583,
   'D10 D12',
   'C'],
  [99,
   1,
   2,
   'Doling, Mrs. John T (Ada Julia Bone)',
   'female',
   34.0,
   0,
   1,
   '231919',
   23.0,
   nan,
   'S'],
  [100,
   0,
   2,
   'Kantor, Mr. Sinai',
   'male',
   34.0,
   1,
   0,
   '244367',
   26.0,
   nan,
   'S'],
  [101,
   0,
   3,
   'Petranec, Miss. Matilda',
   'female',
   28.0,
   0,
   0,
   '349245',
   7.8958,
   nan,
   'S'],
  [102,
   0,
   3,
   'Petroff, Mr. Pastcho ("Pentcho")',
   'male',
   nan,
   0,
   0,
   '349215',
   7.8958,
   nan,
   'S'],
  [103,
   0,
   1,
   'White, Mr. Richard Frasar',
   'male',
   21.0,
   0,
   1,
   '35281',
   77.2875,
   'D26',
   'S'],
  [104,
   0,
   3,
   'Johansson, Mr. Gustaf Joel',
   'male',
   33.0,
   0,
   0,
   '7540',
   8.6542,
   nan,
   'S'],
  [105,
   0,
   3,
   'Gustafsson, Mr. Anders Vilhelm',
   'male',
   37.0,
   2,
   0,
   '3101276',
   7.925,
   nan,
   'S'],
  [106,
   0,
   3,
   'Mionoff, Mr. Stoytcho',
   'male',
   28.0,
   0,
   0,
   '349207',
   7.8958,
   nan,
   'S'],
  [107,
   1,
   3,
   'Salkjelsvik, Miss. Anna Kristine',
   'female',
   21.0,
   0,
   0,
   '343120',
   7.65,
   nan,
   'S'],
  [108,
   1,
   3,
   'Moss, Mr. Albert Johan',
   'male',
   nan,
   0,
   0,
   '312991',
   7.775,
   nan,
   'S'],
  [109,
   0,
   3,
   'Rekic, Mr. Tido',
   'male',

### records - each row becomes a dictionary where key is column name and value is the data in the cell

In [10]:
df.to_dict('records')

[{'PassengerId': 1,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Braund, Mr. Owen Harris',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'A/5 21171',
  'Fare': 7.25,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 2,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17599',
  'Fare': 71.2833,
  'Cabin': 'C85',
  'Embarked': 'C'},
 {'PassengerId': 3,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Heikkinen, Miss. Laina',
  'Sex': 'female',
  'Age': 26.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'STON/O2. 3101282',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 4,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'Sex': 'female',
  'Age': 35.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113803',
  'Fare': 53.1,
  'Cabin': 'C123',
  'Embarked': 'S'},
 {'PassengerId': 5,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Allen, Mr. William Henry',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '373450',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 6,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moran, Mr. James',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330877',
  'Fare': 8.4583,
  'Cabin': nan,
  'Embarked': 'Q'},
 {'PassengerId': 7,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'McCarthy, Mr. Timothy J',
  'Sex': 'male',
  'Age': 54.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '17463',
  'Fare': 51.8625,
  'Cabin': 'E46',
  'Embarked': 'S'},
 {'PassengerId': 8,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson, Master. Gosta Leonard',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 9,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '347742',
  'Fare': 11.1333,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 10,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nasser, Mrs. Nicholas (Adele Achem)',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '237736',
  'Fare': 30.0708,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 11,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sandstrom, Miss. Marguerite Rut',
  'Sex': 'female',
  'Age': 4.0,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': 'PP 9549',
  'Fare': 16.7,
  'Cabin': 'G6',
  'Embarked': 'S'},
 {'PassengerId': 12,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Bonnell, Miss. Elizabeth',
  'Sex': 'female',
  'Age': 58.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113783',
  'Fare': 26.55,
  'Cabin': 'C103',
  'Embarked': 'S'},
 {'PassengerId': 13,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Saundercock, Mr. William Henry',
  'Sex': 'male',
  'Age': 20.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/5. 2151',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 14,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Andersson, Mr. Anders Johan',
  'Sex': 'male',
  'Age': 39.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347082',
  'Fare': 31.275,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 15,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vestrom, Miss. Hulda Amanda Adolfina',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '350406',
  'Fare': 7.8542,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 16,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Hewlett, Mrs. (Mary D Kingcome) ',
  'Sex': 'female',
  'Age': 55.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248706',
  'Fare': 16.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 17,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rice, Master. Eugene',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '382652',
  'Fare': 29.125,
  'Cabin': nan,
  'Embarked': 'Q'},
 {'PassengerId': 18,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Williams, Mr. Charles Eugene',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '244373',
  'Fare': 13.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 19,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'Sex': 'female',
  'Age': 31.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '345763',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 20,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Masselmani, Mrs. Fatima',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2649',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 21,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Fynney, Mr. Joseph J',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '239865',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 22,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Beesley, Mr. Lawrence',
  'Sex': 'male',
  'Age': 34.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248698',
  'Fare': 13.0,
  'Cabin': 'D56',
  'Embarked': 'S'},
 {'PassengerId': 23,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McGowan, Miss. Anna "Annie"',
  'Sex': 'female',
  'Age': 15.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330923',
  'Fare': 8.0292,
  'Cabin': nan,
  'Embarked': 'Q'},
 {'PassengerId': 24,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Sloper, Mr. William Thompson',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113788',
  'Fare': 35.5,
  'Cabin': 'A6',
  'Embarked': 'S'},
 {'PassengerId': 25,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson, Miss. Torborg Danira',
  'Sex': 'female',
  'Age': 8.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 26,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347077',
  'Fare': 31.3875,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 27,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Emir, Mr. Farred Chehab',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2631',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 28,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Fortune, Mr. Charles Alexander',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '19950',
  'Fare': 263.0,
  'Cabin': 'C23 C25 C27',
  'Embarked': 'S'},
 {'PassengerId': 29,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'O\'Dwyer, Miss. Ellen "Nellie"',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330959',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q'},
 {'PassengerId': 30,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Todoroff, Mr. Lalio',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349216',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 31,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Uruchurtu, Don. Manuel E',
  'Sex': 'male',
  'Age': 40.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17601',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 32,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17569',
  'Fare': 146.5208,
  'Cabin': 'B78',
  'Embarked': 'C'},
 {'PassengerId': 33,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Glynn, Miss. Mary Agatha',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '335677',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q'},
 {'PassengerId': 34,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Wheadon, Mr. Edward H',
  'Sex': 'male',
  'Age': 66.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 24579',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 35,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Meyer, Mr. Edgar Joseph',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17604',
  'Fare': 82.1708,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 36,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Holverson, Mr. Alexander Oskar',
  'Sex': 'male',
  'Age': 42.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113789',
  'Fare': 52.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 37,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Mamee, Mr. Hanna',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2677',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 38,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Cann, Mr. Ernest Charles',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A./5. 2152',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 39,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke, Miss. Augusta Maria',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '345764',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 40,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Nicola-Yarred, Miss. Jamila',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2651',
  'Fare': 11.2417,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 41,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'Sex': 'female',
  'Age': 40.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '7546',
  'Fare': 9.475,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 42,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '11668',
  'Fare': 21.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 43,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kraeff, Mr. Theodor',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349253',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 44,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Laroche, Miss. Simonne Marie Anne Andree',
  'Sex': 'female',
  'Age': 3.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'SC/Paris 2123',
  'Fare': 41.5792,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 45,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Devaney, Miss. Margaret Delia',
  'Sex': 'female',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330958',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q'},
 {'PassengerId': 46,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rogers, Mr. William John',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.C./A.4. 23567',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 47,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Lennon, Mr. Denis',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '370371',
  'Fare': 15.5,
  'Cabin': nan,
  'Embarked': 'Q'},
 {'PassengerId': 48,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Driscoll, Miss. Bridget",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '14311',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q'},
 {'PassengerId': 49,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Samaan, Mr. Youssef',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '2662',
  'Fare': 21.6792,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 50,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '349237',
  'Fare': 17.8,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 51,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Panula, Master. Juha Niilo',
  'Sex': 'male',
  'Age': 7.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '3101295',
  'Fare': 39.6875,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 52,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Nosworthy, Mr. Richard Cater',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/4. 39886',
  'Fare': 7.8,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 53,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'Sex': 'female',
  'Age': 49.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17572',
  'Fare': 76.7292,
  'Cabin': 'D33',
  'Embarked': 'C'},
 {'PassengerId': 54,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2926',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 55,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Ostby, Mr. Engelhart Cornelius',
  'Sex': 'male',
  'Age': 65.0,
  'SibSp': 0,
  'Parch': 1,
  'Ticket': '113509',
  'Fare': 61.9792,
  'Cabin': 'B30',
  'Embarked': 'C'},
 {'PassengerId': 56,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Woolner, Mr. Hugh',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '19947',
  'Fare': 35.5,
  'Cabin': 'C52',
  'Embarked': 'S'},
 {'PassengerId': 57,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Rugg, Miss. Emily',
  'Sex': 'female',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 31026',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 58,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Novel, Mr. Mansouer',
  'Sex': 'male',
  'Age': 28.5,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2697',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 59,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'West, Miss. Constance Mirium',
  'Sex': 'female',
  'Age': 5.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'C.A. 34651',
  'Fare': 27.75,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 60,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin, Master. William Frederick',
  'Sex': 'male',
  'Age': 11.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 61,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Sirayanian, Mr. Orsen',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2669',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 62,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Icard, Miss. Amelie',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113572',
  'Fare': 80.0,
  'Cabin': 'B28',
  'Embarked': nan},
 {'PassengerId': 63,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Harris, Mr. Henry Birkhardt',
  'Sex': 'male',
  'Age': 45.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '36973',
  'Fare': 83.475,
  'Cabin': 'C83',
  'Embarked': 'S'},
 {'PassengerId': 64,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Skoog, Master. Harald',
  'Sex': 'male',
  'Age': 4.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '347088',
  'Fare': 27.9,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 65,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Stewart, Mr. Albert A',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17605',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 66,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Moubarek, Master. Gerios',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': '2661',
  'Fare': 15.2458,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 67,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nye, Mrs. (Elizabeth Ramell)',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 29395',
  'Fare': 10.5,
  'Cabin': 'F33',
  'Embarked': 'S'},
 {'PassengerId': 68,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Crease, Mr. Ernest James',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.P. 3464',
  'Fare': 8.1583,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 69,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Andersson, Miss. Erna Alexandra',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 4,
  'Parch': 2,
  'Ticket': '3101281',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 70,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kink, Mr. Vincenz',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '315151',
  'Fare': 8.6625,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 71,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Jenkin, Mr. Stephen Curnow',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 33111',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 72,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin, Miss. Lillian Amy',
  'Sex': 'female',
  'Age': 16.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 73,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Hood, Mr. Ambrose Jr',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.O.C. 14879',
  'Fare': 73.5,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 74,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Chronopoulos, Mr. Apostolos',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2680',
  'Fare': 14.4542,
  'Cabin': nan,
  'Embarked': 'C'},
 {'PassengerId': 75,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Bing, Mr. Lee',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '1601',
  'Fare': 56.4958,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 76,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moen, Mr. Sigurd Hansen',
  'Sex': 'male',
  'Age': 25.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '348123',
  'Fare': 7.65,
  'Cabin': 'F G73',
  'Embarked': 'S'},
 {'PassengerId': 77,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Staneff, Mr. Ivan',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349208',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 78,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moutal, Mr. Rahamin Haim',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '374746',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 79,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Caldwell, Master. Alden Gates',
  'Sex': 'male',
  'Age': 0.83,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '248738',
  'Fare': 29.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 80,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Dowdell, Miss. Elizabeth',
  'Sex': 'female',
  'Age': 30.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '364516',
  'Fare': 12.475,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 81,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Waelens, Mr. Achille',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '345767',
  'Fare': 9.0,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 82,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sheerlinck, Mr. Jan Baptist',
  'Sex': 'male',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '345779',
  'Fare': 9.5,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 83,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McDermott, Miss. Brigdet Delia',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330932',
  'Fare': 7.7875,
  'Cabin': nan,
  'Embarked': 'Q'},
 {'PassengerId': 84,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Carrau, Mr. Francisco M',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113059',
  'Fare': 47.1,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 85,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Ilett, Miss. Bertha',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'SO/C 14885',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 86,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
  'Sex': 'female',
  'Age': 33.0,
  'SibSp': 3,
  'Parch': 0,
  'Ticket': '3101278',
  'Fare': 15.85,
  'Cabin': nan,
  'Embarked': 'S'},
 {'PassengerId': 87,
  'Survived': 0,

### index - like 'records', but a dictionary of dictionaries with keys as index labels (rather than a list)

In [11]:
df.to_dict('index')

{0: {'PassengerId': 1,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Braund, Mr. Owen Harris',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'A/5 21171',
  'Fare': 7.25,
  'Cabin': nan,
  'Embarked': 'S'},
 1: {'PassengerId': 2,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17599',
  'Fare': 71.2833,
  'Cabin': 'C85',
  'Embarked': 'C'},
 2: {'PassengerId': 3,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Heikkinen, Miss. Laina',
  'Sex': 'female',
  'Age': 26.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'STON/O2. 3101282',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S'},
 3: {'PassengerId': 4,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'Sex': 'female',
  'Age': 35.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113803',
  'Fare': 53.1,
  'Cabin': 'C123',
  'Embarked': 'S'},
 4: {'PassengerId': 5,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Allen, Mr. William Henry',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '373450',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 5: {'PassengerId': 6,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moran, Mr. James',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330877',
  'Fare': 8.4583,
  'Cabin': nan,
  'Embarked': 'Q'},
 6: {'PassengerId': 7,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'McCarthy, Mr. Timothy J',
  'Sex': 'male',
  'Age': 54.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '17463',
  'Fare': 51.8625,
  'Cabin': 'E46',
  'Embarked': 'S'},
 7: {'PassengerId': 8,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson, Master. Gosta Leonard',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S'},
 8: {'PassengerId': 9,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '347742',
  'Fare': 11.1333,
  'Cabin': nan,
  'Embarked': 'S'},
 9: {'PassengerId': 10,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nasser, Mrs. Nicholas (Adele Achem)',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '237736',
  'Fare': 30.0708,
  'Cabin': nan,
  'Embarked': 'C'},
 10: {'PassengerId': 11,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sandstrom, Miss. Marguerite Rut',
  'Sex': 'female',
  'Age': 4.0,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': 'PP 9549',
  'Fare': 16.7,
  'Cabin': 'G6',
  'Embarked': 'S'},
 11: {'PassengerId': 12,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Bonnell, Miss. Elizabeth',
  'Sex': 'female',
  'Age': 58.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113783',
  'Fare': 26.55,
  'Cabin': 'C103',
  'Embarked': 'S'},
 12: {'PassengerId': 13,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Saundercock, Mr. William Henry',
  'Sex': 'male',
  'Age': 20.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/5. 2151',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 13: {'PassengerId': 14,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Andersson, Mr. Anders Johan',
  'Sex': 'male',
  'Age': 39.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347082',
  'Fare': 31.275,
  'Cabin': nan,
  'Embarked': 'S'},
 14: {'PassengerId': 15,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vestrom, Miss. Hulda Amanda Adolfina',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '350406',
  'Fare': 7.8542,
  'Cabin': nan,
  'Embarked': 'S'},
 15: {'PassengerId': 16,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Hewlett, Mrs. (Mary D Kingcome) ',
  'Sex': 'female',
  'Age': 55.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248706',
  'Fare': 16.0,
  'Cabin': nan,
  'Embarked': 'S'},
 16: {'PassengerId': 17,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rice, Master. Eugene',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '382652',
  'Fare': 29.125,
  'Cabin': nan,
  'Embarked': 'Q'},
 17: {'PassengerId': 18,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Williams, Mr. Charles Eugene',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '244373',
  'Fare': 13.0,
  'Cabin': nan,
  'Embarked': 'S'},
 18: {'PassengerId': 19,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'Sex': 'female',
  'Age': 31.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '345763',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S'},
 19: {'PassengerId': 20,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Masselmani, Mrs. Fatima',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2649',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C'},
 20: {'PassengerId': 21,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Fynney, Mr. Joseph J',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '239865',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S'},
 21: {'PassengerId': 22,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Beesley, Mr. Lawrence',
  'Sex': 'male',
  'Age': 34.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248698',
  'Fare': 13.0,
  'Cabin': 'D56',
  'Embarked': 'S'},
 22: {'PassengerId': 23,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McGowan, Miss. Anna "Annie"',
  'Sex': 'female',
  'Age': 15.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330923',
  'Fare': 8.0292,
  'Cabin': nan,
  'Embarked': 'Q'},
 23: {'PassengerId': 24,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Sloper, Mr. William Thompson',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113788',
  'Fare': 35.5,
  'Cabin': 'A6',
  'Embarked': 'S'},
 24: {'PassengerId': 25,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson, Miss. Torborg Danira',
  'Sex': 'female',
  'Age': 8.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S'},
 25: {'PassengerId': 26,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347077',
  'Fare': 31.3875,
  'Cabin': nan,
  'Embarked': 'S'},
 26: {'PassengerId': 27,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Emir, Mr. Farred Chehab',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2631',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C'},
 27: {'PassengerId': 28,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Fortune, Mr. Charles Alexander',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '19950',
  'Fare': 263.0,
  'Cabin': 'C23 C25 C27',
  'Embarked': 'S'},
 28: {'PassengerId': 29,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'O\'Dwyer, Miss. Ellen "Nellie"',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330959',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q'},
 29: {'PassengerId': 30,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Todoroff, Mr. Lalio',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349216',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S'},
 30: {'PassengerId': 31,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Uruchurtu, Don. Manuel E',
  'Sex': 'male',
  'Age': 40.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17601',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C'},
 31: {'PassengerId': 32,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17569',
  'Fare': 146.5208,
  'Cabin': 'B78',
  'Embarked': 'C'},
 32: {'PassengerId': 33,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Glynn, Miss. Mary Agatha',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '335677',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q'},
 33: {'PassengerId': 34,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Wheadon, Mr. Edward H',
  'Sex': 'male',
  'Age': 66.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 24579',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 34: {'PassengerId': 35,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Meyer, Mr. Edgar Joseph',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17604',
  'Fare': 82.1708,
  'Cabin': nan,
  'Embarked': 'C'},
 35: {'PassengerId': 36,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Holverson, Mr. Alexander Oskar',
  'Sex': 'male',
  'Age': 42.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113789',
  'Fare': 52.0,
  'Cabin': nan,
  'Embarked': 'S'},
 36: {'PassengerId': 37,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Mamee, Mr. Hanna',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2677',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 37: {'PassengerId': 38,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Cann, Mr. Ernest Charles',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A./5. 2152',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 38: {'PassengerId': 39,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke, Miss. Augusta Maria',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '345764',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S'},
 39: {'PassengerId': 40,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Nicola-Yarred, Miss. Jamila',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2651',
  'Fare': 11.2417,
  'Cabin': nan,
  'Embarked': 'C'},
 40: {'PassengerId': 41,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'Sex': 'female',
  'Age': 40.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '7546',
  'Fare': 9.475,
  'Cabin': nan,
  'Embarked': 'S'},
 41: {'PassengerId': 42,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '11668',
  'Fare': 21.0,
  'Cabin': nan,
  'Embarked': 'S'},
 42: {'PassengerId': 43,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kraeff, Mr. Theodor',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349253',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'C'},
 43: {'PassengerId': 44,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Laroche, Miss. Simonne Marie Anne Andree',
  'Sex': 'female',
  'Age': 3.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'SC/Paris 2123',
  'Fare': 41.5792,
  'Cabin': nan,
  'Embarked': 'C'},
 44: {'PassengerId': 45,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Devaney, Miss. Margaret Delia',
  'Sex': 'female',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330958',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q'},
 45: {'PassengerId': 46,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rogers, Mr. William John',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.C./A.4. 23567',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 46: {'PassengerId': 47,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Lennon, Mr. Denis',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '370371',
  'Fare': 15.5,
  'Cabin': nan,
  'Embarked': 'Q'},
 47: {'PassengerId': 48,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Driscoll, Miss. Bridget",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '14311',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q'},
 48: {'PassengerId': 49,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Samaan, Mr. Youssef',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '2662',
  'Fare': 21.6792,
  'Cabin': nan,
  'Embarked': 'C'},
 49: {'PassengerId': 50,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '349237',
  'Fare': 17.8,
  'Cabin': nan,
  'Embarked': 'S'},
 50: {'PassengerId': 51,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Panula, Master. Juha Niilo',
  'Sex': 'male',
  'Age': 7.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '3101295',
  'Fare': 39.6875,
  'Cabin': nan,
  'Embarked': 'S'},
 51: {'PassengerId': 52,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Nosworthy, Mr. Richard Cater',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/4. 39886',
  'Fare': 7.8,
  'Cabin': nan,
  'Embarked': 'S'},
 52: {'PassengerId': 53,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'Sex': 'female',
  'Age': 49.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17572',
  'Fare': 76.7292,
  'Cabin': 'D33',
  'Embarked': 'C'},
 53: {'PassengerId': 54,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2926',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S'},
 54: {'PassengerId': 55,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Ostby, Mr. Engelhart Cornelius',
  'Sex': 'male',
  'Age': 65.0,
  'SibSp': 0,
  'Parch': 1,
  'Ticket': '113509',
  'Fare': 61.9792,
  'Cabin': 'B30',
  'Embarked': 'C'},
 55: {'PassengerId': 56,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Woolner, Mr. Hugh',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '19947',
  'Fare': 35.5,
  'Cabin': 'C52',
  'Embarked': 'S'},
 56: {'PassengerId': 57,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Rugg, Miss. Emily',
  'Sex': 'female',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 31026',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 57: {'PassengerId': 58,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Novel, Mr. Mansouer',
  'Sex': 'male',
  'Age': 28.5,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2697',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 58: {'PassengerId': 59,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'West, Miss. Constance Mirium',
  'Sex': 'female',
  'Age': 5.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'C.A. 34651',
  'Fare': 27.75,
  'Cabin': nan,
  'Embarked': 'S'},
 59: {'PassengerId': 60,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin, Master. William Frederick',
  'Sex': 'male',
  'Age': 11.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S'},
 60: {'PassengerId': 61,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Sirayanian, Mr. Orsen',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2669',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 61: {'PassengerId': 62,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Icard, Miss. Amelie',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113572',
  'Fare': 80.0,
  'Cabin': 'B28',
  'Embarked': nan},
 62: {'PassengerId': 63,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Harris, Mr. Henry Birkhardt',
  'Sex': 'male',
  'Age': 45.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '36973',
  'Fare': 83.475,
  'Cabin': 'C83',
  'Embarked': 'S'},
 63: {'PassengerId': 64,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Skoog, Master. Harald',
  'Sex': 'male',
  'Age': 4.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '347088',
  'Fare': 27.9,
  'Cabin': nan,
  'Embarked': 'S'},
 64: {'PassengerId': 65,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Stewart, Mr. Albert A',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17605',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C'},
 65: {'PassengerId': 66,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Moubarek, Master. Gerios',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': '2661',
  'Fare': 15.2458,
  'Cabin': nan,
  'Embarked': 'C'},
 66: {'PassengerId': 67,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nye, Mrs. (Elizabeth Ramell)',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 29395',
  'Fare': 10.5,
  'Cabin': 'F33',
  'Embarked': 'S'},
 67: {'PassengerId': 68,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Crease, Mr. Ernest James',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.P. 3464',
  'Fare': 8.1583,
  'Cabin': nan,
  'Embarked': 'S'},
 68: {'PassengerId': 69,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Andersson, Miss. Erna Alexandra',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 4,
  'Parch': 2,
  'Ticket': '3101281',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S'},
 69: {'PassengerId': 70,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kink, Mr. Vincenz',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '315151',
  'Fare': 8.6625,
  'Cabin': nan,
  'Embarked': 'S'},
 70: {'PassengerId': 71,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Jenkin, Mr. Stephen Curnow',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 33111',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 71: {'PassengerId': 72,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin, Miss. Lillian Amy',
  'Sex': 'female',
  'Age': 16.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S'},
 72: {'PassengerId': 73,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Hood, Mr. Ambrose Jr',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.O.C. 14879',
  'Fare': 73.5,
  'Cabin': nan,
  'Embarked': 'S'},
 73: {'PassengerId': 74,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Chronopoulos, Mr. Apostolos',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2680',
  'Fare': 14.4542,
  'Cabin': nan,
  'Embarked': 'C'},
 74: {'PassengerId': 75,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Bing, Mr. Lee',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '1601',
  'Fare': 56.4958,
  'Cabin': nan,
  'Embarked': 'S'},
 75: {'PassengerId': 76,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moen, Mr. Sigurd Hansen',
  'Sex': 'male',
  'Age': 25.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '348123',
  'Fare': 7.65,
  'Cabin': 'F G73',
  'Embarked': 'S'},
 76: {'PassengerId': 77,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Staneff, Mr. Ivan',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349208',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S'},
 77: {'PassengerId': 78,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moutal, Mr. Rahamin Haim',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '374746',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 78: {'PassengerId': 79,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Caldwell, Master. Alden Gates',
  'Sex': 'male',
  'Age': 0.83,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '248738',
  'Fare': 29.0,
  'Cabin': nan,
  'Embarked': 'S'},
 79: {'PassengerId': 80,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Dowdell, Miss. Elizabeth',
  'Sex': 'female',
  'Age': 30.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '364516',
  'Fare': 12.475,
  'Cabin': nan,
  'Embarked': 'S'},
 80: {'PassengerId': 81,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Waelens, Mr. Achille',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '345767',
  'Fare': 9.0,
  'Cabin': nan,
  'Embarked': 'S'},
 81: {'PassengerId': 82,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sheerlinck, Mr. Jan Baptist',
  'Sex': 'male',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '345779',
  'Fare': 9.5,
  'Cabin': nan,
  'Embarked': 'S'},
 82: {'PassengerId': 83,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McDermott, Miss. Brigdet Delia',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330932',
  'Fare': 7.7875,
  'Cabin': nan,
  'Embarked': 'Q'},
 83: {'PassengerId': 84,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Carrau, Mr. Francisco M',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113059',
  'Fare': 47.1,
  'Cabin': nan,
  'Embarked': 'S'},
 84: {'PassengerId': 85,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Ilett, Miss. Bertha',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'SO/C 14885',
  'Fare': 10.5,
  'Cabin': nan,

In [12]:
df_dictionary = df.to_dict('index')

In [13]:
df_dictionary

{0: {'PassengerId': 1,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Braund, Mr. Owen Harris',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'A/5 21171',
  'Fare': 7.25,
  'Cabin': nan,
  'Embarked': 'S'},
 1: {'PassengerId': 2,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17599',
  'Fare': 71.2833,
  'Cabin': 'C85',
  'Embarked': 'C'},
 2: {'PassengerId': 3,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Heikkinen, Miss. Laina',
  'Sex': 'female',
  'Age': 26.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'STON/O2. 3101282',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S'},
 3: {'PassengerId': 4,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'Sex': 'female',
  'Age': 35.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113803',
  'Fare': 53.1,
  'Cabin': 'C123',
  'Embarked': 'S'},
 4: {'PassengerId': 5,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Allen, Mr. William Henry',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '373450',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 5: {'PassengerId': 6,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moran, Mr. James',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330877',
  'Fare': 8.4583,
  'Cabin': nan,
  'Embarked': 'Q'},
 6: {'PassengerId': 7,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'McCarthy, Mr. Timothy J',
  'Sex': 'male',
  'Age': 54.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '17463',
  'Fare': 51.8625,
  'Cabin': 'E46',
  'Embarked': 'S'},
 7: {'PassengerId': 8,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson, Master. Gosta Leonard',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S'},
 8: {'PassengerId': 9,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '347742',
  'Fare': 11.1333,
  'Cabin': nan,
  'Embarked': 'S'},
 9: {'PassengerId': 10,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nasser, Mrs. Nicholas (Adele Achem)',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '237736',
  'Fare': 30.0708,
  'Cabin': nan,
  'Embarked': 'C'},
 10: {'PassengerId': 11,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sandstrom, Miss. Marguerite Rut',
  'Sex': 'female',
  'Age': 4.0,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': 'PP 9549',
  'Fare': 16.7,
  'Cabin': 'G6',
  'Embarked': 'S'},
 11: {'PassengerId': 12,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Bonnell, Miss. Elizabeth',
  'Sex': 'female',
  'Age': 58.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113783',
  'Fare': 26.55,
  'Cabin': 'C103',
  'Embarked': 'S'},
 12: {'PassengerId': 13,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Saundercock, Mr. William Henry',
  'Sex': 'male',
  'Age': 20.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/5. 2151',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 13: {'PassengerId': 14,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Andersson, Mr. Anders Johan',
  'Sex': 'male',
  'Age': 39.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347082',
  'Fare': 31.275,
  'Cabin': nan,
  'Embarked': 'S'},
 14: {'PassengerId': 15,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vestrom, Miss. Hulda Amanda Adolfina',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '350406',
  'Fare': 7.8542,
  'Cabin': nan,
  'Embarked': 'S'},
 15: {'PassengerId': 16,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Hewlett, Mrs. (Mary D Kingcome) ',
  'Sex': 'female',
  'Age': 55.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248706',
  'Fare': 16.0,
  'Cabin': nan,
  'Embarked': 'S'},
 16: {'PassengerId': 17,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rice, Master. Eugene',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '382652',
  'Fare': 29.125,
  'Cabin': nan,
  'Embarked': 'Q'},
 17: {'PassengerId': 18,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Williams, Mr. Charles Eugene',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '244373',
  'Fare': 13.0,
  'Cabin': nan,
  'Embarked': 'S'},
 18: {'PassengerId': 19,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'Sex': 'female',
  'Age': 31.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '345763',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S'},
 19: {'PassengerId': 20,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Masselmani, Mrs. Fatima',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2649',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C'},
 20: {'PassengerId': 21,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Fynney, Mr. Joseph J',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '239865',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S'},
 21: {'PassengerId': 22,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Beesley, Mr. Lawrence',
  'Sex': 'male',
  'Age': 34.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248698',
  'Fare': 13.0,
  'Cabin': 'D56',
  'Embarked': 'S'},
 22: {'PassengerId': 23,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McGowan, Miss. Anna "Annie"',
  'Sex': 'female',
  'Age': 15.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330923',
  'Fare': 8.0292,
  'Cabin': nan,
  'Embarked': 'Q'},
 23: {'PassengerId': 24,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Sloper, Mr. William Thompson',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113788',
  'Fare': 35.5,
  'Cabin': 'A6',
  'Embarked': 'S'},
 24: {'PassengerId': 25,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson, Miss. Torborg Danira',
  'Sex': 'female',
  'Age': 8.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S'},
 25: {'PassengerId': 26,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347077',
  'Fare': 31.3875,
  'Cabin': nan,
  'Embarked': 'S'},
 26: {'PassengerId': 27,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Emir, Mr. Farred Chehab',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2631',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C'},
 27: {'PassengerId': 28,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Fortune, Mr. Charles Alexander',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '19950',
  'Fare': 263.0,
  'Cabin': 'C23 C25 C27',
  'Embarked': 'S'},
 28: {'PassengerId': 29,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'O\'Dwyer, Miss. Ellen "Nellie"',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330959',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q'},
 29: {'PassengerId': 30,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Todoroff, Mr. Lalio',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349216',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S'},
 30: {'PassengerId': 31,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Uruchurtu, Don. Manuel E',
  'Sex': 'male',
  'Age': 40.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17601',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C'},
 31: {'PassengerId': 32,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17569',
  'Fare': 146.5208,
  'Cabin': 'B78',
  'Embarked': 'C'},
 32: {'PassengerId': 33,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Glynn, Miss. Mary Agatha',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '335677',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q'},
 33: {'PassengerId': 34,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Wheadon, Mr. Edward H',
  'Sex': 'male',
  'Age': 66.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 24579',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 34: {'PassengerId': 35,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Meyer, Mr. Edgar Joseph',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17604',
  'Fare': 82.1708,
  'Cabin': nan,
  'Embarked': 'C'},
 35: {'PassengerId': 36,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Holverson, Mr. Alexander Oskar',
  'Sex': 'male',
  'Age': 42.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113789',
  'Fare': 52.0,
  'Cabin': nan,
  'Embarked': 'S'},
 36: {'PassengerId': 37,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Mamee, Mr. Hanna',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2677',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 37: {'PassengerId': 38,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Cann, Mr. Ernest Charles',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A./5. 2152',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 38: {'PassengerId': 39,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke, Miss. Augusta Maria',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '345764',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S'},
 39: {'PassengerId': 40,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Nicola-Yarred, Miss. Jamila',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2651',
  'Fare': 11.2417,
  'Cabin': nan,
  'Embarked': 'C'},
 40: {'PassengerId': 41,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'Sex': 'female',
  'Age': 40.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '7546',
  'Fare': 9.475,
  'Cabin': nan,
  'Embarked': 'S'},
 41: {'PassengerId': 42,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '11668',
  'Fare': 21.0,
  'Cabin': nan,
  'Embarked': 'S'},
 42: {'PassengerId': 43,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kraeff, Mr. Theodor',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349253',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'C'},
 43: {'PassengerId': 44,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Laroche, Miss. Simonne Marie Anne Andree',
  'Sex': 'female',
  'Age': 3.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'SC/Paris 2123',
  'Fare': 41.5792,
  'Cabin': nan,
  'Embarked': 'C'},
 44: {'PassengerId': 45,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Devaney, Miss. Margaret Delia',
  'Sex': 'female',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330958',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q'},
 45: {'PassengerId': 46,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rogers, Mr. William John',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.C./A.4. 23567',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 46: {'PassengerId': 47,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Lennon, Mr. Denis',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '370371',
  'Fare': 15.5,
  'Cabin': nan,
  'Embarked': 'Q'},
 47: {'PassengerId': 48,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Driscoll, Miss. Bridget",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '14311',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q'},
 48: {'PassengerId': 49,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Samaan, Mr. Youssef',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '2662',
  'Fare': 21.6792,
  'Cabin': nan,
  'Embarked': 'C'},
 49: {'PassengerId': 50,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '349237',
  'Fare': 17.8,
  'Cabin': nan,
  'Embarked': 'S'},
 50: {'PassengerId': 51,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Panula, Master. Juha Niilo',
  'Sex': 'male',
  'Age': 7.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '3101295',
  'Fare': 39.6875,
  'Cabin': nan,
  'Embarked': 'S'},
 51: {'PassengerId': 52,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Nosworthy, Mr. Richard Cater',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/4. 39886',
  'Fare': 7.8,
  'Cabin': nan,
  'Embarked': 'S'},
 52: {'PassengerId': 53,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'Sex': 'female',
  'Age': 49.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17572',
  'Fare': 76.7292,
  'Cabin': 'D33',
  'Embarked': 'C'},
 53: {'PassengerId': 54,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2926',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S'},
 54: {'PassengerId': 55,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Ostby, Mr. Engelhart Cornelius',
  'Sex': 'male',
  'Age': 65.0,
  'SibSp': 0,
  'Parch': 1,
  'Ticket': '113509',
  'Fare': 61.9792,
  'Cabin': 'B30',
  'Embarked': 'C'},
 55: {'PassengerId': 56,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Woolner, Mr. Hugh',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '19947',
  'Fare': 35.5,
  'Cabin': 'C52',
  'Embarked': 'S'},
 56: {'PassengerId': 57,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Rugg, Miss. Emily',
  'Sex': 'female',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 31026',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 57: {'PassengerId': 58,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Novel, Mr. Mansouer',
  'Sex': 'male',
  'Age': 28.5,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2697',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 58: {'PassengerId': 59,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'West, Miss. Constance Mirium',
  'Sex': 'female',
  'Age': 5.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'C.A. 34651',
  'Fare': 27.75,
  'Cabin': nan,
  'Embarked': 'S'},
 59: {'PassengerId': 60,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin, Master. William Frederick',
  'Sex': 'male',
  'Age': 11.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S'},
 60: {'PassengerId': 61,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Sirayanian, Mr. Orsen',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2669',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 61: {'PassengerId': 62,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Icard, Miss. Amelie',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113572',
  'Fare': 80.0,
  'Cabin': 'B28',
  'Embarked': nan},
 62: {'PassengerId': 63,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Harris, Mr. Henry Birkhardt',
  'Sex': 'male',
  'Age': 45.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '36973',
  'Fare': 83.475,
  'Cabin': 'C83',
  'Embarked': 'S'},
 63: {'PassengerId': 64,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Skoog, Master. Harald',
  'Sex': 'male',
  'Age': 4.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '347088',
  'Fare': 27.9,
  'Cabin': nan,
  'Embarked': 'S'},
 64: {'PassengerId': 65,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Stewart, Mr. Albert A',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17605',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C'},
 65: {'PassengerId': 66,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Moubarek, Master. Gerios',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': '2661',
  'Fare': 15.2458,
  'Cabin': nan,
  'Embarked': 'C'},
 66: {'PassengerId': 67,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nye, Mrs. (Elizabeth Ramell)',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 29395',
  'Fare': 10.5,
  'Cabin': 'F33',
  'Embarked': 'S'},
 67: {'PassengerId': 68,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Crease, Mr. Ernest James',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.P. 3464',
  'Fare': 8.1583,
  'Cabin': nan,
  'Embarked': 'S'},
 68: {'PassengerId': 69,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Andersson, Miss. Erna Alexandra',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 4,
  'Parch': 2,
  'Ticket': '3101281',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S'},
 69: {'PassengerId': 70,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kink, Mr. Vincenz',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '315151',
  'Fare': 8.6625,
  'Cabin': nan,
  'Embarked': 'S'},
 70: {'PassengerId': 71,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Jenkin, Mr. Stephen Curnow',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 33111',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 71: {'PassengerId': 72,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin, Miss. Lillian Amy',
  'Sex': 'female',
  'Age': 16.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S'},
 72: {'PassengerId': 73,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Hood, Mr. Ambrose Jr',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.O.C. 14879',
  'Fare': 73.5,
  'Cabin': nan,
  'Embarked': 'S'},
 73: {'PassengerId': 74,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Chronopoulos, Mr. Apostolos',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2680',
  'Fare': 14.4542,
  'Cabin': nan,
  'Embarked': 'C'},
 74: {'PassengerId': 75,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Bing, Mr. Lee',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '1601',
  'Fare': 56.4958,
  'Cabin': nan,
  'Embarked': 'S'},
 75: {'PassengerId': 76,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moen, Mr. Sigurd Hansen',
  'Sex': 'male',
  'Age': 25.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '348123',
  'Fare': 7.65,
  'Cabin': 'F G73',
  'Embarked': 'S'},
 76: {'PassengerId': 77,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Staneff, Mr. Ivan',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349208',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S'},
 77: {'PassengerId': 78,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moutal, Mr. Rahamin Haim',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '374746',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 78: {'PassengerId': 79,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Caldwell, Master. Alden Gates',
  'Sex': 'male',
  'Age': 0.83,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '248738',
  'Fare': 29.0,
  'Cabin': nan,
  'Embarked': 'S'},
 79: {'PassengerId': 80,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Dowdell, Miss. Elizabeth',
  'Sex': 'female',
  'Age': 30.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '364516',
  'Fare': 12.475,
  'Cabin': nan,
  'Embarked': 'S'},
 80: {'PassengerId': 81,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Waelens, Mr. Achille',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '345767',
  'Fare': 9.0,
  'Cabin': nan,
  'Embarked': 'S'},
 81: {'PassengerId': 82,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sheerlinck, Mr. Jan Baptist',
  'Sex': 'male',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '345779',
  'Fare': 9.5,
  'Cabin': nan,
  'Embarked': 'S'},
 82: {'PassengerId': 83,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McDermott, Miss. Brigdet Delia',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330932',
  'Fare': 7.7875,
  'Cabin': nan,
  'Embarked': 'Q'},
 83: {'PassengerId': 84,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Carrau, Mr. Francisco M',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113059',
  'Fare': 47.1,
  'Cabin': nan,
  'Embarked': 'S'},
 84: {'PassengerId': 85,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Ilett, Miss. Bertha',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'SO/C 14885',
  'Fare': 10.5,
  'Cabin': nan,

### Adding a new element in dict : Column and value

In [14]:

# new_column = "Familly name"

# # New value for the new column
# new_value = "new_value"

# # Select the target dictionary based on the index
# target_dict = df_dictionary[index + 0]

# # Add the new key-value pair to the target dictionary
# target_dict[new_column] = new_value

### Adding a new column in all element in the dictionnary

In [15]:

# # New column name
# new_column = "Familly name"

# # New value for the new column
# new_value = "new_value"

# # Loop through each dictionary in the main dictionary
# for key, inner_dict in df_dictionary.items():
#     # Add the new key-value pair to the current dictionary
#     inner_dict[new_column] = new_value

# # Print the updated dictionary

In [16]:
df_dictionary

{0: {'PassengerId': 1,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Braund, Mr. Owen Harris',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'A/5 21171',
  'Fare': 7.25,
  'Cabin': nan,
  'Embarked': 'S'},
 1: {'PassengerId': 2,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17599',
  'Fare': 71.2833,
  'Cabin': 'C85',
  'Embarked': 'C'},
 2: {'PassengerId': 3,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Heikkinen, Miss. Laina',
  'Sex': 'female',
  'Age': 26.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'STON/O2. 3101282',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S'},
 3: {'PassengerId': 4,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
  'Sex': 'female',
  'Age': 35.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113803',
  'Fare': 53.1,
  'Cabin': 'C123',
  'Embarked': 'S'},
 4: {'PassengerId': 5,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Allen, Mr. William Henry',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '373450',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 5: {'PassengerId': 6,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moran, Mr. James',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330877',
  'Fare': 8.4583,
  'Cabin': nan,
  'Embarked': 'Q'},
 6: {'PassengerId': 7,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'McCarthy, Mr. Timothy J',
  'Sex': 'male',
  'Age': 54.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '17463',
  'Fare': 51.8625,
  'Cabin': 'E46',
  'Embarked': 'S'},
 7: {'PassengerId': 8,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson, Master. Gosta Leonard',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S'},
 8: {'PassengerId': 9,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '347742',
  'Fare': 11.1333,
  'Cabin': nan,
  'Embarked': 'S'},
 9: {'PassengerId': 10,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nasser, Mrs. Nicholas (Adele Achem)',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '237736',
  'Fare': 30.0708,
  'Cabin': nan,
  'Embarked': 'C'},
 10: {'PassengerId': 11,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sandstrom, Miss. Marguerite Rut',
  'Sex': 'female',
  'Age': 4.0,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': 'PP 9549',
  'Fare': 16.7,
  'Cabin': 'G6',
  'Embarked': 'S'},
 11: {'PassengerId': 12,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Bonnell, Miss. Elizabeth',
  'Sex': 'female',
  'Age': 58.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113783',
  'Fare': 26.55,
  'Cabin': 'C103',
  'Embarked': 'S'},
 12: {'PassengerId': 13,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Saundercock, Mr. William Henry',
  'Sex': 'male',
  'Age': 20.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/5. 2151',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 13: {'PassengerId': 14,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Andersson, Mr. Anders Johan',
  'Sex': 'male',
  'Age': 39.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347082',
  'Fare': 31.275,
  'Cabin': nan,
  'Embarked': 'S'},
 14: {'PassengerId': 15,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vestrom, Miss. Hulda Amanda Adolfina',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '350406',
  'Fare': 7.8542,
  'Cabin': nan,
  'Embarked': 'S'},
 15: {'PassengerId': 16,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Hewlett, Mrs. (Mary D Kingcome) ',
  'Sex': 'female',
  'Age': 55.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248706',
  'Fare': 16.0,
  'Cabin': nan,
  'Embarked': 'S'},
 16: {'PassengerId': 17,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rice, Master. Eugene',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '382652',
  'Fare': 29.125,
  'Cabin': nan,
  'Embarked': 'Q'},
 17: {'PassengerId': 18,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Williams, Mr. Charles Eugene',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '244373',
  'Fare': 13.0,
  'Cabin': nan,
  'Embarked': 'S'},
 18: {'PassengerId': 19,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
  'Sex': 'female',
  'Age': 31.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '345763',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S'},
 19: {'PassengerId': 20,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Masselmani, Mrs. Fatima',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2649',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C'},
 20: {'PassengerId': 21,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Fynney, Mr. Joseph J',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '239865',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S'},
 21: {'PassengerId': 22,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Beesley, Mr. Lawrence',
  'Sex': 'male',
  'Age': 34.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248698',
  'Fare': 13.0,
  'Cabin': 'D56',
  'Embarked': 'S'},
 22: {'PassengerId': 23,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McGowan, Miss. Anna "Annie"',
  'Sex': 'female',
  'Age': 15.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330923',
  'Fare': 8.0292,
  'Cabin': nan,
  'Embarked': 'Q'},
 23: {'PassengerId': 24,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Sloper, Mr. William Thompson',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113788',
  'Fare': 35.5,
  'Cabin': 'A6',
  'Embarked': 'S'},
 24: {'PassengerId': 25,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson, Miss. Torborg Danira',
  'Sex': 'female',
  'Age': 8.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S'},
 25: {'PassengerId': 26,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347077',
  'Fare': 31.3875,
  'Cabin': nan,
  'Embarked': 'S'},
 26: {'PassengerId': 27,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Emir, Mr. Farred Chehab',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2631',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C'},
 27: {'PassengerId': 28,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Fortune, Mr. Charles Alexander',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '19950',
  'Fare': 263.0,
  'Cabin': 'C23 C25 C27',
  'Embarked': 'S'},
 28: {'PassengerId': 29,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'O\'Dwyer, Miss. Ellen "Nellie"',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330959',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q'},
 29: {'PassengerId': 30,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Todoroff, Mr. Lalio',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349216',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S'},
 30: {'PassengerId': 31,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Uruchurtu, Don. Manuel E',
  'Sex': 'male',
  'Age': 40.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17601',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C'},
 31: {'PassengerId': 32,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Spencer, Mrs. William Augustus (Marie Eugenie)',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17569',
  'Fare': 146.5208,
  'Cabin': 'B78',
  'Embarked': 'C'},
 32: {'PassengerId': 33,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Glynn, Miss. Mary Agatha',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '335677',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q'},
 33: {'PassengerId': 34,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Wheadon, Mr. Edward H',
  'Sex': 'male',
  'Age': 66.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 24579',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 34: {'PassengerId': 35,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Meyer, Mr. Edgar Joseph',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17604',
  'Fare': 82.1708,
  'Cabin': nan,
  'Embarked': 'C'},
 35: {'PassengerId': 36,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Holverson, Mr. Alexander Oskar',
  'Sex': 'male',
  'Age': 42.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113789',
  'Fare': 52.0,
  'Cabin': nan,
  'Embarked': 'S'},
 36: {'PassengerId': 37,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Mamee, Mr. Hanna',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2677',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 37: {'PassengerId': 38,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Cann, Mr. Ernest Charles',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A./5. 2152',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 38: {'PassengerId': 39,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke, Miss. Augusta Maria',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '345764',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S'},
 39: {'PassengerId': 40,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Nicola-Yarred, Miss. Jamila',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2651',
  'Fare': 11.2417,
  'Cabin': nan,
  'Embarked': 'C'},
 40: {'PassengerId': 41,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  'Sex': 'female',
  'Age': 40.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '7546',
  'Fare': 9.475,
  'Cabin': nan,
  'Embarked': 'S'},
 41: {'PassengerId': 42,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '11668',
  'Fare': 21.0,
  'Cabin': nan,
  'Embarked': 'S'},
 42: {'PassengerId': 43,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kraeff, Mr. Theodor',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349253',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'C'},
 43: {'PassengerId': 44,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Laroche, Miss. Simonne Marie Anne Andree',
  'Sex': 'female',
  'Age': 3.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'SC/Paris 2123',
  'Fare': 41.5792,
  'Cabin': nan,
  'Embarked': 'C'},
 44: {'PassengerId': 45,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Devaney, Miss. Margaret Delia',
  'Sex': 'female',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330958',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q'},
 45: {'PassengerId': 46,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rogers, Mr. William John',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.C./A.4. 23567',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 46: {'PassengerId': 47,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Lennon, Mr. Denis',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '370371',
  'Fare': 15.5,
  'Cabin': nan,
  'Embarked': 'Q'},
 47: {'PassengerId': 48,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Driscoll, Miss. Bridget",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '14311',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q'},
 48: {'PassengerId': 49,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Samaan, Mr. Youssef',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '2662',
  'Fare': 21.6792,
  'Cabin': nan,
  'Embarked': 'C'},
 49: {'PassengerId': 50,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '349237',
  'Fare': 17.8,
  'Cabin': nan,
  'Embarked': 'S'},
 50: {'PassengerId': 51,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Panula, Master. Juha Niilo',
  'Sex': 'male',
  'Age': 7.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '3101295',
  'Fare': 39.6875,
  'Cabin': nan,
  'Embarked': 'S'},
 51: {'PassengerId': 52,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Nosworthy, Mr. Richard Cater',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/4. 39886',
  'Fare': 7.8,
  'Cabin': nan,
  'Embarked': 'S'},
 52: {'PassengerId': 53,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
  'Sex': 'female',
  'Age': 49.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17572',
  'Fare': 76.7292,
  'Cabin': 'D33',
  'Embarked': 'C'},
 53: {'PassengerId': 54,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2926',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S'},
 54: {'PassengerId': 55,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Ostby, Mr. Engelhart Cornelius',
  'Sex': 'male',
  'Age': 65.0,
  'SibSp': 0,
  'Parch': 1,
  'Ticket': '113509',
  'Fare': 61.9792,
  'Cabin': 'B30',
  'Embarked': 'C'},
 55: {'PassengerId': 56,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Woolner, Mr. Hugh',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '19947',
  'Fare': 35.5,
  'Cabin': 'C52',
  'Embarked': 'S'},
 56: {'PassengerId': 57,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Rugg, Miss. Emily',
  'Sex': 'female',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 31026',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 57: {'PassengerId': 58,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Novel, Mr. Mansouer',
  'Sex': 'male',
  'Age': 28.5,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2697',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 58: {'PassengerId': 59,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'West, Miss. Constance Mirium',
  'Sex': 'female',
  'Age': 5.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'C.A. 34651',
  'Fare': 27.75,
  'Cabin': nan,
  'Embarked': 'S'},
 59: {'PassengerId': 60,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin, Master. William Frederick',
  'Sex': 'male',
  'Age': 11.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S'},
 60: {'PassengerId': 61,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Sirayanian, Mr. Orsen',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2669',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C'},
 61: {'PassengerId': 62,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Icard, Miss. Amelie',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113572',
  'Fare': 80.0,
  'Cabin': 'B28',
  'Embarked': nan},
 62: {'PassengerId': 63,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Harris, Mr. Henry Birkhardt',
  'Sex': 'male',
  'Age': 45.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '36973',
  'Fare': 83.475,
  'Cabin': 'C83',
  'Embarked': 'S'},
 63: {'PassengerId': 64,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Skoog, Master. Harald',
  'Sex': 'male',
  'Age': 4.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '347088',
  'Fare': 27.9,
  'Cabin': nan,
  'Embarked': 'S'},
 64: {'PassengerId': 65,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Stewart, Mr. Albert A',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17605',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C'},
 65: {'PassengerId': 66,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Moubarek, Master. Gerios',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': '2661',
  'Fare': 15.2458,
  'Cabin': nan,
  'Embarked': 'C'},
 66: {'PassengerId': 67,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nye, Mrs. (Elizabeth Ramell)',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 29395',
  'Fare': 10.5,
  'Cabin': 'F33',
  'Embarked': 'S'},
 67: {'PassengerId': 68,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Crease, Mr. Ernest James',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.P. 3464',
  'Fare': 8.1583,
  'Cabin': nan,
  'Embarked': 'S'},
 68: {'PassengerId': 69,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Andersson, Miss. Erna Alexandra',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 4,
  'Parch': 2,
  'Ticket': '3101281',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S'},
 69: {'PassengerId': 70,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kink, Mr. Vincenz',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '315151',
  'Fare': 8.6625,
  'Cabin': nan,
  'Embarked': 'S'},
 70: {'PassengerId': 71,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Jenkin, Mr. Stephen Curnow',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 33111',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S'},
 71: {'PassengerId': 72,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin, Miss. Lillian Amy',
  'Sex': 'female',
  'Age': 16.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S'},
 72: {'PassengerId': 73,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Hood, Mr. Ambrose Jr',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.O.C. 14879',
  'Fare': 73.5,
  'Cabin': nan,
  'Embarked': 'S'},
 73: {'PassengerId': 74,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Chronopoulos, Mr. Apostolos',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2680',
  'Fare': 14.4542,
  'Cabin': nan,
  'Embarked': 'C'},
 74: {'PassengerId': 75,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Bing, Mr. Lee',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '1601',
  'Fare': 56.4958,
  'Cabin': nan,
  'Embarked': 'S'},
 75: {'PassengerId': 76,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moen, Mr. Sigurd Hansen',
  'Sex': 'male',
  'Age': 25.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '348123',
  'Fare': 7.65,
  'Cabin': 'F G73',
  'Embarked': 'S'},
 76: {'PassengerId': 77,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Staneff, Mr. Ivan',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349208',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S'},
 77: {'PassengerId': 78,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moutal, Mr. Rahamin Haim',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '374746',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S'},
 78: {'PassengerId': 79,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Caldwell, Master. Alden Gates',
  'Sex': 'male',
  'Age': 0.83,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '248738',
  'Fare': 29.0,
  'Cabin': nan,
  'Embarked': 'S'},
 79: {'PassengerId': 80,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Dowdell, Miss. Elizabeth',
  'Sex': 'female',
  'Age': 30.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '364516',
  'Fare': 12.475,
  'Cabin': nan,
  'Embarked': 'S'},
 80: {'PassengerId': 81,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Waelens, Mr. Achille',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '345767',
  'Fare': 9.0,
  'Cabin': nan,
  'Embarked': 'S'},
 81: {'PassengerId': 82,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sheerlinck, Mr. Jan Baptist',
  'Sex': 'male',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '345779',
  'Fare': 9.5,
  'Cabin': nan,
  'Embarked': 'S'},
 82: {'PassengerId': 83,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McDermott, Miss. Brigdet Delia',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330932',
  'Fare': 7.7875,
  'Cabin': nan,
  'Embarked': 'Q'},
 83: {'PassengerId': 84,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Carrau, Mr. Francisco M',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113059',
  'Fare': 47.1,
  'Cabin': nan,
  'Embarked': 'S'},
 84: {'PassengerId': 85,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Ilett, Miss. Bertha',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'SO/C 14885',
  'Fare': 10.5,
  'Cabin': nan,

### Split element and create a new column

In [17]:


# Column to split
column_to_split = "Name"

# Separator for splitting
separator = ","

# New column name
new_column = "First name"

# Loop through each inner dictionary
for key, inner_dict in df_dictionary.items():
    # Split the value of the specified column
    split_values = inner_dict[column_to_split].split(separator)

    # Assign the first split value to the original column
    inner_dict[column_to_split] = split_values[0]

    # Create the new column and assign the second split value
    inner_dict[new_column] = split_values[1]

# Print the updated dictionary
df_dictionary

{0: {'PassengerId': 1,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Braund',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'A/5 21171',
  'Fare': 7.25,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Owen Harris'},
 1: {'PassengerId': 2,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Cumings',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17599',
  'Fare': 71.2833,
  'Cabin': 'C85',
  'Embarked': 'C',
  'First name': ' Mrs. John Bradley (Florence Briggs Thayer)'},
 2: {'PassengerId': 3,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Heikkinen',
  'Sex': 'female',
  'Age': 26.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'STON/O2. 3101282',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Laina'},
 3: {'PassengerId': 4,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Futrelle',
  'Sex': 'female',
  'Age': 35.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113803',
  'Fare': 53.1,
  'Cabin': 'C123',
  'Embarked': 'S',
  'First name': ' Mrs. Jacques Heath (Lily May Peel)'},
 4: {'PassengerId': 5,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Allen',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '373450',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. William Henry'},
 5: {'PassengerId': 6,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moran',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330877',
  'Fare': 8.4583,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Mr. James'},
 6: {'PassengerId': 7,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'McCarthy',
  'Sex': 'male',
  'Age': 54.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '17463',
  'Fare': 51.8625,
  'Cabin': 'E46',
  'Embarked': 'S',
  'First name': ' Mr. Timothy J'},
 7: {'PassengerId': 8,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Gosta Leonard'},
 8: {'PassengerId': 9,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Johnson',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '347742',
  'Fare': 11.1333,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Oscar W (Elisabeth Vilhelmina Berg)'},
 9: {'PassengerId': 10,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nasser',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '237736',
  'Fare': 30.0708,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mrs. Nicholas (Adele Achem)'},
 10: {'PassengerId': 11,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sandstrom',
  'Sex': 'female',
  'Age': 4.0,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': 'PP 9549',
  'Fare': 16.7,
  'Cabin': 'G6',
  'Embarked': 'S',
  'First name': ' Miss. Marguerite Rut'},
 11: {'PassengerId': 12,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Bonnell',
  'Sex': 'female',
  'Age': 58.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113783',
  'Fare': 26.55,
  'Cabin': 'C103',
  'Embarked': 'S',
  'First name': ' Miss. Elizabeth'},
 12: {'PassengerId': 13,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Saundercock',
  'Sex': 'male',
  'Age': 20.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/5. 2151',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. William Henry'},
 13: {'PassengerId': 14,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Andersson',
  'Sex': 'male',
  'Age': 39.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347082',
  'Fare': 31.275,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Anders Johan'},
 14: {'PassengerId': 15,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vestrom',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '350406',
  'Fare': 7.8542,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Hulda Amanda Adolfina'},
 15: {'PassengerId': 16,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Hewlett',
  'Sex': 'female',
  'Age': 55.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248706',
  'Fare': 16.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. (Mary D Kingcome) '},
 16: {'PassengerId': 17,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rice',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '382652',
  'Fare': 29.125,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Master. Eugene'},
 17: {'PassengerId': 18,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Williams',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '244373',
  'Fare': 13.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Charles Eugene'},
 18: {'PassengerId': 19,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke',
  'Sex': 'female',
  'Age': 31.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '345763',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Julius (Emelia Maria Vandemoortele)'},
 19: {'PassengerId': 20,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Masselmani',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2649',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mrs. Fatima'},
 20: {'PassengerId': 21,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Fynney',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '239865',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Joseph J'},
 21: {'PassengerId': 22,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Beesley',
  'Sex': 'male',
  'Age': 34.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248698',
  'Fare': 13.0,
  'Cabin': 'D56',
  'Embarked': 'S',
  'First name': ' Mr. Lawrence'},
 22: {'PassengerId': 23,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McGowan',
  'Sex': 'female',
  'Age': 15.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330923',
  'Fare': 8.0292,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Anna "Annie"'},
 23: {'PassengerId': 24,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Sloper',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113788',
  'Fare': 35.5,
  'Cabin': 'A6',
  'Embarked': 'S',
  'First name': ' Mr. William Thompson'},
 24: {'PassengerId': 25,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson',
  'Sex': 'female',
  'Age': 8.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Torborg Danira'},
 25: {'PassengerId': 26,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Asplund',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347077',
  'Fare': 31.3875,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'},
 26: {'PassengerId': 27,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Emir',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2631',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Farred Chehab'},
 27: {'PassengerId': 28,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Fortune',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '19950',
  'Fare': 263.0,
  'Cabin': 'C23 C25 C27',
  'Embarked': 'S',
  'First name': ' Mr. Charles Alexander'},
 28: {'PassengerId': 29,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Dwyer",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330959',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Ellen "Nellie"'},
 29: {'PassengerId': 30,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Todoroff',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349216',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Lalio'},
 30: {'PassengerId': 31,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Uruchurtu',
  'Sex': 'male',
  'Age': 40.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17601',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Don. Manuel E'},
 31: {'PassengerId': 32,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Spencer',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17569',
  'Fare': 146.5208,
  'Cabin': 'B78',
  'Embarked': 'C',
  'First name': ' Mrs. William Augustus (Marie Eugenie)'},
 32: {'PassengerId': 33,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Glynn',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '335677',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Mary Agatha'},
 33: {'PassengerId': 34,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Wheadon',
  'Sex': 'male',
  'Age': 66.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 24579',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Edward H'},
 34: {'PassengerId': 35,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Meyer',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17604',
  'Fare': 82.1708,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Edgar Joseph'},
 35: {'PassengerId': 36,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Holverson',
  'Sex': 'male',
  'Age': 42.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113789',
  'Fare': 52.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Alexander Oskar'},
 36: {'PassengerId': 37,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Mamee',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2677',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Hanna'},
 37: {'PassengerId': 38,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Cann',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A./5. 2152',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ernest Charles'},
 38: {'PassengerId': 39,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '345764',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Augusta Maria'},
 39: {'PassengerId': 40,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Nicola-Yarred',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2651',
  'Fare': 11.2417,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Miss. Jamila'},
 40: {'PassengerId': 41,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Ahlin',
  'Sex': 'female',
  'Age': 40.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '7546',
  'Fare': 9.475,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Johan (Johanna Persdotter Larsson)'},
 41: {'PassengerId': 42,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Turpin',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '11668',
  'Fare': 21.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. William John Robert (Dorothy Ann Wonnacott)'},
 42: {'PassengerId': 43,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kraeff',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349253',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Theodor'},
 43: {'PassengerId': 44,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Laroche',
  'Sex': 'female',
  'Age': 3.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'SC/Paris 2123',
  'Fare': 41.5792,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Miss. Simonne Marie Anne Andree'},
 44: {'PassengerId': 45,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Devaney',
  'Sex': 'female',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330958',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Margaret Delia'},
 45: {'PassengerId': 46,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rogers',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.C./A.4. 23567',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. William John'},
 46: {'PassengerId': 47,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Lennon',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '370371',
  'Fare': 15.5,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Mr. Denis'},
 47: {'PassengerId': 48,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Driscoll",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '14311',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Bridget'},
 48: {'PassengerId': 49,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Samaan',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '2662',
  'Fare': 21.6792,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Youssef'},
 49: {'PassengerId': 50,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Arnold-Franchi',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '349237',
  'Fare': 17.8,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Josef (Josefine Franchi)'},
 50: {'PassengerId': 51,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Panula',
  'Sex': 'male',
  'Age': 7.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '3101295',
  'Fare': 39.6875,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Juha Niilo'},
 51: {'PassengerId': 52,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Nosworthy',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/4. 39886',
  'Fare': 7.8,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Richard Cater'},
 52: {'PassengerId': 53,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Harper',
  'Sex': 'female',
  'Age': 49.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17572',
  'Fare': 76.7292,
  'Cabin': 'D33',
  'Embarked': 'C',
  'First name': ' Mrs. Henry Sleeper (Myna Haxtun)'},
 53: {'PassengerId': 54,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Faunthorpe',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2926',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Lizzie (Elizabeth Anne Wilkinson)'},
 54: {'PassengerId': 55,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Ostby',
  'Sex': 'male',
  'Age': 65.0,
  'SibSp': 0,
  'Parch': 1,
  'Ticket': '113509',
  'Fare': 61.9792,
  'Cabin': 'B30',
  'Embarked': 'C',
  'First name': ' Mr. Engelhart Cornelius'},
 55: {'PassengerId': 56,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Woolner',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '19947',
  'Fare': 35.5,
  'Cabin': 'C52',
  'Embarked': 'S',
  'First name': ' Mr. Hugh'},
 56: {'PassengerId': 57,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Rugg',
  'Sex': 'female',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 31026',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Emily'},
 57: {'PassengerId': 58,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Novel',
  'Sex': 'male',
  'Age': 28.5,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2697',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Mansouer'},
 58: {'PassengerId': 59,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'West',
  'Sex': 'female',
  'Age': 5.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'C.A. 34651',
  'Fare': 27.75,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Constance Mirium'},
 59: {'PassengerId': 60,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin',
  'Sex': 'male',
  'Age': 11.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. William Frederick'},
 60: {'PassengerId': 61,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Sirayanian',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2669',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Orsen'},
 61: {'PassengerId': 62,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Icard',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113572',
  'Fare': 80.0,
  'Cabin': 'B28',
  'Embarked': nan,
  'First name': ' Miss. Amelie'},
 62: {'PassengerId': 63,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Harris',
  'Sex': 'male',
  'Age': 45.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '36973',
  'Fare': 83.475,
  'Cabin': 'C83',
  'Embarked': 'S',
  'First name': ' Mr. Henry Birkhardt'},
 63: {'PassengerId': 64,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Skoog',
  'Sex': 'male',
  'Age': 4.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '347088',
  'Fare': 27.9,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Harald'},
 64: {'PassengerId': 65,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Stewart',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17605',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Albert A'},
 65: {'PassengerId': 66,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Moubarek',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': '2661',
  'Fare': 15.2458,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Master. Gerios'},
 66: {'PassengerId': 67,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nye',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 29395',
  'Fare': 10.5,
  'Cabin': 'F33',
  'Embarked': 'S',
  'First name': ' Mrs. (Elizabeth Ramell)'},
 67: {'PassengerId': 68,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Crease',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.P. 3464',
  'Fare': 8.1583,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ernest James'},
 68: {'PassengerId': 69,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Andersson',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 4,
  'Parch': 2,
  'Ticket': '3101281',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Erna Alexandra'},
 69: {'PassengerId': 70,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kink',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '315151',
  'Fare': 8.6625,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Vincenz'},
 70: {'PassengerId': 71,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Jenkin',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 33111',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Stephen Curnow'},
 71: {'PassengerId': 72,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin',
  'Sex': 'female',
  'Age': 16.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Lillian Amy'},
 72: {'PassengerId': 73,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Hood',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.O.C. 14879',
  'Fare': 73.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ambrose Jr'},
 73: {'PassengerId': 74,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Chronopoulos',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2680',
  'Fare': 14.4542,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Apostolos'},
 74: {'PassengerId': 75,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Bing',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '1601',
  'Fare': 56.4958,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Lee'},
 75: {'PassengerId': 76,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moen',
  'Sex': 'male',
  'Age': 25.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '348123',
  'Fare': 7.65,
  'Cabin': 'F G73',
  'Embarked': 'S',
  'First name': ' Mr. Sigurd Hansen'},
 76: {'PassengerId': 77,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Staneff',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349208',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ivan'},
 77: {'PassengerId': 78,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moutal',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '374746',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Rahamin Haim'},
 78: {'PassengerId': 79,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Caldwell',
  'Sex': 'male',
  'Age': 0.83,

### replace element in a dictionary

In [18]:
# Key, subkey, and new value
key = 0
subkey = "Name"
new_value = "Braundo"

# Directly replace the value of the subkey within the inner dictionary
df_dictionary[key][subkey] = new_value

In [19]:
df_dictionary

{0: {'PassengerId': 1,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Braundo',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'A/5 21171',
  'Fare': 7.25,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Owen Harris'},
 1: {'PassengerId': 2,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Cumings',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17599',
  'Fare': 71.2833,
  'Cabin': 'C85',
  'Embarked': 'C',
  'First name': ' Mrs. John Bradley (Florence Briggs Thayer)'},
 2: {'PassengerId': 3,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Heikkinen',
  'Sex': 'female',
  'Age': 26.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'STON/O2. 3101282',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Laina'},
 3: {'PassengerId': 4,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Futrelle',
  'Sex': 'female',
  'Age': 35.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113803',
  'Fare': 53.1,
  'Cabin': 'C123',
  'Embarked': 'S',
  'First name': ' Mrs. Jacques Heath (Lily May Peel)'},
 4: {'PassengerId': 5,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Allen',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '373450',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. William Henry'},
 5: {'PassengerId': 6,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moran',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330877',
  'Fare': 8.4583,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Mr. James'},
 6: {'PassengerId': 7,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'McCarthy',
  'Sex': 'male',
  'Age': 54.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '17463',
  'Fare': 51.8625,
  'Cabin': 'E46',
  'Embarked': 'S',
  'First name': ' Mr. Timothy J'},
 7: {'PassengerId': 8,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Gosta Leonard'},
 8: {'PassengerId': 9,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Johnson',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '347742',
  'Fare': 11.1333,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Oscar W (Elisabeth Vilhelmina Berg)'},
 9: {'PassengerId': 10,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nasser',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '237736',
  'Fare': 30.0708,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mrs. Nicholas (Adele Achem)'},
 10: {'PassengerId': 11,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sandstrom',
  'Sex': 'female',
  'Age': 4.0,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': 'PP 9549',
  'Fare': 16.7,
  'Cabin': 'G6',
  'Embarked': 'S',
  'First name': ' Miss. Marguerite Rut'},
 11: {'PassengerId': 12,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Bonnell',
  'Sex': 'female',
  'Age': 58.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113783',
  'Fare': 26.55,
  'Cabin': 'C103',
  'Embarked': 'S',
  'First name': ' Miss. Elizabeth'},
 12: {'PassengerId': 13,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Saundercock',
  'Sex': 'male',
  'Age': 20.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/5. 2151',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. William Henry'},
 13: {'PassengerId': 14,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Andersson',
  'Sex': 'male',
  'Age': 39.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347082',
  'Fare': 31.275,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Anders Johan'},
 14: {'PassengerId': 15,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vestrom',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '350406',
  'Fare': 7.8542,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Hulda Amanda Adolfina'},
 15: {'PassengerId': 16,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Hewlett',
  'Sex': 'female',
  'Age': 55.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248706',
  'Fare': 16.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. (Mary D Kingcome) '},
 16: {'PassengerId': 17,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rice',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '382652',
  'Fare': 29.125,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Master. Eugene'},
 17: {'PassengerId': 18,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Williams',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '244373',
  'Fare': 13.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Charles Eugene'},
 18: {'PassengerId': 19,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke',
  'Sex': 'female',
  'Age': 31.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '345763',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Julius (Emelia Maria Vandemoortele)'},
 19: {'PassengerId': 20,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Masselmani',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2649',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mrs. Fatima'},
 20: {'PassengerId': 21,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Fynney',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '239865',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Joseph J'},
 21: {'PassengerId': 22,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Beesley',
  'Sex': 'male',
  'Age': 34.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248698',
  'Fare': 13.0,
  'Cabin': 'D56',
  'Embarked': 'S',
  'First name': ' Mr. Lawrence'},
 22: {'PassengerId': 23,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McGowan',
  'Sex': 'female',
  'Age': 15.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330923',
  'Fare': 8.0292,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Anna "Annie"'},
 23: {'PassengerId': 24,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Sloper',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113788',
  'Fare': 35.5,
  'Cabin': 'A6',
  'Embarked': 'S',
  'First name': ' Mr. William Thompson'},
 24: {'PassengerId': 25,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson',
  'Sex': 'female',
  'Age': 8.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Torborg Danira'},
 25: {'PassengerId': 26,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Asplund',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347077',
  'Fare': 31.3875,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'},
 26: {'PassengerId': 27,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Emir',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2631',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Farred Chehab'},
 27: {'PassengerId': 28,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Fortune',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '19950',
  'Fare': 263.0,
  'Cabin': 'C23 C25 C27',
  'Embarked': 'S',
  'First name': ' Mr. Charles Alexander'},
 28: {'PassengerId': 29,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Dwyer",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330959',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Ellen "Nellie"'},
 29: {'PassengerId': 30,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Todoroff',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349216',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Lalio'},
 30: {'PassengerId': 31,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Uruchurtu',
  'Sex': 'male',
  'Age': 40.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17601',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Don. Manuel E'},
 31: {'PassengerId': 32,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Spencer',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17569',
  'Fare': 146.5208,
  'Cabin': 'B78',
  'Embarked': 'C',
  'First name': ' Mrs. William Augustus (Marie Eugenie)'},
 32: {'PassengerId': 33,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Glynn',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '335677',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Mary Agatha'},
 33: {'PassengerId': 34,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Wheadon',
  'Sex': 'male',
  'Age': 66.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 24579',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Edward H'},
 34: {'PassengerId': 35,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Meyer',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17604',
  'Fare': 82.1708,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Edgar Joseph'},
 35: {'PassengerId': 36,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Holverson',
  'Sex': 'male',
  'Age': 42.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113789',
  'Fare': 52.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Alexander Oskar'},
 36: {'PassengerId': 37,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Mamee',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2677',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Hanna'},
 37: {'PassengerId': 38,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Cann',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A./5. 2152',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ernest Charles'},
 38: {'PassengerId': 39,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '345764',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Augusta Maria'},
 39: {'PassengerId': 40,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Nicola-Yarred',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2651',
  'Fare': 11.2417,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Miss. Jamila'},
 40: {'PassengerId': 41,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Ahlin',
  'Sex': 'female',
  'Age': 40.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '7546',
  'Fare': 9.475,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Johan (Johanna Persdotter Larsson)'},
 41: {'PassengerId': 42,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Turpin',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '11668',
  'Fare': 21.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. William John Robert (Dorothy Ann Wonnacott)'},
 42: {'PassengerId': 43,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kraeff',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349253',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Theodor'},
 43: {'PassengerId': 44,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Laroche',
  'Sex': 'female',
  'Age': 3.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'SC/Paris 2123',
  'Fare': 41.5792,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Miss. Simonne Marie Anne Andree'},
 44: {'PassengerId': 45,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Devaney',
  'Sex': 'female',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330958',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Margaret Delia'},
 45: {'PassengerId': 46,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rogers',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.C./A.4. 23567',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. William John'},
 46: {'PassengerId': 47,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Lennon',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '370371',
  'Fare': 15.5,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Mr. Denis'},
 47: {'PassengerId': 48,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Driscoll",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '14311',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Bridget'},
 48: {'PassengerId': 49,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Samaan',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '2662',
  'Fare': 21.6792,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Youssef'},
 49: {'PassengerId': 50,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Arnold-Franchi',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '349237',
  'Fare': 17.8,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Josef (Josefine Franchi)'},
 50: {'PassengerId': 51,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Panula',
  'Sex': 'male',
  'Age': 7.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '3101295',
  'Fare': 39.6875,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Juha Niilo'},
 51: {'PassengerId': 52,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Nosworthy',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/4. 39886',
  'Fare': 7.8,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Richard Cater'},
 52: {'PassengerId': 53,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Harper',
  'Sex': 'female',
  'Age': 49.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17572',
  'Fare': 76.7292,
  'Cabin': 'D33',
  'Embarked': 'C',
  'First name': ' Mrs. Henry Sleeper (Myna Haxtun)'},
 53: {'PassengerId': 54,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Faunthorpe',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2926',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Lizzie (Elizabeth Anne Wilkinson)'},
 54: {'PassengerId': 55,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Ostby',
  'Sex': 'male',
  'Age': 65.0,
  'SibSp': 0,
  'Parch': 1,
  'Ticket': '113509',
  'Fare': 61.9792,
  'Cabin': 'B30',
  'Embarked': 'C',
  'First name': ' Mr. Engelhart Cornelius'},
 55: {'PassengerId': 56,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Woolner',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '19947',
  'Fare': 35.5,
  'Cabin': 'C52',
  'Embarked': 'S',
  'First name': ' Mr. Hugh'},
 56: {'PassengerId': 57,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Rugg',
  'Sex': 'female',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 31026',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Emily'},
 57: {'PassengerId': 58,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Novel',
  'Sex': 'male',
  'Age': 28.5,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2697',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Mansouer'},
 58: {'PassengerId': 59,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'West',
  'Sex': 'female',
  'Age': 5.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'C.A. 34651',
  'Fare': 27.75,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Constance Mirium'},
 59: {'PassengerId': 60,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin',
  'Sex': 'male',
  'Age': 11.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. William Frederick'},
 60: {'PassengerId': 61,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Sirayanian',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2669',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Orsen'},
 61: {'PassengerId': 62,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Icard',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113572',
  'Fare': 80.0,
  'Cabin': 'B28',
  'Embarked': nan,
  'First name': ' Miss. Amelie'},
 62: {'PassengerId': 63,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Harris',
  'Sex': 'male',
  'Age': 45.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '36973',
  'Fare': 83.475,
  'Cabin': 'C83',
  'Embarked': 'S',
  'First name': ' Mr. Henry Birkhardt'},
 63: {'PassengerId': 64,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Skoog',
  'Sex': 'male',
  'Age': 4.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '347088',
  'Fare': 27.9,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Harald'},
 64: {'PassengerId': 65,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Stewart',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17605',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Albert A'},
 65: {'PassengerId': 66,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Moubarek',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': '2661',
  'Fare': 15.2458,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Master. Gerios'},
 66: {'PassengerId': 67,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nye',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 29395',
  'Fare': 10.5,
  'Cabin': 'F33',
  'Embarked': 'S',
  'First name': ' Mrs. (Elizabeth Ramell)'},
 67: {'PassengerId': 68,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Crease',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.P. 3464',
  'Fare': 8.1583,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ernest James'},
 68: {'PassengerId': 69,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Andersson',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 4,
  'Parch': 2,
  'Ticket': '3101281',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Erna Alexandra'},
 69: {'PassengerId': 70,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kink',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '315151',
  'Fare': 8.6625,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Vincenz'},
 70: {'PassengerId': 71,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Jenkin',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 33111',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Stephen Curnow'},
 71: {'PassengerId': 72,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin',
  'Sex': 'female',
  'Age': 16.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Lillian Amy'},
 72: {'PassengerId': 73,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Hood',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.O.C. 14879',
  'Fare': 73.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ambrose Jr'},
 73: {'PassengerId': 74,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Chronopoulos',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2680',
  'Fare': 14.4542,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Apostolos'},
 74: {'PassengerId': 75,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Bing',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '1601',
  'Fare': 56.4958,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Lee'},
 75: {'PassengerId': 76,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moen',
  'Sex': 'male',
  'Age': 25.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '348123',
  'Fare': 7.65,
  'Cabin': 'F G73',
  'Embarked': 'S',
  'First name': ' Mr. Sigurd Hansen'},
 76: {'PassengerId': 77,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Staneff',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349208',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ivan'},
 77: {'PassengerId': 78,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moutal',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '374746',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Rahamin Haim'},
 78: {'PassengerId': 79,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Caldwell',
  'Sex': 'male',
  'Age': 0.83,

### Delete a key

In [20]:

# Key to delete
key_to_delete = 1
# Delete the key
del df_dictionary[key_to_delete]

df_dictionary

{0: {'PassengerId': 1,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Braundo',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'A/5 21171',
  'Fare': 7.25,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Owen Harris'},
 2: {'PassengerId': 3,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Heikkinen',
  'Sex': 'female',
  'Age': 26.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'STON/O2. 3101282',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Laina'},
 3: {'PassengerId': 4,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Futrelle',
  'Sex': 'female',
  'Age': 35.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113803',
  'Fare': 53.1,
  'Cabin': 'C123',
  'Embarked': 'S',
  'First name': ' Mrs. Jacques Heath (Lily May Peel)'},
 4: {'PassengerId': 5,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Allen',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '373450',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. William Henry'},
 5: {'PassengerId': 6,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moran',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330877',
  'Fare': 8.4583,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Mr. James'},
 6: {'PassengerId': 7,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'McCarthy',
  'Sex': 'male',
  'Age': 54.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '17463',
  'Fare': 51.8625,
  'Cabin': 'E46',
  'Embarked': 'S',
  'First name': ' Mr. Timothy J'},
 7: {'PassengerId': 8,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Gosta Leonard'},
 8: {'PassengerId': 9,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Johnson',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '347742',
  'Fare': 11.1333,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Oscar W (Elisabeth Vilhelmina Berg)'},
 9: {'PassengerId': 10,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nasser',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '237736',
  'Fare': 30.0708,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mrs. Nicholas (Adele Achem)'},
 10: {'PassengerId': 11,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Sandstrom',
  'Sex': 'female',
  'Age': 4.0,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': 'PP 9549',
  'Fare': 16.7,
  'Cabin': 'G6',
  'Embarked': 'S',
  'First name': ' Miss. Marguerite Rut'},
 11: {'PassengerId': 12,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Bonnell',
  'Sex': 'female',
  'Age': 58.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113783',
  'Fare': 26.55,
  'Cabin': 'C103',
  'Embarked': 'S',
  'First name': ' Miss. Elizabeth'},
 12: {'PassengerId': 13,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Saundercock',
  'Sex': 'male',
  'Age': 20.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/5. 2151',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. William Henry'},
 13: {'PassengerId': 14,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Andersson',
  'Sex': 'male',
  'Age': 39.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347082',
  'Fare': 31.275,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Anders Johan'},
 14: {'PassengerId': 15,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vestrom',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '350406',
  'Fare': 7.8542,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Hulda Amanda Adolfina'},
 15: {'PassengerId': 16,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Hewlett',
  'Sex': 'female',
  'Age': 55.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248706',
  'Fare': 16.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. (Mary D Kingcome) '},
 16: {'PassengerId': 17,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rice',
  'Sex': 'male',
  'Age': 2.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '382652',
  'Fare': 29.125,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Master. Eugene'},
 17: {'PassengerId': 18,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Williams',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '244373',
  'Fare': 13.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Charles Eugene'},
 18: {'PassengerId': 19,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke',
  'Sex': 'female',
  'Age': 31.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '345763',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Julius (Emelia Maria Vandemoortele)'},
 19: {'PassengerId': 20,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Masselmani',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2649',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mrs. Fatima'},
 20: {'PassengerId': 21,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Fynney',
  'Sex': 'male',
  'Age': 35.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '239865',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Joseph J'},
 21: {'PassengerId': 22,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Beesley',
  'Sex': 'male',
  'Age': 34.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '248698',
  'Fare': 13.0,
  'Cabin': 'D56',
  'Embarked': 'S',
  'First name': ' Mr. Lawrence'},
 22: {'PassengerId': 23,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'McGowan',
  'Sex': 'female',
  'Age': 15.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330923',
  'Fare': 8.0292,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Anna "Annie"'},
 23: {'PassengerId': 24,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Sloper',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113788',
  'Fare': 35.5,
  'Cabin': 'A6',
  'Embarked': 'S',
  'First name': ' Mr. William Thompson'},
 24: {'PassengerId': 25,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Palsson',
  'Sex': 'female',
  'Age': 8.0,
  'SibSp': 3,
  'Parch': 1,
  'Ticket': '349909',
  'Fare': 21.075,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Torborg Danira'},
 25: {'PassengerId': 26,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Asplund',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 1,
  'Parch': 5,
  'Ticket': '347077',
  'Fare': 31.3875,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'},
 26: {'PassengerId': 27,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Emir',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2631',
  'Fare': 7.225,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Farred Chehab'},
 27: {'PassengerId': 28,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Fortune',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '19950',
  'Fare': 263.0,
  'Cabin': 'C23 C25 C27',
  'Embarked': 'S',
  'First name': ' Mr. Charles Alexander'},
 28: {'PassengerId': 29,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Dwyer",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330959',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Ellen "Nellie"'},
 29: {'PassengerId': 30,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Todoroff',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349216',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Lalio'},
 30: {'PassengerId': 31,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Uruchurtu',
  'Sex': 'male',
  'Age': 40.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17601',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Don. Manuel E'},
 31: {'PassengerId': 32,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Spencer',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17569',
  'Fare': 146.5208,
  'Cabin': 'B78',
  'Embarked': 'C',
  'First name': ' Mrs. William Augustus (Marie Eugenie)'},
 32: {'PassengerId': 33,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Glynn',
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '335677',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Mary Agatha'},
 33: {'PassengerId': 34,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Wheadon',
  'Sex': 'male',
  'Age': 66.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 24579',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Edward H'},
 34: {'PassengerId': 35,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Meyer',
  'Sex': 'male',
  'Age': 28.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17604',
  'Fare': 82.1708,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Edgar Joseph'},
 35: {'PassengerId': 36,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Holverson',
  'Sex': 'male',
  'Age': 42.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '113789',
  'Fare': 52.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Alexander Oskar'},
 36: {'PassengerId': 37,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Mamee',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2677',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Hanna'},
 37: {'PassengerId': 38,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Cann',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A./5. 2152',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ernest Charles'},
 38: {'PassengerId': 39,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Vander Planke',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '345764',
  'Fare': 18.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Augusta Maria'},
 39: {'PassengerId': 40,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Nicola-Yarred',
  'Sex': 'female',
  'Age': 14.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2651',
  'Fare': 11.2417,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Miss. Jamila'},
 40: {'PassengerId': 41,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Ahlin',
  'Sex': 'female',
  'Age': 40.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '7546',
  'Fare': 9.475,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Johan (Johanna Persdotter Larsson)'},
 41: {'PassengerId': 42,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Turpin',
  'Sex': 'female',
  'Age': 27.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '11668',
  'Fare': 21.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. William John Robert (Dorothy Ann Wonnacott)'},
 42: {'PassengerId': 43,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kraeff',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349253',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Theodor'},
 43: {'PassengerId': 44,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Laroche',
  'Sex': 'female',
  'Age': 3.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'SC/Paris 2123',
  'Fare': 41.5792,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Miss. Simonne Marie Anne Andree'},
 44: {'PassengerId': 45,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Devaney',
  'Sex': 'female',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '330958',
  'Fare': 7.8792,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Margaret Delia'},
 45: {'PassengerId': 46,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Rogers',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.C./A.4. 23567',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. William John'},
 46: {'PassengerId': 47,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Lennon',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '370371',
  'Fare': 15.5,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Mr. Denis'},
 47: {'PassengerId': 48,
  'Survived': 1,
  'Pclass': 3,
  'Name': "O'Driscoll",
  'Sex': 'female',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '14311',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q',
  'First name': ' Miss. Bridget'},
 48: {'PassengerId': 49,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Samaan',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '2662',
  'Fare': 21.6792,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Youssef'},
 49: {'PassengerId': 50,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Arnold-Franchi',
  'Sex': 'female',
  'Age': 18.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '349237',
  'Fare': 17.8,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Josef (Josefine Franchi)'},
 50: {'PassengerId': 51,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Panula',
  'Sex': 'male',
  'Age': 7.0,
  'SibSp': 4,
  'Parch': 1,
  'Ticket': '3101295',
  'Fare': 39.6875,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Juha Niilo'},
 51: {'PassengerId': 52,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Nosworthy',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'A/4. 39886',
  'Fare': 7.8,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Richard Cater'},
 52: {'PassengerId': 53,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Harper',
  'Sex': 'female',
  'Age': 49.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': 'PC 17572',
  'Fare': 76.7292,
  'Cabin': 'D33',
  'Embarked': 'C',
  'First name': ' Mrs. Henry Sleeper (Myna Haxtun)'},
 53: {'PassengerId': 54,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Faunthorpe',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2926',
  'Fare': 26.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mrs. Lizzie (Elizabeth Anne Wilkinson)'},
 54: {'PassengerId': 55,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Ostby',
  'Sex': 'male',
  'Age': 65.0,
  'SibSp': 0,
  'Parch': 1,
  'Ticket': '113509',
  'Fare': 61.9792,
  'Cabin': 'B30',
  'Embarked': 'C',
  'First name': ' Mr. Engelhart Cornelius'},
 55: {'PassengerId': 56,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Woolner',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '19947',
  'Fare': 35.5,
  'Cabin': 'C52',
  'Embarked': 'S',
  'First name': ' Mr. Hugh'},
 56: {'PassengerId': 57,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Rugg',
  'Sex': 'female',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 31026',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Emily'},
 57: {'PassengerId': 58,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Novel',
  'Sex': 'male',
  'Age': 28.5,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2697',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Mansouer'},
 58: {'PassengerId': 59,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'West',
  'Sex': 'female',
  'Age': 5.0,
  'SibSp': 1,
  'Parch': 2,
  'Ticket': 'C.A. 34651',
  'Fare': 27.75,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Constance Mirium'},
 59: {'PassengerId': 60,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin',
  'Sex': 'male',
  'Age': 11.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. William Frederick'},
 60: {'PassengerId': 61,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Sirayanian',
  'Sex': 'male',
  'Age': 22.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '2669',
  'Fare': 7.2292,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Orsen'},
 61: {'PassengerId': 62,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Icard',
  'Sex': 'female',
  'Age': 38.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113572',
  'Fare': 80.0,
  'Cabin': 'B28',
  'Embarked': nan,
  'First name': ' Miss. Amelie'},
 62: {'PassengerId': 63,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Harris',
  'Sex': 'male',
  'Age': 45.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '36973',
  'Fare': 83.475,
  'Cabin': 'C83',
  'Embarked': 'S',
  'First name': ' Mr. Henry Birkhardt'},
 63: {'PassengerId': 64,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Skoog',
  'Sex': 'male',
  'Age': 4.0,
  'SibSp': 3,
  'Parch': 2,
  'Ticket': '347088',
  'Fare': 27.9,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Harald'},
 64: {'PassengerId': 65,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Stewart',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17605',
  'Fare': 27.7208,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Albert A'},
 65: {'PassengerId': 66,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Moubarek',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 1,
  'Parch': 1,
  'Ticket': '2661',
  'Fare': 15.2458,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Master. Gerios'},
 66: {'PassengerId': 67,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Nye',
  'Sex': 'female',
  'Age': 29.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 29395',
  'Fare': 10.5,
  'Cabin': 'F33',
  'Embarked': 'S',
  'First name': ' Mrs. (Elizabeth Ramell)'},
 67: {'PassengerId': 68,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Crease',
  'Sex': 'male',
  'Age': 19.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.P. 3464',
  'Fare': 8.1583,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ernest James'},
 68: {'PassengerId': 69,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Andersson',
  'Sex': 'female',
  'Age': 17.0,
  'SibSp': 4,
  'Parch': 2,
  'Ticket': '3101281',
  'Fare': 7.925,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Erna Alexandra'},
 69: {'PassengerId': 70,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Kink',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 2,
  'Parch': 0,
  'Ticket': '315151',
  'Fare': 8.6625,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Vincenz'},
 70: {'PassengerId': 71,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Jenkin',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 33111',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Stephen Curnow'},
 71: {'PassengerId': 72,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Goodwin',
  'Sex': 'female',
  'Age': 16.0,
  'SibSp': 5,
  'Parch': 2,
  'Ticket': 'CA 2144',
  'Fare': 46.9,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Miss. Lillian Amy'},
 72: {'PassengerId': 73,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Hood',
  'Sex': 'male',
  'Age': 21.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'S.O.C. 14879',
  'Fare': 73.5,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ambrose Jr'},
 73: {'PassengerId': 74,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Chronopoulos',
  'Sex': 'male',
  'Age': 26.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '2680',
  'Fare': 14.4542,
  'Cabin': nan,
  'Embarked': 'C',
  'First name': ' Mr. Apostolos'},
 74: {'PassengerId': 75,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Bing',
  'Sex': 'male',
  'Age': 32.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '1601',
  'Fare': 56.4958,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Lee'},
 75: {'PassengerId': 76,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moen',
  'Sex': 'male',
  'Age': 25.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '348123',
  'Fare': 7.65,
  'Cabin': 'F G73',
  'Embarked': 'S',
  'First name': ' Mr. Sigurd Hansen'},
 76: {'PassengerId': 77,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Staneff',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '349208',
  'Fare': 7.8958,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Ivan'},
 77: {'PassengerId': 78,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Moutal',
  'Sex': 'male',
  'Age': nan,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '374746',
  'Fare': 8.05,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Mr. Rahamin Haim'},
 78: {'PassengerId': 79,
  'Survived': 1,
  'Pclass': 2,
  'Name': 'Caldwell',
  'Sex': 'male',
  'Age': 0.83,
  'SibSp': 0,
  'Parch': 2,
  'Ticket': '248738',
  'Fare': 29.0,
  'Cabin': nan,
  'Embarked': 'S',
  'First name': ' Master. Alden Gates'},
 79: {'PassengerId': 80,
  'Survived': 1,
  'Pclass': 3,
  'Name': 'Dowdell',
  'Sex': 'female',
  'Age': 30.0,
  'SibSp': 0,
  'Parch': 0,

### Count the number of Keys in a Dictionary

In [21]:

# shows how to get the number of key-value pairs in the dictionary.
result_1 = len(df_dictionary)
print(result_1)  # 👉️ 3

890

In [22]:

result_2 = len(df_dictionary.keys())
print(result_2)  # 👉️ 3

890

####  Explicitly using the dict.keys() method

In [23]:
print(df_dictionary.keys())  # 👉️ dict_keys(['id', 'name'])

print(len(df_dictionary.keys()))  # 👉️ 2

dict_keys([0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890])
890

In [24]:
count = 0

for key, value in df_dictionary.items():
    count += 1

    print(key, value)

print(count) # 👉️ 3

0 {'PassengerId': 1, 'Survived': 0, 'Pclass': 3, 'Name': 'Braundo', 'Sex': 'male', 'Age': 22.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'A/5 21171', 'Fare': 7.25, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Owen Harris'}
2 {'PassengerId': 3, 'Survived': 1, 'Pclass': 3, 'Name': 'Heikkinen', 'Sex': 'female', 'Age': 26.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'STON/O2. 3101282', 'Fare': 7.925, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Laina'}
3 {'PassengerId': 4, 'Survived': 1, 'Pclass': 1, 'Name': 'Futrelle', 'Sex': 'female', 'Age': 35.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '113803', 'Fare': 53.1, 'Cabin': 'C123', 'Embarked': 'S', 'First name': ' Mrs. Jacques Heath (Lily May Peel)'}
4 {'PassengerId': 5, 'Survived': 0, 'Pclass': 3, 'Name': 'Allen', 'Sex': 'male', 'Age': 35.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '373450', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. William Henry'}
5 {'PassengerId': 6, 'Survived': 0, 'Pclass': 3, 'Name': 'Moran', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '330877', 'Fare': 8.4583, 'Cabin': nan, 'Embarked': 'Q', 'First name': ' Mr. James'}
6 {'PassengerId': 7, 'Survived': 0, 'Pclass': 1, 'Name': 'McCarthy', 'Sex': 'male', 'Age': 54.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '17463', 'Fare': 51.8625, 'Cabin': 'E46', 'Embarked': 'S', 'First name': ' Mr. Timothy J'}
7 {'PassengerId': 8, 'Survived': 0, 'Pclass': 3, 'Name': 'Palsson', 'Sex': 'male', 'Age': 2.0, 'SibSp': 3, 'Parch': 1, 'Ticket': '349909', 'Fare': 21.075, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Master. Gosta Leonard'}
8 {'PassengerId': 9, 'Survived': 1, 'Pclass': 3, 'Name': 'Johnson', 'Sex': 'female', 'Age': 27.0, 'SibSp': 0, 'Parch': 2, 'Ticket': '347742', 'Fare': 11.1333, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mrs. Oscar W (Elisabeth Vilhelmina Berg)'}
9 {'PassengerId': 10, 'Survived': 1, 'Pclass': 2, 'Name': 'Nasser', 'Sex': 'female', 'Age': 14.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '237736', 'Fare': 30.0708, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mrs. Nicholas (Adele Achem)'}
10 {'PassengerId': 11, 'Survived': 1, 'Pclass': 3, 'Name': 'Sandstrom', 'Sex': 'female', 'Age': 4.0, 'SibSp': 1, 'Parch': 1, 'Ticket': 'PP 9549', 'Fare': 16.7, 'Cabin': 'G6', 'Embarked': 'S', 'First name': ' Miss. Marguerite Rut'}
11 {'PassengerId': 12, 'Survived': 1, 'Pclass': 1, 'Name': 'Bonnell', 'Sex': 'female', 'Age': 58.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113783', 'Fare': 26.55, 'Cabin': 'C103', 'Embarked': 'S', 'First name': ' Miss. Elizabeth'}
12 {'PassengerId': 13, 'Survived': 0, 'Pclass': 3, 'Name': 'Saundercock', 'Sex': 'male', 'Age': 20.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A/5. 2151', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. William Henry'}
13 {'PassengerId': 14, 'Survived': 0, 'Pclass': 3, 'Name': 'Andersson', 'Sex': 'male', 'Age': 39.0, 'SibSp': 1, 'Parch': 5, 'Ticket': '347082', 'Fare': 31.275, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Anders Johan'}
14 {'PassengerId': 15, 'Survived': 0, 'Pclass': 3, 'Name': 'Vestrom', 'Sex': 'female', 'Age': 14.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '350406', 'Fare': 7.8542, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Hulda Amanda Adolfina'}
15 {'PassengerId': 16, 'Survived': 1, 'Pclass': 2, 'Name': 'Hewlett', 'Sex': 'female', 'Age': 55.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '248706', 'Fare': 16.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mrs. (Mary D Kingcome) '}
16 {'PassengerId': 17, 'Survived': 0, 'Pclass': 3, 'Name': 'Rice', 'Sex': 'male', 'Age': 2.0, 'SibSp': 4, 'Parch': 1, 'Ticket': '382652', 'Fare': 29.125, 'Cabin': nan, 'Embarked': 'Q', 'First name': ' Master. Eugene'}
17 {'PassengerId': 18, 'Survived': 1, 'Pclass': 2, 'Name': 'Williams', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '244373', 'Fare': 13.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Charles Eugene'}
18 {'PassengerId': 19, 'Survived': 0, 'Pclass': 3, 'Name': 'Vander Planke', 'Sex': 'female', 'Age': 31.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '345763', 'Fare': 18.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mrs. Julius (Emelia Maria Vandemoortele)'}
19 {'PassengerId': 20, 'Survived': 1, 'Pclass': 3, 'Name': 'Masselmani', 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '2649', 'Fare': 7.225, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mrs. Fatima'}
20 {'PassengerId': 21, 'Survived': 0, 'Pclass': 2, 'Name': 'Fynney', 'Sex': 'male', 'Age': 35.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '239865', 'Fare': 26.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Joseph J'}
21 {'PassengerId': 22, 'Survived': 1, 'Pclass': 2, 'Name': 'Beesley', 'Sex': 'male', 'Age': 34.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '248698', 'Fare': 13.0, 'Cabin': 'D56', 'Embarked': 'S', 'First name': ' Mr. Lawrence'}
22 {'PassengerId': 23, 'Survived': 1, 'Pclass': 3, 'Name': 'McGowan', 'Sex': 'female', 'Age': 15.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '330923', 'Fare': 8.0292, 'Cabin': nan, 'Embarked': 'Q', 'First name': ' Miss. Anna "Annie"'}
23 {'PassengerId': 24, 'Survived': 1, 'Pclass': 1, 'Name': 'Sloper', 'Sex': 'male', 'Age': 28.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113788', 'Fare': 35.5, 'Cabin': 'A6', 'Embarked': 'S', 'First name': ' Mr. William Thompson'}
24 {'PassengerId': 25, 'Survived': 0, 'Pclass': 3, 'Name': 'Palsson', 'Sex': 'female', 'Age': 8.0, 'SibSp': 3, 'Parch': 1, 'Ticket': '349909', 'Fare': 21.075, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Torborg Danira'}
25 {'PassengerId': 26, 'Survived': 1, 'Pclass': 3, 'Name': 'Asplund', 'Sex': 'female', 'Age': 38.0, 'SibSp': 1, 'Parch': 5, 'Ticket': '347077', 'Fare': 31.3875, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'}
26 {'PassengerId': 27, 'Survived': 0, 'Pclass': 3, 'Name': 'Emir', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '2631', 'Fare': 7.225, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mr. Farred Chehab'}
27 {'PassengerId': 28, 'Survived': 0, 'Pclass': 1, 'Name': 'Fortune', 'Sex': 'male', 'Age': 19.0, 'SibSp': 3, 'Parch': 2, 'Ticket': '19950', 'Fare': 263.0, 'Cabin': 'C23 C25 C27', 'Embarked': 'S', 'First name': ' Mr. Charles Alexander'}
28 {'PassengerId': 29, 'Survived': 1, 'Pclass': 3, 'Name': "O'Dwyer", 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '330959', 'Fare': 7.8792, 'Cabin': nan, 'Embarked': 'Q', 'First name': ' Miss. Ellen "Nellie"'}
29 {'PassengerId': 30, 'Survived': 0, 'Pclass': 3, 'Name': 'Todoroff', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '349216', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Lalio'}
30 {'PassengerId': 31, 'Survived': 0, 'Pclass': 1, 'Name': 'Uruchurtu', 'Sex': 'male', 'Age': 40.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'PC 17601', 'Fare': 27.7208, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Don. Manuel E'}
31 {'PassengerId': 32, 'Survived': 1, 'Pclass': 1, 'Name': 'Spencer', 'Sex': 'female', 'Age': nan, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17569', 'Fare': 146.5208, 'Cabin': 'B78', 'Embarked': 'C', 'First name': ' Mrs. William Augustus (Marie Eugenie)'}
32 {'PassengerId': 33, 'Survived': 1, 'Pclass': 3, 'Name': 'Glynn', 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '335677', 'Fare': 7.75, 'Cabin': nan, 'Embarked': 'Q', 'First name': ' Miss. Mary Agatha'}
33 {'PassengerId': 34, 'Survived': 0, 'Pclass': 2, 'Name': 'Wheadon', 'Sex': 'male', 'Age': 66.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 24579', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Edward H'}
34 {'PassengerId': 35, 'Survived': 0, 'Pclass': 1, 'Name': 'Meyer', 'Sex': 'male', 'Age': 28.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17604', 'Fare': 82.1708, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mr. Edgar Joseph'}
35 {'PassengerId': 36, 'Survived': 0, 'Pclass': 1, 'Name': 'Holverson', 'Sex': 'male', 'Age': 42.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '113789', 'Fare': 52.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Alexander Oskar'}
36 {'PassengerId': 37, 'Survived': 1, 'Pclass': 3, 'Name': 'Mamee', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '2677', 'Fare': 7.2292, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mr. Hanna'}
37 {'PassengerId': 38, 'Survived': 0, 'Pclass': 3, 'Name': 'Cann', 'Sex': 'male', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A./5. 2152', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Ernest Charles'}
38 {'PassengerId': 39, 'Survived': 0, 'Pclass': 3, 'Name': 'Vander Planke', 'Sex': 'female', 'Age': 18.0, 'SibSp': 2, 'Parch': 0, 'Ticket': '345764', 'Fare': 18.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Augusta Maria'}
39 {'PassengerId': 40, 'Survived': 1, 'Pclass': 3, 'Name': 'Nicola-Yarred', 'Sex': 'female', 'Age': 14.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '2651', 'Fare': 11.2417, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Miss. Jamila'}
40 {'PassengerId': 41, 'Survived': 0, 'Pclass': 3, 'Name': 'Ahlin', 'Sex': 'female', 'Age': 40.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '7546', 'Fare': 9.475, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mrs. Johan (Johanna Persdotter Larsson)'}
41 {'PassengerId': 42, 'Survived': 0, 'Pclass': 2, 'Name': 'Turpin', 'Sex': 'female', 'Age': 27.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '11668', 'Fare': 21.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mrs. William John Robert (Dorothy Ann Wonnacott)'}
42 {'PassengerId': 43, 'Survived': 0, 'Pclass': 3, 'Name': 'Kraeff', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '349253', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mr. Theodor'}
43 {'PassengerId': 44, 'Survived': 1, 'Pclass': 2, 'Name': 'Laroche', 'Sex': 'female', 'Age': 3.0, 'SibSp': 1, 'Parch': 2, 'Ticket': 'SC/Paris 2123', 'Fare': 41.5792, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Miss. Simonne Marie Anne Andree'}
44 {'PassengerId': 45, 'Survived': 1, 'Pclass': 3, 'Name': 'Devaney', 'Sex': 'female', 'Age': 19.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '330958', 'Fare': 7.8792, 'Cabin': nan, 'Embarked': 'Q', 'First name': ' Miss. Margaret Delia'}
45 {'PassengerId': 46, 'Survived': 0, 'Pclass': 3, 'Name': 'Rogers', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.C./A.4. 23567', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. William John'}
46 {'PassengerId': 47, 'Survived': 0, 'Pclass': 3, 'Name': 'Lennon', 'Sex': 'male', 'Age': nan, 'SibSp': 1, 'Parch': 0, 'Ticket': '370371', 'Fare': 15.5, 'Cabin': nan, 'Embarked': 'Q', 'First name': ' Mr. Denis'}
47 {'PassengerId': 48, 'Survived': 1, 'Pclass': 3, 'Name': "O'Driscoll", 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '14311', 'Fare': 7.75, 'Cabin': nan, 'Embarked': 'Q', 'First name': ' Miss. Bridget'}
48 {'PassengerId': 49, 'Survived': 0, 'Pclass': 3, 'Name': 'Samaan', 'Sex': 'male', 'Age': nan, 'SibSp': 2, 'Parch': 0, 'Ticket': '2662', 'Fare': 21.6792, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mr. Youssef'}
49 {'PassengerId': 50, 'Survived': 0, 'Pclass': 3, 'Name': 'Arnold-Franchi', 'Sex': 'female', 'Age': 18.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '349237', 'Fare': 17.8, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mrs. Josef (Josefine Franchi)'}
50 {'PassengerId': 51, 'Survived': 0, 'Pclass': 3, 'Name': 'Panula', 'Sex': 'male', 'Age': 7.0, 'SibSp': 4, 'Parch': 1, 'Ticket': '3101295', 'Fare': 39.6875, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Master. Juha Niilo'}
51 {'PassengerId': 52, 'Survived': 0, 'Pclass': 3, 'Name': 'Nosworthy', 'Sex': 'male', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'A/4. 39886', 'Fare': 7.8, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Richard Cater'}
52 {'PassengerId': 53, 'Survived': 1, 'Pclass': 1, 'Name': 'Harper', 'Sex': 'female', 'Age': 49.0, 'SibSp': 1, 'Parch': 0, 'Ticket': 'PC 17572', 'Fare': 76.7292, 'Cabin': 'D33', 'Embarked': 'C', 'First name': ' Mrs. Henry Sleeper (Myna Haxtun)'}
53 {'PassengerId': 54, 'Survived': 1, 'Pclass': 2, 'Name': 'Faunthorpe', 'Sex': 'female', 'Age': 29.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '2926', 'Fare': 26.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mrs. Lizzie (Elizabeth Anne Wilkinson)'}
54 {'PassengerId': 55, 'Survived': 0, 'Pclass': 1, 'Name': 'Ostby', 'Sex': 'male', 'Age': 65.0, 'SibSp': 0, 'Parch': 1, 'Ticket': '113509', 'Fare': 61.9792, 'Cabin': 'B30', 'Embarked': 'C', 'First name': ' Mr. Engelhart Cornelius'}
55 {'PassengerId': 56, 'Survived': 1, 'Pclass': 1, 'Name': 'Woolner', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '19947', 'Fare': 35.5, 'Cabin': 'C52', 'Embarked': 'S', 'First name': ' Mr. Hugh'}
56 {'PassengerId': 57, 'Survived': 1, 'Pclass': 2, 'Name': 'Rugg', 'Sex': 'female', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 31026', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Emily'}
57 {'PassengerId': 58, 'Survived': 0, 'Pclass': 3, 'Name': 'Novel', 'Sex': 'male', 'Age': 28.5, 'SibSp': 0, 'Parch': 0, 'Ticket': '2697', 'Fare': 7.2292, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mr. Mansouer'}
58 {'PassengerId': 59, 'Survived': 1, 'Pclass': 2, 'Name': 'West', 'Sex': 'female', 'Age': 5.0, 'SibSp': 1, 'Parch': 2, 'Ticket': 'C.A. 34651', 'Fare': 27.75, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Constance Mirium'}
59 {'PassengerId': 60, 'Survived': 0, 'Pclass': 3, 'Name': 'Goodwin', 'Sex': 'male', 'Age': 11.0, 'SibSp': 5, 'Parch': 2, 'Ticket': 'CA 2144', 'Fare': 46.9, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Master. William Frederick'}
60 {'PassengerId': 61, 'Survived': 0, 'Pclass': 3, 'Name': 'Sirayanian', 'Sex': 'male', 'Age': 22.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '2669', 'Fare': 7.2292, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mr. Orsen'}
61 {'PassengerId': 62, 'Survived': 1, 'Pclass': 1, 'Name': 'Icard', 'Sex': 'female', 'Age': 38.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113572', 'Fare': 80.0, 'Cabin': 'B28', 'Embarked': nan, 'First name': ' Miss. Amelie'}
62 {'PassengerId': 63, 'Survived': 0, 'Pclass': 1, 'Name': 'Harris', 'Sex': 'male', 'Age': 45.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '36973', 'Fare': 83.475, 'Cabin': 'C83', 'Embarked': 'S', 'First name': ' Mr. Henry Birkhardt'}
63 {'PassengerId': 64, 'Survived': 0, 'Pclass': 3, 'Name': 'Skoog', 'Sex': 'male', 'Age': 4.0, 'SibSp': 3, 'Parch': 2, 'Ticket': '347088', 'Fare': 27.9, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Master. Harald'}
64 {'PassengerId': 65, 'Survived': 0, 'Pclass': 1, 'Name': 'Stewart', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': 'PC 17605', 'Fare': 27.7208, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mr. Albert A'}
65 {'PassengerId': 66, 'Survived': 1, 'Pclass': 3, 'Name': 'Moubarek', 'Sex': 'male', 'Age': nan, 'SibSp': 1, 'Parch': 1, 'Ticket': '2661', 'Fare': 15.2458, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Master. Gerios'}
66 {'PassengerId': 67, 'Survived': 1, 'Pclass': 2, 'Name': 'Nye', 'Sex': 'female', 'Age': 29.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 29395', 'Fare': 10.5, 'Cabin': 'F33', 'Embarked': 'S', 'First name': ' Mrs. (Elizabeth Ramell)'}
67 {'PassengerId': 68, 'Survived': 0, 'Pclass': 3, 'Name': 'Crease', 'Sex': 'male', 'Age': 19.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.P. 3464', 'Fare': 8.1583, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Ernest James'}
68 {'PassengerId': 69, 'Survived': 1, 'Pclass': 3, 'Name': 'Andersson', 'Sex': 'female', 'Age': 17.0, 'SibSp': 4, 'Parch': 2, 'Ticket': '3101281', 'Fare': 7.925, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Erna Alexandra'}
69 {'PassengerId': 70, 'Survived': 0, 'Pclass': 3, 'Name': 'Kink', 'Sex': 'male', 'Age': 26.0, 'SibSp': 2, 'Parch': 0, 'Ticket': '315151', 'Fare': 8.6625, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Vincenz'}
70 {'PassengerId': 71, 'Survived': 0, 'Pclass': 2, 'Name': 'Jenkin', 'Sex': 'male', 'Age': 32.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'C.A. 33111', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Stephen Curnow'}
71 {'PassengerId': 72, 'Survived': 0, 'Pclass': 3, 'Name': 'Goodwin', 'Sex': 'female', 'Age': 16.0, 'SibSp': 5, 'Parch': 2, 'Ticket': 'CA 2144', 'Fare': 46.9, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Lillian Amy'}
72 {'PassengerId': 73, 'Survived': 0, 'Pclass': 2, 'Name': 'Hood', 'Sex': 'male', 'Age': 21.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'S.O.C. 14879', 'Fare': 73.5, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Ambrose Jr'}
73 {'PassengerId': 74, 'Survived': 0, 'Pclass': 3, 'Name': 'Chronopoulos', 'Sex': 'male', 'Age': 26.0, 'SibSp': 1, 'Parch': 0, 'Ticket': '2680', 'Fare': 14.4542, 'Cabin': nan, 'Embarked': 'C', 'First name': ' Mr. Apostolos'}
74 {'PassengerId': 75, 'Survived': 1, 'Pclass': 3, 'Name': 'Bing', 'Sex': 'male', 'Age': 32.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '1601', 'Fare': 56.4958, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Lee'}
75 {'PassengerId': 76, 'Survived': 0, 'Pclass': 3, 'Name': 'Moen', 'Sex': 'male', 'Age': 25.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '348123', 'Fare': 7.65, 'Cabin': 'F G73', 'Embarked': 'S', 'First name': ' Mr. Sigurd Hansen'}
76 {'PassengerId': 77, 'Survived': 0, 'Pclass': 3, 'Name': 'Staneff', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '349208', 'Fare': 7.8958, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Ivan'}
77 {'PassengerId': 78, 'Survived': 0, 'Pclass': 3, 'Name': 'Moutal', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '374746', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Rahamin Haim'}
78 {'PassengerId': 79, 'Survived': 1, 'Pclass': 2, 'Name': 'Caldwell', 'Sex': 'male', 'Age': 0.83, 'SibSp': 0, 'Parch': 2, 'Ticket': '248738', 'Fare': 29.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Master. Alden Gates'}
79 {'PassengerId': 80, 'Survived': 1, 'Pclass': 3, 'Name': 'Dowdell', 'Sex': 'female', 'Age': 30.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '364516', 'Fare': 12.475, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Elizabeth'}
80 {'PassengerId': 81, 'Survived': 0, 'Pclass': 3, 'Name': 'Waelens', 'Sex': 'male', 'Age': 22.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '345767', 'Fare': 9.0, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Achille'}
81 {'PassengerId': 82, 'Survived': 1, 'Pclass': 3, 'Name': 'Sheerlinck', 'Sex': 'male', 'Age': 29.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '345779', 'Fare': 9.5, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Jan Baptist'}
82 {'PassengerId': 83, 'Survived': 1, 'Pclass': 3, 'Name': 'McDermott', 'Sex': 'female', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': '330932', 'Fare': 7.7875, 'Cabin': nan, 'Embarked': 'Q', 'First name': ' Miss. Brigdet Delia'}
83 {'PassengerId': 84, 'Survived': 0, 'Pclass': 1, 'Name': 'Carrau', 'Sex': 'male', 'Age': 28.0, 'SibSp': 0, 'Parch': 0, 'Ticket': '113059', 'Fare': 47.1, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Francisco M'}
84 {'PassengerId': 85, 'Survived': 1, 'Pclass': 2, 'Name': 'Ilett', 'Sex': 'female', 'Age': 17.0, 'SibSp': 0, 'Parch': 0, 'Ticket': 'SO/C 14885', 'Fare': 10.5, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Miss. Bertha'}
85 {'PassengerId': 86, 'Survived': 1, 'Pclass': 3, 'Name': 'Backstrom', 'Sex': 'female', 'Age': 33.0, 'SibSp': 3, 'Parch': 0, 'Ticket': '3101278', 'Fare': 15.85, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mrs. Karl Alfred (Maria Mathilda Gustafsson)'}
86 {'PassengerId': 87, 'Survived': 0, 'Pclass': 3, 'Name': 'Ford', 'Sex': 'male', 'Age': 16.0, 'SibSp': 1, 'Parch': 3, 'Ticket': 'W./C. 6608', 'Fare': 34.375, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. William Neal'}
87 {'PassengerId': 88, 'Survived': 0, 'Pclass': 3, 'Name': 'Slocovski', 'Sex': 'male', 'Age': nan, 'SibSp': 0, 'Parch': 0, 'Ticket': 'SOTON/OQ 392086', 'Fare': 8.05, 'Cabin': nan, 'Embarked': 'S', 'First name': ' Mr. Selman Francis'}

### Check if a key exist

In [31]:
key_to_check = 20
if key_to_check in df_dictionary.keys():
    print(f"Key '{key_to_check}' exists.")
else:
    print(f"Key '{key_to_check}' does not exist.")

Key '20' exists.

In [32]:
key_to_check = 10

if key_to_check in df_dictionary:
    print(f"Key '{key_to_check}' exists.")
else:
    print(f"Key '{key_to_check}' does not exist.")

Key '10' exists.

### Convert to data frame

In [28]:
new_df = pd.DataFrame.from_dict(df_dictionary, orient='index')

In [29]:
new_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First name
0,1,0,3,Braundo,male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr. Owen Harris
2,3,1,3,Heikkinen,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss. Laina
3,4,1,1,Futrelle,female,35.0,1,0,113803,53.1000,C123,S,Mrs. Jacques Heath (Lily May Peel)
4,5,0,3,Allen,male,35.0,0,0,373450,8.0500,NaN,S,Mr. William Henry
5,6,0,3,Moran,male,NaN,0,0,330877,8.4583,NaN,Q,Mr. James